N: "local points 3" * ‚Ž…›… €Ž„ŽŒ› *

****VAntonov08.11.11****

S: "1" <R1> XHSH
*T: <R2> XHSH / œ•‘• XHSH/*
SD:0.0,-1.0
T: <R2> XHSH / ‘Œˆ›•/
SD:0.0,0.0

SD:0.0,-1.0
S: "1" <R1> XHSO
*T: <R2> XHSO / œ•‘Ž XHSO/*
SD:0.0,-2.0
T: <R2> XHSO / ‘ŽŠŽ‹ (“žŠ)/
SD:0.0,0.0

S: "1" <R1> XHSR 
*T: <R2> XHSR / œ•‘ XHSR/*
SD:0.0,-1.0
T: <R2> XHSR / ‘’€Ž“‘‘ŠŽ… (ˆŠ€)/
SD:0.0,0.0

SD:0.0,-1.0
S: "1" <R1> XHSS 
*T: <R2> XHSS / œ•‘‘ XHSR/*
SD:0.0,-2.0
T: <R2> XHSS / •ŽŒ“’Ž‚Ž (”‘)/
SD:0.0,0.0

SD:0.0,-1.0
S: "1" <R1> XHSB 
*T: <R2> XHSB / œ•‘ XHSB/*
SD:0.0,-2.0
T: <R2> XHSB / “…‚…‘’ˆŠ (ƒ‚€„……–)/
SD:0.0,0.0

S: "1" <R1> XHGP 
*T: <R2> XHGP / œ•ƒ XHGP/*
SD:0.0,-1.0
T: <R2> XHGP / ƒŽ. ‹Ÿ† (Ž’…‹Š€)/
SD:0.0,0.0

SD:0.0,-1.0
S: "1" <R1> XHSM 
*T: <R2> XHSM / œ•‘Œ XHSM/*
SD:0.0,-2.0
T: <R2> XHSM / ž†. Š“ˆ‹œ‘Š (Œ…„…‹……‚Ž)/
SD:0.0,0.0

S: "1" <R1> XHHA 
*T: <R2> XHHA / œ••€ XHHA/*
SD:0.0,-1.0
T: <R2> XHHA / •-– (’……Š)/
SD:0.0,0.0

S: "1" <R1> XHXS 
*T: <R2> XHXS / œ•œ‘ XHXS/*
SD:0.0,-1.0
T: <R2> XHXS / ‘‚Ÿ’ŽƒŽœ…/
SD:0.0,0.0

S: "1" <R1> XHXL 
*T: <R2> XHXL / œ•œ‹ XHXL/*
SD:0.0,-1.0
T: <R2> XHXL / ‹ˆ’Ž‚ŠŽ/
SD:0.0,0.0

S: "1" <R1> XHKK 
*T: <R2> XHKK / œ•ŠŠ XHKK/*
SD:0.0,-1.0
T: <R2> XHKK / •“€ (…ƒ‹ˆŠ€)/
SD:0.0,0.0

S: "1" <R1> XHKD 
*T: <R2> XHKD / œ•Š„ XHKD/*
SD:0.0,-1.0
T: <R2> XHKD / „‡…Œƒˆ (Žƒ…›‰)/
SD:0.0,0.0

S: "1" <R1> XHIU 
*T: <R2> XHIU / œ•ˆ“ XHIU/*
SD:0.0,-1.0
T: <R2> XHIU / –.“ƒ‹Ž‚€Ÿ (“„€‹Ž‰)/
SD:0.0,0.0

S: "1" <R1> XHWV
*T: <R2> XHWV / œ•‚† XHWV/*
SD:0.0,-1.0
T: <R2> XHWV / ‚Ž‡„‚ˆ†…Š€ (‘‚€Ÿ)/
SD:0.0,0.0

S: "1" <R1> XHII 
*T: <R2> XHII / œ•ˆˆ XHII/*
SD:0.0,-1.0
T: <R2> XHII / —…ˆƒŽ‚Š€ (‚…’ŸŠ)/
SD:0.0,0.0

S: "1" <R1> XHIF 
*T: <R2> XHIF / œ•ˆ” XHIF/*
SD:0.0,-1.0
T: <R2> XHIF / ‚€”Ž‹ŽŒ……‚Š€ (’Ž‰Š€)/
SD:0.0,0.0

SD:0.0,-1.0
S: "1" <R1> XHIS 
*T: <R2> XHIS / œ•ˆ‘ XHIS/*
SD:0.0,-2.0
T: <R2> XHIS / ‘ŽŠŽ‹Ž‚Š€ (‘’€‹…‚€)/
SD:0.0,0.0

S: "1" <R1> XHBE 
*T: <R2> XHBE / œ•… XHBE/*
SD:0.0,-1.0
T: <R2> XHBE / ˆŠŽ‹€…‚Š€ (…˜ˆ’…‹œ›‰)/
SD:0.0,0.0

S: "1" <R1> XHXA 
*T: <R2> XHXA / œ•œ€ XHXA/*
SD:0.0,-1.0
T: <R2> XHXA / €Œ€€Š€ (‹ˆ‘’‚…›‰)/
SD:0.0,0.0

S: "1" <R1> XHBW 
*T: <R2> XHBW / œ•‚ XHBW/*
SD:0.0,-1.0
T: <R2> XHBW / ‚Ž‡†€…‚Š€ (Š“ƒ€)/
SD:0.0,0.0

SD:0.0,1.0
S: "1" <R1> XHIB 
*T: <R2> XHIB / œ•ˆ XHIB/*
SD:0.0,0.0
T: <R2> XHIB / ‘…„……‹Ž… (‹Žƒ)/
SD:0.0,0.0

S: "1" <R1> XHBU 
*T: <R2> XHBU / œ•“ XHBU/*
SD:0.0,-1.0
T: <R2> XHBU / “Š€ˆŠ€ (Š“€Š€)/
SD:0.0,0.0

SD:0.0,-1.0
S: "1" <R1> XHBS 
*T: <R2> XHBS / œ•‘ XHBS/*
SD:0.0,-2.0
T: <R2> XHBS / ‘‚ŽŽ„›‰/
SD:0.0,0.0

S: "1" <R1> XHKG 
*T: <R2> XHKG / œ•Šƒ XHKG/*
SD:0.0,-1.0
T: <R2> XHKG / Š.“—…‰ (ŽˆŠ€)/
SD:0.0,0.0

S: "1" <R1> XHWA 
*T: <R2> XHWA / œ•‚€ XHWA/*
SD:0.0,-1.0
T: <R2> XHWA / €‘…œ…‚ (Š›Œ‘ŠŽ…)/
SD:0.0,0.0


****VAntonov08.11.11****



****VAntonov25.11.14****

S: "1" <R1> UHNU 
*T: <R2> UHNU / “•“ UHNU/*
SD:1.0,-2.0
T: <R2> UHNU / “ƒ€‹€/
SD:0.0,0.0

SD:-15.0,-2.0
T: <R2> UHSI / ˆ’““ (‚›˜Š€)/
SD:0.0,0.0

****VAntonov25.11.14****

****VAntonov13.10.17****
S: "1" <R1> N500815E1280400
T: <R2> N500815E1280400 / ’€ŒŽ‚Š€ /
SD:0.0,0.0

****VAntonov23.12.17****
SD:0.0,-1.0
S: "1" <R1> UHWG
T: <R2> UHWG / “•‚ƒ UHWG /
SD:0.0,-2.0
S: "1" <R1> UHWG
T: <R2> UHWG / „€‹œ…ƒŽ‘Š /

SD:0.0,-1.0
S: "1" <R1> UHSJ
T: <R2, RED> UHSJ / “•‘‰ UHSJ /
SD:0.0,-2.0
S: "1" <R1> UHSJ
T: <R2> UHSJ / “˜ˆ‘’›‰ /
SD:-7.0,-1.0
S: "1" <R1> UHMVL8P4
T: <R2> UHMVL8P4 / ’“ƒ“ /

SD:0.0,1.0
S: "1" <R1> UHMVL8P8
T: <R2> UHMVL8P8 /  “„‘ŠŽ… /

SD:0.0,1.0
S: "1" <R1> N44270001E132070000
T: <R2> N44270001E132070000 /  •ŽŽ‹œ (–‚…’Ž‰) /
