N: "local points"
S: "9" <R1, BLACK> UHMVL1P1
T: <BLACK, R1> UHMVL1P1 /  - †®­ª¨¥ΰ-¬λα /


*S: "9" <R1, BLACK> UHMVL1P4*
*T: <BLACK, R1> UHMVL1P4 / ƒ€ - ®£ΰ ­¨η­®¥ /*				***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL1P5*
*T: <BLACK, R1> UHMVL1P5 / …€ - ¥ΰΆ®¬ ©αª /*				***Schetinkin30.01.17***	
S: "9" <R1, BLACK> UHMVL1P6
T: <BLACK, R1> UHMVL1P6 / ‹ - 10-©ª¬ /
S: "9" <R1, BLACK> UHMVL1P7
T: <BLACK, R1> UHMVL1P7 / ‘€ - ‘¬¨ΰ­λε /
S: "9" <R1, BLACK> UHMVL1P8
T: <BLACK, R1> UHMVL1P8 / ‹… - ‹¥®­¨¤®Ά® /
*S: "9" <R1, BLACK> UHMVL1P9 *			***Schetinkin27.12.16***
*T: <BLACK, R1> UHMVL1P9 / ƒ€‹‹ - ƒ αβ¥««® /*

*S: "9" <R1, BLACK> UHMVL2P2*
*T: <BLACK, R1> UHMVL2P2 / „€‹ - ‚« ¤¨¬¨ΰ®Άª  /*				***Schetinkin03.02.17***
S: "9" <R1, BLACK> UHMVL2P3
T: <BLACK, R1> UHMVL2P3 / “ƒ€ - “αβμ-€£­¥Ά® /
S: "9" <R1, BLACK> UHMVL3P1
T: <BLACK, R1> UHMVL3P1 / ‘€ - ‘¬¨ΰ­λε /
S: "9" <R1, BLACK> UHMVL3P2
T: <BLACK, R1> UHMVL3P2 / ‹ - ΰ«®Ά® /
*S: "9" <R1, BLACK> UHMVL3P3*
*T: <BLACK, R1> UHMVL3P3 / ’““„ - ’ΰγ¤®Ά®¥ /*					***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL3P4*
*T: <BLACK, R1> UHMVL3P4 / ‹‹ - ¥««¨­α£ γ§¥­-¬λα /*			***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL3P5*
*T: <BLACK, R1> UHMVL3P5 / ‹€„ - ‚« ¤¨¬¨ΰ®Ά® /*				***Schetinkin30.01.17***
S: "9" <R1, BLACK> UHMVL4P1
T: <BLACK, R1> UHMVL4P1 / ‹€‘ - «μ¨­αª¨© /
S: "9" <R1, BLACK> UHMVL4P2
T: <BLACK, R1> UHMVL4P2 / ‚ - ‚§¬®ΰμ¥ /
S: "9" <R1, BLACK> UHMVL5P1
T: <BLACK, R1> UHMVL5P1 / ‘‹… - ‘«¥―¨ª®Άαª®£®-¬λα /

*S: "9" <R1, BLACK> UHMVL5P3*
*T: <BLACK, R1> UHMVL5P3 / ‘€ - ®ΰα ª®Ά /*					***Schetinkin30.01.17***

S: "9" <R1, BLACK> UHMVL6P2
T: <BLACK, R1> UHMVL6P2 / €’€ -  β ¬£  /
*S: "9" <R1, BLACK> UHMVL6P3*
*T: <BLACK, R1> UHMVL6P3 / ’€€ /*
S: "9" <R1, BLACK> UHMVL6P4
T: <BLACK, R1> UHMVL6P4 / €€ -  ©¬ ª ­-βΰ Ά¥ΰ§ /
S: "9" <R1, BLACK> UHMVL6P5
T: <BLACK, R1> UHMVL6P5 / €€ /
S: "9" <R1, BLACK> UHMVL6P6
T: <BLACK, R1> UHMVL6P6 / „€ /
*S: "9" <R1, BLACK> UHMVL6P7*			***Schetinkin23.05.16***
*T: <BLACK, R1> UHMVL6P7 / „€ /*
S: "9" <R1, BLACK> UHMVL6P8
T: <BLACK, R1> UHMVL6P8 / €’€ - €­βλª ­ /

S: "9" <R1, BLACK> UHMVL6P10
T: <BLACK, R1> UHMVL6P10 / „€‘€ /
* S: "9" <R1, BLACK> UHMVL6P11 *		***Schetinkin23.05.16***
* T: <BLACK, R1> UHMVL6P11 / ‘€„€ - ‘®¤ ΰª ­-ΰ¥ª  / *

S: "9" <R1, BLACK> UHMVL6P13
T: <BLACK, R1> UHMVL6P13 / “ -  ¬¥­ª  /
S: "9" <R1, BLACK> UHMVL6P14
T: <BLACK, R1> UHMVL6P14 / €€€ /
S: "9" <R1, BLACK> UHMVL6P15
T: <BLACK, R1> UHMVL6P15 / „ - ®­¤®­ /
S: "9" <R1, BLACK> UHMVL6P16
T: <BLACK, R1> UHMVL6P16 / €’€‘ - ‘β ΰβ-βΰ Ά¥ΰ§ /
S: "9" <R1, BLACK> UHMVL6P17
T: <BLACK, R1> UHMVL6P17 / ‹€€ -  «¬λ¦-¦¤,αβ, /
S: "9" <R1, BLACK> UHMVL6P18
T: <BLACK, R1> UHMVL6P18 / €€ - €η ­-βΰ Ά¥ΰ§ /
S: "9" <R1, BLACK> UHMVL6P19
T: <BLACK, R1> UHMVL6P19 / ‘“ - ®Ά®γααγΰ¨-βΰ Ά¥ΰ§ /
S: "9" <R1, BLACK> UHMVL6P20
T: <BLACK, R1> UHMVL6P20 / „€€ - „ ΅ ­¤  /
*S: "9" <R1, BLACK> UHMVL6P21*
*T: <BLACK, R1> UHMVL6P21 / ƒ - ‚¨­®£ΰ ¤®Άª  /*				***Schetinkin23.05.17***
*S: "9" <R1, BLACK> UHMVL6P22*
*T: <BLACK, R1> UHMVL6P22 / “••’ - • ΅ ΰ®Άαª-‚‹ /*				***Schetinkin06.12.18***
S: "9" <R1, BLACK> UHMVL6P23
T: <BLACK, R1> UHMVL6P23 /  - ®ηª¨ /
*S: "9" <R1, BLACK> UHMVL6P24*
*T: <BLACK, R1> UHMVL6P24 / ‘€ - ®ΰα ª®Ά® /*
S: "9" <R1, BLACK> UHMVL6P25
T: <BLACK, R1> UHMVL6P25 / … - •¥εζ¨ΰ /
S: "9" <R1, BLACK> UHMVL6P26
T: <BLACK, R1> UHMVL6P26 / ’€‘ - ‘¨β  /
S: "9" <R1, BLACK> UHMVL6P27
T: <BLACK, R1> UHMVL6P27 / … - ¨η¥Ά ο /
S: "9" <R1, BLACK> UHMVL6P28
T: <BLACK, R1> UHMVL6P28 / … /
S: "9" <R1, BLACK> UHMVL6P29
T: <BLACK, R1> UHMVL6P29 / …‹€’ - ‚¥ΰε­¨©¥ΰ¥Ά « /
S: "9" <R1, BLACK> UHMVL6P30
T: <BLACK, R1> UHMVL6P30 / …’… - ¥β¥®ΰ¨β­λ© /
S: "9" <R1, BLACK> UHMVL6P31
T: <BLACK, R1> UHMVL6P31 / ’ - ®Ά®―®ªΰ®Άª  /
S: "9" <R1, BLACK> UHMVL6P32
T: <BLACK, R1> UHMVL6P32 / ‹ -  «¨­®Ά® /
S: "9" <R1, BLACK> UHMVL6P33
T: <BLACK, R1> UHMVL6P33 / „“ - §¥ΰ­®¥ /
S: "9" <R1, BLACK> UHMVL6P34
T: <BLACK, R1> UHMVL6P34 / ‹ - —¥ΰ­λθ¥Άª  /
S: "9" <R1, BLACK> UHMVL6P35
T: <BLACK, R1> UHMVL6P35 / ’€ƒ - βΰ ¤­®¥ /
S: "9" <R1, BLACK> UHMVL6P36
T: <BLACK, R1> UHMVL6P36 / „ - ®­¤ΰ β¥­®Άª  /
S: "9" <R1, BLACK> UHMVL6P37
T: <BLACK, R1> UHMVL6P37 / €‘€€ - α­®¥ /


S: "9" <R1, BLACK> UHMVL6P40
T: <BLACK, R1> UHMVL6P40 / ‘…„ - ‘¥¤ ­ª  /
S: "9" <R1, BLACK> UHMVL7P1
T: <BLACK, R1> UHMVL7P1 / €’€ - €­βλª ­ /
* S: "9" <R1, BLACK> UHMVL7P2 *				***Schetinkin23.05.16***
* T: <BLACK, R1> UHMVL7P2 / …‘ / *
S: "9" <R1, BLACK> UHMVL7P3
T: <BLACK, R1> UHMVL7P3 / “• - ¨ΰ ­ /
* S: "9" <R1, BLACK> UHMVL7P4 *
* T: <BLACK, R1> UHMVL7P4 / €‘€“ / *		***Schetinkin24.05.16***
S: "9" <R1, BLACK> UHMVL7P5
T: <BLACK, R1> UHMVL7P5 / € /
S: "9" <R1, BLACK> UHMVL7P6
T: <BLACK, R1> UHMVL7P6 / € -  ©¬ ª ­ /
*S: "9" <R1, BLACK> UHMVL7P7*
*T: <BLACK, R1> UHMVL7P7 / € /*


S: "9" <R1, BLACK> UHMVL8P2
T: <BLACK, R1> UHMVL8P2 / ‹ - ΰ¥«μ-—«ο /
S: "9" <R1, BLACK> UHMVL8P3
T: <BLACK, R1> UHMVL8P3 / ‘€‹ƒ - “α «£¨­ /

S: "9" <R1, BLACK> UHMVL8P5
T: <BLACK, R1> UHMVL8P5 / €’ /
S: "9" <R1, BLACK> UHMVL8P6
T: <BLACK, R1> UHMVL8P6 / ’ /

S: "1" <R1, BLACK> UHMVL8P8
T: <BLACK, R1> UHMVL8P8 / “„€ - “¤αª®¥ /
*S: "9" <R1, BLACK> UHMVL9P1*			***Schetinkin28.12.16***
*T: <BLACK, R1> UHMVL9P1 / €‹€ /*
S: "9" <R1, BLACK> UHMVL9P2
T: <BLACK, R1> UHMVL9P2 / €… /
S: "9" <R1, BLACK> UHMVL9P3
T: <BLACK, R1> UHMVL9P3 / “€€ - ®― γ /
S: "9" <R1, BLACK> UHMVL9P4
T: <BLACK, R1> UHMVL9P4 / ƒ‹ - ƒ®΅¨««¨-γαβμ¥ΰ¥ª¨ /
S: "9" <R1, BLACK> UHMVL9P5
T: <BLACK, R1> UHMVL9P5 / €’ -  ­®¬  /

S: "9" <R1, BLACK> UHMVL9P7
T: <BLACK, R1> UHMVL9P7 / ƒ€‹€ -  «¬λ¦ /
S: "9" <R1, BLACK> UHMVL9P8
T: <BLACK, R1> UHMVL9P8 / ‹ /
S: "9" <R1, BLACK> UHMVL9P9
T: <BLACK, R1> UHMVL9P9 / ‘’’ - ‘β ΰβ /
S: "9" <R1, BLACK> UHMVL9P10
T: <BLACK, R1> UHMVL9P10 / € - ƒ®ΰ¨­ /
S: "9" <R1, BLACK> UHMVL9P11
T: <BLACK, R1> UHMVL9P11 / …“ - Άγΰ-γαβμ¥ΰ¥ª¨ /
S: "9" <R1, BLACK> UHMVL9P12
T: <BLACK, R1> UHMVL9P12 / ‹“„€ - „¦ «γ-®αβΰ®Ά /


*S: "9" <R1, BLACK> UHMVL10P2*
*T: <BLACK, R1> UHMVL10P2 / ƒ“’€ /*						***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL10P3*
*T: <BLACK, R1> UHMVL10P3 / € - €¬ª -γαβμ¥ΰ¥ª¨ /*		***Schetinkin30.01.17***


S: "9" <R1, BLACK> UHMVL11P2
T: <BLACK, R1> UHMVL11P2 / …‹ - ΰ¥¬¨δ-®αβΰ®Ά /
S: "9" <R1, BLACK> UHMVL11P3
T: <BLACK, R1> UHMVL11P3 / €€ - λ-ΰ¥ª  /
S: "9" <R1, BLACK> UHMVL11P4
T: <BLACK, R1> UHMVL11P4 / … - —®¬¥-ΰ¥ª  /
S: "9" <R1, BLACK> UHMVL11P5
T: <BLACK, R1> UHMVL11P5 / ‹€„€ - ‹ § ΰ¥Ά /
S: "9" <R1, BLACK> UHMVL11P6
T: <BLACK, R1> UHMVL11P6 / ‹€ - ‚¨¤ ­®Ά® /
S: "9" <R1, BLACK> UHMVL11P7
T: <BLACK, R1> UHMVL11P7 / …‹ - ¥δβ¥―¥ΰ¥£ΰγ§®η­λ©’¥ΰ¬¨­ «„¥- αβΰ¨ /
S: "9" <R1, BLACK> UHMVL11P8
T: <BLACK, R1> UHMVL11P8 / €‘’ - „¥- αβΰ¨ /

S: "9" <R1, BLACK> UHMVL11P10
T: <BLACK, R1> UHMVL11P10 / ‘…‘€ - ‡ αβΰ¥«μι¨ª /
S: "9" <R1, BLACK> UHMVL11P11
T: <BLACK, R1> UHMVL11P11 / … - †¥ΰ¥΅ζ®Ά® /

S: "9" <R1, BLACK> UHMVL11P13
T: <BLACK, R1> UHMVL11P13 / ‘“ - •γ¬¬¨ /
S: "9" <R1, BLACK> UHMVL11P14
T: <BLACK, R1> UHMVL11P14 / “‘€’ /

S: "9" <R1, BLACK> UHMVL11P16
T: <BLACK, R1> UHMVL11P16 / ‘“ - ®Ά®γααγΰ¨-βΰ Ά¥ΰ§ /
S: "9" <R1, BLACK> UHMVL12P1
T: <BLACK, R1> UHMVL12P1 / „“„ - „γ¤¨ /

S: "9" <R1, BLACK> UHMVL13P1
T: <BLACK, R1> UHMVL13P1 / ‹€„€ - ‹ § ΰ¥Ά /
S: "9" <R1, BLACK> UHMVL13P2
T: <BLACK, R1> UHMVL13P2 / … - ®«μθ®¥—®¬¥ /
S: "9" <R1, BLACK> UHMVL13P3
T: <BLACK, R1> UHMVL13P3 / €„ƒ - „¦ ®ΰ¥-βΰ Ά¥ΰ§ /
S: "9" <R1, BLACK> UHMVL13P4
T: <BLACK, R1> UHMVL13P4 / ƒ - ¨¦­¨¥ΰ®­£¥ /
S: "9" <R1, BLACK> UHMVL13P5
T: <BLACK, R1> UHMVL13P5 / …‹ - ΰ¥¬¨δ-®αβΰ®Ά /
S: "9" <R1, BLACK> UHMVL14P1
T: <BLACK, R1> UHMVL14P1 / ‘‹€ -  α«®Άª -γαβμ¥ΰ¥ª¨ /
S: "9" <R1, BLACK> UHMVL14P2
T: <BLACK, R1> UHMVL14P2 / …‘ - ‚®αªΰ¥α¥­αª®¥ /
S: "9" <R1, BLACK> UHMVL14P3
T: <BLACK, R1> UHMVL14P3 / …‘ /

S: "9" <R1, BLACK> UHMVL14P5
T: <BLACK, R1> UHMVL14P5 / „“„ - „γ¤¨ /
S: "9" <R1, BLACK> UHMVL14P6
T: <BLACK, R1> UHMVL14P6 / ‘…‘€ - ‡ αβΰ¥«μι¨ª /
S: "9" <R1, BLACK> UHMVL14P7
T: <BLACK, R1> UHMVL14P7 / “• - …€ /
S: "9" <R1, BLACK> UHMVL14P8
T: <BLACK, R1> UHMVL14P8 / … - †¥ΰ¥΅ζ®Ά® /

S: "9" <R1, BLACK> UHMVL15P2
T: <BLACK, R1> UHMVL15P2 / € /

S: "9" <R1, BLACK> UHMVL15P4
T: <BLACK, R1> UHMVL15P4 / ‹€ /
S: "9" <R1, BLACK> UHMVL15P5
T: <BLACK, R1> UHMVL15P5 / € - €­,¨­,‚®¤λ /
S: "9" <R1, BLACK> UHMVL15P6
T: <BLACK, R1> UHMVL15P6 / ‘‹€ -  α«®Άª -γαβμ¥ΰ¥ª¨ /
S: "9" <R1, BLACK> UHMVL15P7
T: <BLACK, R1> UHMVL15P7 / ’ - ®Ά®βΰ®¨ζª®¥ /
S: "9" <R1, BLACK> UHMVL15P8
T: <BLACK, R1> UHMVL15P8 / ’ /


*S: "9" <R1, BLACK> UHMVL15P12*
*T: <BLACK, R1> UHMVL15P12 / “••… /*								***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL15P14*
*T: <BLACK, R1> UHMVL15P14 / “•‰ /*								***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL15P17*
*T: <BLACK, R1> UHMVL15P17 / €„ƒ€ /*								***Schetinkin30.01.17***

S: "9" <R1, BLACK> UHMVL16P2
T: <BLACK, R1> UHMVL16P2 / €‹ -  «λθ¥Άαª®¥ /
S: "9" <R1, BLACK> UHMVL16P3
T: <BLACK, R1> UHMVL16P3 / ‹€‘ /
S: "9" <R1, BLACK> UHMVL16P4
T: <BLACK, R1> UHMVL16P4 /  - ¬-γαβμ¥ΰ¥ª¨ /

S: "9" <R1, BLACK> UHMVL16P6
T: <BLACK, R1> UHMVL16P6 / €’€ /
S: "9" <R1, BLACK> UHMVL16P7
T: <BLACK, R1> UHMVL16P7 / ’€’€ - ’ εβ  /
S: "9" <R1, BLACK> UHMVL16P8
T: <BLACK, R1> UHMVL16P8 / ‘‹€ -  α«®Άª -γαβμ¥ΰ¥ª¨ /
*S: "9" <R1, BLACK> UHMVL17P1*
*T: <BLACK, R1> UHMVL17P1 / €‘ - ‘λΰ ­μ-γαβμ¥ΰ¥ª¨ /*				***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL17P2*
*T: <BLACK, R1> UHMVL17P2 / ‘€ /*								***Schetinkin30.01.17***

*S: "9" <R1, BLACK> UHMVL17P4*
*T: <BLACK, R1> UHMVL17P4 / ‹ - ‘¥ΰ£®-¨ε ©«®Άαª /*				***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL17P5*
*T: <BLACK, R1> UHMVL17P5 / €’ - ªβο΅ΰμαª¨© /*					***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL17P6*
*T: <BLACK, R1> UHMVL17P6 / ’€’€ - ’ εβ  /*						***Schetinkin30.01.17***

S: "9" <R1, BLACK> UHMVL18P2
T: <BLACK, R1> UHMVL18P2 / ‘‹€ -  α«®Άª -γαβμ¥ΰ¥ª¨ /
*S: "9" <R1, BLACK> UHMVL18P3*
*T: <BLACK, R1> UHMVL18P3 / ‹“’ - ¥«®£«¨­ª -βΰ Ά¥ΰ§ /*
*S: "9" <R1, BLACK> UHMVL18P4*
*T: <BLACK, R1> UHMVL18P4 / €’ - ªβο΅ΰμαª¨© /*

S: "9" <R1, BLACK> UHMVL19P1
T: <BLACK, R1> UHMVL19P1 / ’ - ®Ά®βΰ®¨ζª®¥ /
S: "9" <R1, BLACK> UHMVL19P2
T: <BLACK, R1> UHMVL19P2 / ’€’€ - ’ εβ  /
S: "9" <R1, BLACK> UHMVL19P3
T: <BLACK, R1> UHMVL19P3 / ‹ - ’λΰ /
S: "9" <R1, BLACK> UHMVL19P4
T: <BLACK, R1> UHMVL19P4 / “ - ΰ®β®ª  /
S: "9" <R1, BLACK> UHMVL19P5
T: <BLACK, R1> UHMVL19P5 / …‘ - ‚®αªΰ¥α¥­αª®¥ /
S: "9" <R1, BLACK> UHMVL20P1
T: <BLACK, R1> UHMVL20P1 / ‹€„€ - ‹ § ΰ¥Ά /
S: "9" <R1, BLACK> UHMVL20P2
T: <BLACK, R1> UHMVL20P2 / ’‘…ƒ /


*S: "9" <R1, BLACK> UHMVL21P2*
*T: <BLACK, R1> UHMVL21P2 / ‹“„ - „γ«μ¤¨ /*						***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL21P3*
*T: <BLACK, R1> UHMVL21P3 / …‹ - ¥δβ¥―¥ΰ¥£ΰγ§®η­λ©’¥ΰ¬¨­ «„¥- αβΰ¨ /*				***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL21P4*
*T: <BLACK, R1> UHMVL21P4 / ‘ - ΰ«®Ά -¬λα /*					***Schetinkin30.01.17***
S: "9" <R1, BLACK> UHMVL22P1
T: <BLACK, R1> UHMVL22P1 / €‘’ - „¥- αβΰ¨ /
S: "9" <R1, BLACK> UHMVL22P2
T: <BLACK, R1> UHMVL22P2 / ‘ - ΰ«®Ά -¬λα /
S: "9" <R1, BLACK> UHMVL22P3
T: <BLACK, R1> UHMVL22P3 / ‹€…‘ - ‹ ε-¬λα /
S: "9" <R1, BLACK> UHMVL22P4
T: <BLACK, R1> UHMVL22P4 / ‘ /
S: "9" <R1, BLACK> UHMVL22P5
T: <BLACK, R1> UHMVL22P5 / „€’ - 19-©΅«®ª―®αβ /
S: "9" <R1, BLACK> UHMVL22P6
T: <BLACK, R1> UHMVL22P6 / €’“ - ‚¨ εβγ /
S: "9" <R1, BLACK> UHMVL23P1
T: <BLACK, R1> UHMVL23P1 / ‹€…‘ - ‹ ε-¬λα /
S: "9" <R1, BLACK> UHMVL23P2
T: <BLACK, R1> UHMVL23P2 / “‹ - ®£¨΅¨ /
S: "9" <R1, BLACK> UHMVL24P1
T: <BLACK, R1> UHMVL24P1 / …“ - Άγΰ-γαβμ¥ΰ¥ª¨ /
*S: "9" <R1, BLACK> UHMVL24P2*
*T: <BLACK, R1> UHMVL24P2 / “••… /*					***Schetinkin30.01.17***
S: "9" <R1, BLACK> UHMVL24P3
T: <BLACK, R1> UHMVL24P3 / €€€ /
S: "9" <R1, BLACK> UHMVL25P1
T: <BLACK, R1> UHMVL25P1 / ‘“ - •γ¬¬¨ /
S: "9" <R1, BLACK> UHMVL25P2
T: <BLACK, R1> UHMVL25P2 / €‘€ - £,β /
S: "9" <R1, BLACK> UHMVL25P3
T: <BLACK, R1> UHMVL25P3 / ‘“ - ®Ά®γααγΰ¨-βΰ Ά¥ΰ§ /
*S: "9" <R1, BLACK> UHMVL26P1*
*T: <BLACK, R1> UHMVL26P1 / …‘ - ®Ά®γααγΰ¨ /*	***Schetinkin23.05.17***
S: "9" <R1, BLACK> UHMVL26P2
T: <BLACK, R1> UHMVL26P2 / ƒ€‹€ -  «¬λ¦ /
*S: "9" <R1, BLACK> UHMVL26P3*
*T: <BLACK, R1> UHMVL26P3 / €“‘ /*				***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL26P4*
*T: <BLACK, R1> UHMVL26P4 / ƒ /*				***Schetinkin31.01.17***
S: "9" <R1, BLACK> UHMVL26P5
T: <BLACK, R1> UHMVL26P5 / ‘’’ - ‘β ΰβ /

S: "9" <R1, BLACK> UHMVL27P3
T: <BLACK, R1> UHMVL27P3 / €€ - €η ­-βΰ Ά¥ΰ§ /
S: "9" <R1, BLACK> UHMVL28P1

*T: <BLACK, R1> UHMVL29P1 / €‹ /*
*S: "9" <R1, BLACK> UHMVL29P4*			***Schetinkin28.12.16***
*T: <BLACK, R1> UHMVL29P4 / €‹€ /*

*S: "9" <R1, BLACK> UHMVL29P6*			***Schetinkin28.12.16***
*T: <BLACK, R1> UHMVL29P6 / € /*
*S: "9" <R1, BLACK> UHMVL29P10*
*T: <BLACK, R1> UHMVL29P10 / “ /*				***Schetinkin31.01.17***
S: "9" <R1, BLACK> UHMVL29P11
T: <BLACK, R1> UHMVL29P11 / ‘“ - •γ¬¬¨ /

*S: "9" <R1, BLACK> UHMVL30P1*
*T: <BLACK, R1> UHMVL30P1 / “•‰ /*					***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL30P2*
*T: <BLACK, R1> UHMVL30P2 / € /*				***Schetinkin31.01.17***

S: "9" <R1, BLACK> UHMVL30P5
T: <BLACK, R1> UHMVL30P5 / €„“ƒ - „¦ £¤ ­ -γαβμ¥ΰ¥ª¨ /

S: "9" <R1, BLACK> UHMVL30P8
T: <BLACK, R1> UHMVL30P8 / „€ - „¦ ΰ¬¥­ /
*S: "9" <R1, BLACK> UHMVL30P9*
*T: <BLACK, R1> UHMVL30P9 / …‹ /*				***Schetinkin23.05.17***
*S: "9" <R1, BLACK> UHMVL30P10*
*T: <BLACK, R1> UHMVL30P10 / “••’ - • ΅ ΰ®Άαª-‚‹ /*
*S: "9" <R1, BLACK> UHMVL31P1*
*T: <BLACK, R1> UHMVL31P1 / … - ¨η¥Ά ο /*
*S: "9" <R1, BLACK> UHMVL31P2*
*T: <BLACK, R1> UHMVL31P2 / €… - 34-©ª¬ /*
*S: "9" <R1, BLACK> UHMVL31P3*
*T: <BLACK, R1> UHMVL31P3 / „“‹€ - „¦γ«¨ε -γαβμ¥ΰ¥ª¨ /*	***Schetinkin03.02.17***
*S: "9" <R1, BLACK> UHMVL31P5*
*T: <BLACK, R1> UHMVL31P5 / ’“‘ - ’νζ-2 /*				***Schetinkin23.05.17***
S: "9" <R1, BLACK> UHMVL31P6
T: <BLACK, R1> UHMVL31P6 / “••’ - • ΅ ΰ®Άαª-‚‹ /
*S: "9" <R1, BLACK> UHMVL31P7*
*T: <BLACK, R1> UHMVL31P7 /  - ®ηª¨ /*				***Schetinkin03.02.17***
*S: "9" <R1, BLACK> UHMVL31P8*
*T: <BLACK, R1> UHMVL31P8 / ‘ - ‚®«®η ¥Άª 2-ο /*		***Schetinkin23.05.17***

*S: "9" <R1, BLACK> UHMVL32P1*
*T: <BLACK, R1> UHMVL32P1 / „€ - „¦ ΰ¬¥­ /*			***Schetinkin31.01.17***	
S: "9" <R1, BLACK> UHMVL32P2
T: <BLACK, R1> UHMVL32P2 / “ - “ΰ¬¨-ΰ¥ª  /			***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL33P1*
*T: <BLACK, R1> UHMVL33P1 / “•• - †¥«βλ©ΰ /*			***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL33P2*
*T: <BLACK, R1> UHMVL33P2 / €“’ - €γΰ /*				***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL33P3*
*T: <BLACK, R1> UHMVL33P3 / …‘ - ¥αη ­®¥ /*			***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL33P4*
*T: <BLACK, R1> UHMVL33P4 / „€‹ - „ ­¨«®Άª  /*		***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL34P1*
*T: <BLACK, R1> UHMVL34P1 / “‹€ /*					***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL34P2*
*T: <BLACK, R1> UHMVL34P2 / ‹ - «μ /*				***Schetinkin03.02.17***
*S: "9" <R1, BLACK> UHMVL34P3*
*T: <BLACK, R1> UHMVL34P3 / …‘ - ¥αη ­®¥ /*			***Schetinkin03.02.17***
S: "9" <R1, BLACK> UHMVL35P1
T: <BLACK, R1> UHMVL35P1 / ’€‘ - ‘¨β  /
*S: "9" <R1, BLACK> UHMVL35P4*
*T: <BLACK, R1> UHMVL35P4 / „“‹€ - „¦γ«¨ε -γαβμ¥ΰ¥ª¨ /*	***Schetinkin03.02.17***

*S: "9" <R1, BLACK> UHMVL36P4*
*T: <BLACK, R1> UHMVL36P4 / €“ /*					***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL36P5*
*T: <BLACK, R1> UHMVL36P5 / “€ /*					***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL36P6*
*T: <BLACK, R1> UHMVL36P6 / “•• - “€ƒ“ /*				***Schetinkin03.02.17***
*S: "9" <R1, BLACK> UHMVL37P1*
*T: <BLACK, R1> UHMVL37P1 / ‘ - ‚®«®η ¥Άª 2-ο /*	***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL37P2*
*T: <BLACK, R1> UHMVL37P2 / ‹ - «μ /*				***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL37P3*
*T: <BLACK, R1> UHMVL37P3 / “•• - “€ƒ“ /*				***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL38P1*
*T: <BLACK, R1> UHMVL38P1 / ‘ - ‚®«®η ¥Άª 2-ο /*	***Schetinkin23.05.17***
S: "9" <R1, BLACK> UHMVL38P2
T: <BLACK, R1> UHMVL38P2 / “ - “ΰ¬¨­-ΰ¥ª  /

S: "9" <R1, BLACK> UHMVL40P1
T: <BLACK, R1> UHMVL40P1 / €‘ - ¨ΰ  /
S: "9" <R1, BLACK> UHMVL41P2
T: <BLACK, R1> UHMVL41P2 / … - •¥εζ¨ΰ /
*S: "9" <R1, BLACK> UHMVL41P3*
*T: <BLACK, R1> UHMVL41P3 / ƒ€ - —¨ΰª¨ /*
S: "9" <R1, BLACK> UHMVL41P4
T: <BLACK, R1> UHMVL41P4 / ƒ - ®£¨«¥Άª  /
S: "9" <R1, BLACK> UHMVL41P5
T: <BLACK, R1> UHMVL41P5 / €€‘ - ΰ α¨ζª¨© /
S: "9" <R1, BLACK> UHMVL41P6
T: <BLACK, R1> UHMVL41P6 / ‹… - ‹¥ΰ¬®­β®Άª  /
S: "9" <R1, BLACK> UHMVL41P7
T: <BLACK, R1> UHMVL41P7 /  - ¨ª¨­ /
S: "9" <R1, BLACK> UHMVL41P8
T: <BLACK, R1> UHMVL41P8 / €‹“ - €«η ­ /
S: "9" <R1, BLACK> UHMVL41P9
T: <BLACK, R1> UHMVL41P9 / ‹€‘‹ - ‹ αβ®ηª  /
S: "9" <R1, BLACK> UHMVL41P10
T: <BLACK, R1> UHMVL41P10 / €‘€ /

S: "9" <R1, BLACK> UHMVL41P12
T: <BLACK, R1> UHMVL41P12 / …’ /
S: "9" <R1, BLACK> UHMVL41P13
T: <BLACK, R1> UHMVL41P13 / ’… - ’¨ε¬¥­¥Ά® /
S: "9" <R1, BLACK> UHMVL41P14
T: <BLACK, R1> UHMVL41P14 / ‘… - —ª «®Άαª®¥ /
S: "9" <R1, BLACK> UHMVL41P15
T: <BLACK, R1> UHMVL41P15 / ‘€„€ - ‘― ααª-„ «μ­¨© /
S: "9" <R1, BLACK> UHMVL41P16
T: <BLACK, R1> UHMVL41P16 / ‘„ - ‘¨Ά ª®Άª  /
S: "9" <R1, BLACK> UHMVL41P17
T: <BLACK, R1> UHMVL41P17 / ‘‹€ - ΰ®α« Άαª¨© /
S: "9" <R1, BLACK> UHMVL41P18
T: <BLACK, R1> UHMVL41P18 / €‘… - ®Ά®θ εβ¨­αª¨© /

S: "9" <R1, BLACK> UHMVL41P20
T: <BLACK, R1> UHMVL41P20 / €‘ - ΰ α­λ©ΰ-ΰ¨¬®ΰαª, /
S: "9" <R1, BLACK> UHMVL41P21
T: <BLACK, R1> UHMVL41P21 / €‘’€ -  §¤®«μ­®¥ /
S: "9" <R1, BLACK> UHMVL41P22
T: <BLACK, R1> UHMVL41P22 / €‘€€ - α­®¥ /


S: "9" <R1, BLACK> UHMVL42P3
T: <BLACK, R1> UHMVL42P3 / ’€ƒ - ’ Άΰ¨η ­ª  /
S: "9" <R1, BLACK> UHMVL42P4
T: <BLACK, R1> UHMVL42P4 / ‘‹€€ - ‘« Άο­ª  /
S: "9" <R1, BLACK> UHMVL42P5
T: <BLACK, R1> UHMVL42P5 / €ƒ - ΰ αª¨­® /
S: "9" <R1, BLACK> UHMVL43P1
T: <BLACK, R1> UHMVL43P1 / €‘€€ - α­®¥ /
S: "9" <R1, BLACK> UHMVL43P2
T: <BLACK, R1> UHMVL43P2 / ““ -  ¬¥­γθª  /
S: "9" <R1, BLACK> UHMVL43P3
T: <BLACK, R1> UHMVL43P3 / ’€ƒ - βΰ ¤­®¥ /
S: "9" <R1, BLACK> UHMVL43P4
T: <BLACK, R1> UHMVL43P4 / ‹‘ - ‘¬®«μ­®¥ /
S: "9" <R1, BLACK> UHMVL43P5
T: <BLACK, R1> UHMVL43P5 / ƒ - γΰ Ά¥©ª  /

S: "9" <R1, BLACK> UHMVL43P7
T: <BLACK, R1> UHMVL43P7 / ‹… - ‹¥­¨­® /
S: "9" <R1, BLACK> UHMVL43P8
T: <BLACK, R1> UHMVL43P8 / ‘‘… - ®αΆ  /

S: "9" <R1, BLACK> UHMVL43P10
T: <BLACK, R1> UHMVL43P10 / ‹€„ /
S: "9" <R1, BLACK> UHMVL43P11
T: <BLACK, R1> UHMVL43P11 / …‘’ - ‚λα®ª®£®ΰαª /
S: "9" <R1, BLACK> UHMVL43P12
T: <BLACK, R1> UHMVL43P12 / „€‹ - „ «μ­¥£®ΰαª /
S: "9" <R1, BLACK> UHMVL43P14
T: <BLACK, R1> UHMVL43P14 / “ - ¥«μ­¨η­®¥ /
*S: "9" <R1, BLACK> UHMVL43P16*
*T: <BLACK, R1> UHMVL43P16 / „€‹“ /*					***Schetinkin03.02.17***
S: "9" <R1, BLACK> UHMVL43P17
T: <BLACK, R1> UHMVL43P17 / ƒ‹“ - ƒ«γ΅¨­­®¥ /
*S: "9" <R1, BLACK> UHMVL43P18*
*T: <BLACK, R1> UHMVL43P18 / “••‹ - «®­ /*
S: "9" <R1, BLACK> UHMVL43P19
T: <BLACK, R1> UHMVL43P19 / ‘‹ - ‘®΅®«¨­λ© /
S: "9" <R1, BLACK> UHMVL43P23
T: <BLACK, R1> UHMVL43P23 / … - ¨η¥Ά ο /

S: "9" <R1, BLACK> UHMVL44P2
T: <BLACK, R1> UHMVL44P2 / ‘€ - ‡  ¬¨-γαβμ¥ΰ¥ª¨ /




S: "9" <R1, BLACK> UHMVL44P10
T: <BLACK, R1> UHMVL44P10 / €‹… -  « ο¥¬  /
S: "9" <R1, BLACK> UHMVL44P11
T: <BLACK, R1> UHMVL44P11 / “‘‘ - γααª ο-΅γεβ  /

*S: "9" <R1, BLACK> UHMVL44P18*
*T: <BLACK, R1> UHMVL44P18 / “…€ /*					***Schetinkin31.01.17***
S: "9" <R1, BLACK> UHMVL44P19
T: <BLACK, R1> UHMVL44P19 / ƒ - γΰ Ά¥©ª  /

S: "9" <R1, BLACK> UHMVL45P2
T: <BLACK, R1> UHMVL45P2 / ‘’ - ΰ¨αβ ­μ /
S: "9" <R1, BLACK> UHMVL45P3
T: <BLACK, R1> UHMVL45P3 / €‘€ - €­¨α¨¬®Άª  /

S: "9" <R1, BLACK> UHMVL45P5
T: <BLACK, R1> UHMVL45P5 / €… - ¨¥Άª  /
S: "9" <R1, BLACK> UHMVL45P6
T: <BLACK, R1> UHMVL45P6 / € - ΰ¥®΅ΰ ¦¥­¨¥ /
S: "9" <R1, BLACK> UHMVL45P7
T: <BLACK, R1> UHMVL45P7 / …‹„€ - ‚ «¥­β¨­ /
S: "9" <R1, BLACK> UHMVL45P8
T: <BLACK, R1> UHMVL45P8 / ‹ƒ - ¨«®£ΰ ¤®Ά® /
S: "9" <R1, BLACK> UHMVL45P9
T: <BLACK, R1> UHMVL45P9 / ƒ‹€ - «μ£  /
S: "9" <R1, BLACK> UHMVL45P10
T: <BLACK, R1> UHMVL45P10 / ‘€ - ‘¥ΰ δ¨¬®Άª  /
S: "9" <R1, BLACK> UHMVL45P11
T: <BLACK, R1> UHMVL45P11 / €‹ƒ /

*S: "9" <R1, BLACK> UHMVL45P14*
*T: <BLACK, R1> UHMVL45P14 / “ /*					***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL45P15*
*T: <BLACK, R1> UHMVL45P15 / “…€ /*					***Schetinkin31.01.17***
S: "9" <R1, BLACK> UHMVL45P16
T: <BLACK, R1> UHMVL45P16 / „“ - §¥ΰ­®¥ /
S: "9" <R1, BLACK> UHMVL45P18
T: <BLACK, R1> UHMVL45P18 / ’… - ’¨ε¬¥­¥Ά® /

S: "9" <R1, BLACK> UHMVL46P3
T: <BLACK, R1> UHMVL46P3 / €… -  ¬¥­μ-λ΅®«®Ά /
S: "9" <R1, BLACK> UHMVL46P4
T: <BLACK, R1> UHMVL46P4 / ‘„ - ‘¨Ά ª®Άª  /
S: "9" <R1, BLACK> UHMVL47P1
T: <BLACK, R1> UHMVL47P1 / ‘€„€ - ‘― ααª-„ «μ­¨© /
S: "9" <R1, BLACK> UHMVL47P2
T: <BLACK, R1> UHMVL47P2 / “‹ -  «¨­®Άª  /
S: "9" <R1, BLACK> UHMVL47P3
T: <BLACK, R1> UHMVL47P3 / ‹ - —¥ΰ­λθ¥Άª  /


S: "9" <R1, BLACK> UHMVL48P1
T: <BLACK, R1> UHMVL48P1 / ‹ - —¥ΰ­λθ¥Άª  /
S: "9" <R1, BLACK> UHMVL48P3
T: <BLACK, R1> UHMVL48P3 / ƒ - γΰ Ά¥©ª  /
*S: "9" <R1, BLACK> UHMVL48P4*
*T: <BLACK, R1> UHMVL48P4 / €„€ƒ /*					***Schetinkin31.01.17***
S: "9" <R1, BLACK> UHMVL49P1	
T: <BLACK, R1> UHMVL49P1 / ’€ƒ - βΰ ¤­®¥ /

S: "9" <R1, BLACK> UHMVL50P1
T: <BLACK, R1> UHMVL50P1 / €‘€€ - α­®¥ /
S: "9" <R1, BLACK> UHMVL50P2
T: <BLACK, R1> UHMVL50P2 / €‹…‘ - €«¥ªα¥¥Άª  /
S: "9" <R1, BLACK> UHMVL50P3
T: <BLACK, R1> UHMVL50P3 / €‘ - ΰ α­λ©ΰ-ΰ¨¬®ΰαª /
S: "9" <R1, BLACK> UHMVL51P1
T: <BLACK, R1> UHMVL51P1 / €‹…‘ - €«¥ªα¥¥Άª  /
S: "9" <R1, BLACK> UHMVL51P3
T: <BLACK, R1> UHMVL51P3 / ’€ƒ - βΰ ¤­®¥ /
S: "9" <R1, BLACK> UHMVL52P2
T: <BLACK, R1> UHMVL52P2 / ‹‘ - ‘¬®«μ­®¥ /
S: "9" <R1, BLACK> UHMVL53P1
T: <BLACK, R1> UHMVL53P1 / €‘… - ®Ά®θ εβ¨­αª¨© /
S: "9" <R1, BLACK> UHMVL53P5
T: <BLACK, R1> UHMVL53P5 / ‹ - —¥ΰ­λθ¥Άª  /
S: "9" <R1, BLACK> UHMVL53P7
T: <BLACK, R1> UHMVL53P7 / „“ - §¥ΰ­®¥ /
S: "9" <R1, BLACK> UHMVL53P8
T: <BLACK, R1> UHMVL53P8 / ‹ -  «¨­®Ά® /

*S: "9" <R1, BLACK> UHMVL54P1*				***Schetinkin27.12.16***
*T: <BLACK, R1> UHMVL54P1 / “ -  ¬¥­ª  /*

S: "9" <R1, BLACK> UHMVL55P2
T: <BLACK, R1> UHMVL55P2 / „ - ®­¤ΰ β¥­®Άª  /

S: "9" <R1, BLACK> UHMVL56P3
T: <BLACK, R1> UHMVL56P3 / €‘’€ -  §¤®«μ­®¥ /
S: "9" <R1, BLACK> UHMVL56P4
T: <BLACK, R1> UHMVL56P4 / ’€ƒ - ’ Άΰ¨η ­ª  /
S: "9" <R1, BLACK> UHMVL57P1
T: <BLACK, R1> UHMVL57P1 / ‘’ - ΰ¨αβ ­μ /
S: "9" <R1, BLACK> UHMVL57P3
T: <BLACK, R1> UHMVL57P3 / …‘… - ‘¥ΰ£¥¥Άª  /
*S: "9" <R1, BLACK> UHMVL57P4*
*T: <BLACK, R1> UHMVL57P4 / …€‹ /*				***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL57P5*
*T: <BLACK, R1> UHMVL57P5 / €„€ƒ /*				***Schetinkin31.01.17***

*S: "9" <R1, BLACK> UHMVL58P1*
*T: <BLACK, R1> UHMVL58P1 / €„€ƒ /*				***Schetinkin31.01.17***
S: "9" <R1, BLACK> UHMVL58P2
T: <BLACK, R1> UHMVL58P2 / …‘… - ‘¥ΰ£¥¥Άª  /
S: "9" <R1, BLACK> UHMVL58P3
T: <BLACK, R1> UHMVL58P3 / ‘€ - ”ΰ¥­ζ¥Άª  /
S: "9" <R1, BLACK> UHMVL58P4
T: <BLACK, R1> UHMVL58P4 / €‘€ - €­¨α¨¬®Άª  /
S: "9" <R1, BLACK> UHMVL59P1
T: <BLACK, R1> UHMVL59P1 / ‘€ - ”ΰ¥­ζ¥Άª  /

S: "9" <R1, BLACK> UHMVL59P4
T: <BLACK, R1> UHMVL59P4 / €… - ¨¥Άª  /
S: "9" <R1, BLACK> UHMVL59P5
T: <BLACK, R1> UHMVL59P5 / ‹ - ‹ §® /
S: "9" <R1, BLACK> UHMVL59P7
T: <BLACK, R1> UHMVL59P7 / ‹ƒ - ¨«®£ΰ ¤®Ά® /
S: "9" <R1, BLACK> UHMVL60P1
T: <BLACK, R1> UHMVL60P1 / ‹ƒ - ¨«®£ΰ ¤®Ά® /
S: "9" <R1, BLACK> UHMVL60P2
T: <BLACK, R1> UHMVL60P2 / ‹ - ‹ §® /
S: "9" <R1, BLACK> UHMVL60P3
T: <BLACK, R1> UHMVL60P3 / …‘… - ‘¥ΰ£¥¥Άª  /
S: "9" <R1, BLACK> UHMVL61P1
T: <BLACK, R1> UHMVL61P1 / €… - ¨¥Άª  /

S: "9" <R1, BLACK> UHMVL62P2
T: <BLACK, R1> UHMVL62P2 / ‹ - ‹ §® /
S: "9" <R1, BLACK> UHMVL63P1
T: <BLACK, R1> UHMVL63P1 / …‹„€ - ‚ «¥­β¨­ /
S: "9" <R1, BLACK> UHMVL64P1
T: <BLACK, R1> UHMVL64P1 / ‘… - —ª «®Άαª®¥ /
*S: "9" <R1, BLACK> UHMVL64P2*
*T: <BLACK, R1> UHMVL64P2 / “ /*				***Schetinkin31.01.17***
S: "9" <R1, BLACK> UHMVL64P3
T: <BLACK, R1> UHMVL64P3 / ‹ -  «¨­®Ά® /
S: "9" <R1, BLACK> UHMVL64P4
T: <BLACK, R1> UHMVL64P4 / “ - ¥«μ­¨η­®¥ /
*S: "9" <R1, BLACK> UHMVL64P5*
*T: <BLACK, R1> UHMVL64P5 / ’€“ƒ€ /*				***Schetinkin31.01.17***



S: "9" <R1, BLACK> UHMVL65P2
T: <BLACK, R1> UHMVL65P2 / “„ /
S: "9" <R1, BLACK> UHMVL65P3
T: <BLACK, R1> UHMVL65P3 / ’ - ®Ά®―®ªΰ®Άª  /

S: "9" <R1, BLACK> UHMVL65P5
T: <BLACK, R1> UHMVL65P5 / ƒ‹“ - ƒ«γ΅¨­­®¥ /
S: "9" <R1, BLACK> UHMVL65P6
T: <BLACK, R1> UHMVL65P6 / ‘…’‹ - ‡®«®β®© /


S: "9" <R1, BLACK> UHMVL65P9
T: <BLACK, R1> UHMVL65P9 / ‘€ - ‡  ¬¨-γαβμ¥ΰ¥ª¨ /
*S: "9" <R1, BLACK> UHMVL66P1*
*T: <BLACK, R1> UHMVL66P1 / “ /*				***Schetinkin31.01.17***
S: "9" <R1, BLACK> UHMVL66P3
T: <BLACK, R1> UHMVL66P3 / …‹€’ - ‚¥ΰε­¨©¥ΰ¥Ά « /
*S: "9" <R1, BLACK> UHMVL66P4*
*T: <BLACK, R1> UHMVL66P4 /  /*				***Schetinkin030.02.17***
S: "9" <R1, BLACK> UHMVL66P5
T: <BLACK, R1> UHMVL66P5 / … - ¨η¥Ά ο /

S: "9" <R1, BLACK> UHMVL67P2
T: <BLACK, R1> UHMVL67P2 / “‘ /
S: "9" <R1, BLACK> UHMVL67P3
T: <BLACK, R1> UHMVL67P3 / “ - γΰ®Άª  /
S: "9" <R1, BLACK> UHMVL67P4
T: <BLACK, R1> UHMVL67P4 / …’… - ¥β¥®ΰ¨β­λ© /
S: "9" <R1, BLACK> UHMVL67P5
T: <BLACK, R1> UHMVL67P5 / ‹ /
S: "9" <R1, BLACK> UHMVL68P1
T: <BLACK, R1> UHMVL68P1 / ‹€‘‹ - ‹ αβ®ηª  /
S: "9" <R1, BLACK> UHMVL68P2
T: <BLACK, R1> UHMVL68P2 / …’… - ¥β¥®ΰ¨β­λ© /

S: "9" <R1, BLACK> UHMVL68P4
T: <BLACK, R1> UHMVL68P4 / “ - ¥«μ­¨η­®¥ /
S: "9" <R1, BLACK> UHMVL68P5
T: <BLACK, R1> UHMVL68P5 / ……‘ - ‘¥ΰ¥΅ΰο­ª -βΰ Ά¥ΰ§ /

S: "9" <R1, BLACK> UHMVL69P1
T: <BLACK, R1> UHMVL69P1 / “ - γΰ®Άª  /
S: "9" <R1, BLACK> UHMVL69P2
T: <BLACK, R1> UHMVL69P2 / ’ - ®Ά®―®ªΰ®Άª  /
S: "9" <R1, BLACK> UHMVL70P1
T: <BLACK, R1> UHMVL70P1 / ‹€‘‹ - ‹ αβ®ηª  /
S: "9" <R1, BLACK> UHMVL70P2
T: <BLACK, R1> UHMVL70P2 / …‹€’ - ‚¥ΰε­¨©¥ΰ¥Ά « /
*S: "9" <R1, BLACK> UHMVL70P3*
*T: <BLACK, R1> UHMVL70P3 / “••‹ - «®­ /*

S: "9" <R1, BLACK> UHMVL71P1
T: <BLACK, R1> UHMVL71P1 / „€‹ - „ «μ­¥£®ΰαª /
S: "9" <R1, BLACK> UHMVL71P2
T: <BLACK, R1> UHMVL71P2 / …€ - —¥ΰ¥¬θ ­λ-βΰ Ά¥ΰ§ /
S: "9" <R1, BLACK> UHMVL71P3
T: <BLACK, R1> UHMVL71P3 / …€ /

S: "9" <R1, BLACK> UHMVL71P5
T: <BLACK, R1> UHMVL71P5 / ‹€„ /
S: "9" <R1, BLACK> UHMVL71P6
T: <BLACK, R1> UHMVL71P6 / € - ¥ΰ¥Ά «-’¥ΰ­¥©αª¨© /

*S: "9" <R1, BLACK> UHMVL71P8*
*T: <BLACK, R1> UHMVL71P8 / ’€“ƒ€ /*						***Schetinkin31.01.17***
S: "9" <R1, BLACK> UHMVL72P1
T: <BLACK, R1> UHMVL72P1 / €‹… -  « ο¥¬  /
*S: "9" <R1, BLACK> UHMVL72P3*
*T: <BLACK, R1> UHMVL72P3 / ’€“ƒ€ /*						***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL72P4*
*T: <BLACK, R1> UHMVL72P4 / „…‘“ /*						***Schetinkin31.01.17***
S: "9" <R1, BLACK> UHMVL73P1
T: <BLACK, R1> UHMVL73P1 / ƒ‹“ - ƒ«γ΅¨­­®¥ /
*S: "9" <R1, BLACK> UHMVL73P2*
*T: <BLACK, R1> UHMVL73P2 / “•’‚ /*							***Schetinkin31.01.17***
S: "9" <R1, BLACK> UHMVL73P3
T: <BLACK, R1> UHMVL73P3 / ‘ƒ€ /



S: "9" <R1, BLACK> UHMVL74P1
T: <BLACK, R1> UHMVL74P1 / ‘‹ - ‘®΅®«¨­λ© /
S: "9" <R1, BLACK> UHMVL74P2
T: <BLACK, R1> UHMVL74P2 / ‘ƒ€ /


*S: "9" <R1, BLACK> UHMVL76P2*
*T: <BLACK, R1> UHMVL76P2 / €€‘“ /*						***Schetinkin31.01.17***

*S: "9" <R1, BLACK> UHMVL78P1*
*T: <BLACK, R1> UHMVL78P1 / ‹€„ /*						***Schetinkin03.02.17***
S: "9" <R1, BLACK> UHMVL78P2
T: <BLACK, R1> UHMVL78P2 / ‘…’‹ - ‡®«®β®© /
S: "9" <R1, BLACK> UHMVL79P1
T: <BLACK, R1> UHMVL79P1 / “• -  ΰ-ξ¥«μ /
S: "9" <R1, BLACK> UHMVL79P2
T: <BLACK, R1> UHMVL79P2 / „ - ®­¤¥ΰ /
S: "9" <R1, BLACK> UHMVL79P3
T: <BLACK, R1> UHMVL79P3 / „ /

*S: "9" <R1, BLACK> UHMVL79P5*
*T: <BLACK, R1> UHMVL79P5 / ““ /*
*S: "9" <R1, BLACK> UHMVL79P6*
*T: <BLACK, R1> UHMVL79P6 / €…‹ /*
*S: "9" <R1, BLACK> UHMVL79P7*
*T: <BLACK, R1> UHMVL79P7 / “•’ - ’ α-ΰοε /*
*S: "9" <R1, BLACK> UHMVL79P8*
*T: <BLACK, R1> UHMVL79P8 / €„€ -  ¤ ªη ­ /*
*S: "9" <R1, BLACK> UHMVL79P9*
*T: <BLACK, R1> UHMVL79P9 / €ƒ‘“ /*
*S: "9" <R1, BLACK> UHMVL79P10*
*T: <BLACK, R1> UHMVL79P10 / “€‘ - “ΰ ª /*
S: "9" <R1, BLACK> UHMVL80P1
T: <BLACK, R1> UHMVL80P1 / €ƒ“‘ - οη  /
S: "9" <R1, BLACK> UHMVL80P2
T: <BLACK, R1> UHMVL80P2 / …… /
*S: "9" <R1, BLACK> UHMVL80P3*
*T: <BLACK, R1> UHMVL80P3 / €‘ /*

*S: "9" <R1, BLACK> UHMVL80P5*
*T: <BLACK, R1> UHMVL80P5 / „ /*
*S: "9" <R1, BLACK> UHMVL80P6*
*T: <BLACK, R1> UHMVL80P6 / €„€ - –¨― ­¤  /*
*S: "9" <R1, BLACK> UHMVL80P7*
*T: <BLACK, R1> UHMVL80P7 / € - €¨¬ /*
*S: "9" <R1, BLACK> UHMVL80P8*
*T: <BLACK, R1> UHMVL80P8 / “•– - ¥«μª η¨-ΰ Άλ¥ /*
*S: "9" <R1, BLACK> UHMVL80P9*
*T: <BLACK, R1> UHMVL80P9 / “…… - ¥«μª η¨-‹¥Άλ¥ /*
*S: "9" <R1, BLACK> UHMVL81P1*
*T: <BLACK, R1> UHMVL81P1 / “• -  ΰ-ξ¥«μ /*
*S: "9" <R1, BLACK> UHMVL81P2*
*T: <BLACK, R1> UHMVL81P2 / „€’“ - „ξα¬ ª¨β-γαβμ¥ΰ¥ª¨ /*
*S: "9" <R1, BLACK> UHMVL81P3*
*T: <BLACK, R1> UHMVL81P3 / …“ - γΰ¥ο /*
*S: "9" <R1, BLACK> UHMVL81P4*
*T: <BLACK, R1> UHMVL81P4 / €„€ - –¨― ­¤  /*
*S: "9" <R1, BLACK> UHMVL81P5*
*T: <BLACK, R1> UHMVL81P5 / €ƒ“ /*
*S: "9" <R1, BLACK> UHMVL81P6*
*T: <BLACK, R1> UHMVL81P6 / “•’ - ’ α-ΰοε /*
*S: "9" <R1, BLACK> UHMVL81P7*
*T: <BLACK, R1> UHMVL81P7 / €’“‹ /*
*S: "9" <R1, BLACK> UHMVL81P8*
*T: <BLACK, R1> UHMVL81P8 / €’€“ - €β ­μ¤¦ -γαβμ¥ΰ¥ª¨ /*
*S: "9" <R1, BLACK> UHMVL81P9*
*T: <BLACK, R1> UHMVL81P9 / “ƒ“ - “£ ­ª ­-γαβμ¥ΰ¥ª¨ /*
*S: "9" <R1, BLACK> UHMVL81P10*
*T: <BLACK, R1> UHMVL81P10 / ’€„€ - β ­¤¦  /*
*S: "9" <R1, BLACK> UHMVL81P11			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL81P11 / …’€“ - β ­¤¦ -γαβμ¥ΰ¥ª¨ /*

*S: "9" <R1, BLACK> UHMVL81P13			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL81P13 / €“ -  «β ­-γαβμ¥ΰ¥ª¨ /*

S: "9" <R1, BLACK> UHMVL82P2
T: <BLACK, R1> UHMVL82P2 / €ƒ„ /
S: "9" <R1, BLACK> UHMVL82P3
T: <BLACK, R1> UHMVL82P3 / ƒ“„€ /

*S: "9" <R1, BLACK> UHMVL83P1			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL83P1 / “•– - ¥«μª η¨-ΰ Άλ¥ /*
*S: "9" <R1, BLACK> UHMVL83P2			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL83P2 / ‘ /*
*S: "9" <R1, BLACK> UHMVL83P3			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL83P3 / € /*
*S: "9" <R1, BLACK> UHMVL83P4			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL83P4 / “ - ®­¤¥ΰ-γαβμ¥ΰ¥ª¨ /*
*S: "9" <R1, BLACK> UHMVL83P5			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL83P5 / „ - ®­¤¥ΰ /*
*S: "9" <R1, BLACK> UHMVL84P1			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL84P1 / “•– - ¥«μª η¨-ΰ Άλ¥ /*
*S: "9" <R1, BLACK> UHMVL84P2			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL84P2 / €€ /*
*S: "9" <R1, BLACK> UHMVL84P3			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL84P3 / …„€ - ΰ¥αβοε /*
*S: "9" <R1, BLACK> UHMVL84P4			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL84P4 / “•’ - ’ α-ΰοε /*
*S: "9" <R1, BLACK> UHMVL84P5			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL84P5 / € - €¨¬ /*
S: "9" <R1, BLACK> UHMVL85P1
T: <BLACK, R1> UHMVL85P1 / €’€ - €­βλª ­ /
S: "9" <R1, BLACK> UHMVL85P2
T: <BLACK, R1> UHMVL85P2 / €ƒ€“ /
*S: "9" <R1, BLACK> UHMVL85P3*			*Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL85P3 / €… /*
S: "9" <R1, BLACK> UHMVL85P4
T: <BLACK, R1> UHMVL85P4 / €“ /
*S: "9" <R1, BLACK> UHMVL85P5*			*Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL85P5 / €ƒ - γΰγ­£ /*
*S: "9" <R1, BLACK> UHMVL85P6*			*Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL85P6 / “’ - ®ªγΰ /*
*S: "9" <R1, BLACK> UHMVL85P7*			*Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL85P7 / €€€ /*
*S: "9" <R1, BLACK> UHMVL85P8*			*Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL85P8 / “•– - ¥«μª η¨-ΰ Άλ¥ /*
*S: "9" <R1, BLACK> UHMVL85P9*			*Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL85P9 / €ƒ€ /*
*S: "9" <R1, BLACK> UHMVL85P10*			*Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL85P10 / €‘€ /*

*S: "9" <R1, BLACK> UHMVL85P12*			*Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL85P12 / €“ /*
S: "9" <R1, BLACK> UHMVL85P13
T: <BLACK, R1> UHMVL85P13 / €… /
*S: "9" <R1, BLACK> UHMVL85P14*			*Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL85P14 / €“ -  «β ­-γαβμ¥ΰ¥ª¨ /*
*S: "9" <R1, BLACK> UHMVL85P15*			*Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL85P15 / “ƒ“ - “£ ­ª ­-γαβμ¥ΰ¥ª¨ /*
*S: "9" <R1, BLACK> UHMVL86P1			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL86P1 / “• -  ΰ-ξ¥«μ /*
*S: "9" <R1, BLACK> UHMVL86P2			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL86P2 / ‘€’ - ‘ δΰ®­ /*
*S: "9" <R1, BLACK> UHMVL86P3			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL86P3 / „“€‘ - „ξα¬ ª¨β /*
*S: "9" <R1, BLACK> UHMVL86P4			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL86P4 /  - ¨ª¨ /*
*S: "9" <R1, BLACK> UHMVL86P5			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL86P5 / “ - ®­¤¥ΰ-γαβμ¥ΰ¥ª¨ /*
*S: "9" <R1, BLACK> UHMVL86P6			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL86P6 / „ /*
*S: "9" <R1, BLACK> UHMVL86P7			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL86P7 / ““ /*
*S: "9" <R1, BLACK> UHMVL87P1			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL87P1 / „“€‘ - „ξα¬ ª¨β /*
*S: "9" <R1, BLACK> UHMVL87P2			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL87P2 / „€’“ - „ξα¬ ª¨β-γαβμ¥ΰ¥ª¨ /*
*S: "9" <R1, BLACK> UHMVL87P3			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL87P3 / €“ /*
*S: "9" <R1, BLACK> UHMVL87P4			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL87P4 / € - €¨¬ /*
*S: "9" <R1, BLACK> UHMVL87P5			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL87P5 / …„€ - ΰ¥αβοε /*
*S: "9" <R1, BLACK> UHMVL88P1			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL88P1 / € -  ©¬ ª ­ /*
*S: "9" <R1, BLACK> UHMVL88P2			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL88P2 / €€ -  ©¬ ª ­-βΰ Ά¥ΰ§ /*
*S: "9" <R1, BLACK> UHMVL88P3			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL88P3 / €’ /*
*S: "9" <R1, BLACK> UHMVL88P4			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL88P4 / “• -  ΰ-ξ¥«μ /*
*S: "9" <R1, BLACK> UHMVL88P5			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL88P5 / “‹€‹ - “« ε ­ /*
*S: "9" <R1, BLACK> UHMVL88P6			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL88P6 / €ƒ - γΰγ­£ /*
*S: "9" <R1, BLACK> UHMVL88P7			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL88P7 / „€’“ - „ξα¬ ª¨β-γαβμ¥ΰ¥ª¨ /*
*S: "9" <R1, BLACK> UHMVL88P8			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL88P8 / “ - ®­¤¥ΰ-γαβμ¥ΰ¥ª¨ /*

*S: "9" <R1, BLACK> UHMVL89P2			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL89P2 / €’€‹€ /*
S: "9" <R1, BLACK> UHMVL89P3
T: <BLACK, R1> UHMVL89P3 / ’’’€ - ’®ββ -γαβμ¥ΰ¥ª¨ /
S: "9" <R1, BLACK> UHMVL89P4
T: <BLACK, R1> UHMVL89P4 / ’““ - ’γΰ¬ ­¤¦ -γαβμ¥ΰ¥ª¨ /
*S: "9" <R1, BLACK> UHMVL89P5			Schetinkin17.11.15*
*T: <BLACK, R1> UHMVL89P5 / €„ /*
S: "9" <R1, BLACK> UHMVL89P6
T: <BLACK, R1> UHMVL89P6 / “€“ - “¥­¬ -γαβμ¥ΰ¥ª¨ /
S: "9" <R1, BLACK> UHMVL89P7
T: <BLACK, R1> UHMVL89P7 / “‹“€ - “«μο /

S: "9" <R1, BLACK> UHMVL90P2
T: <BLACK, R1> UHMVL90P2 / €ƒ - β¬¥βª 221 /
S: "9" <R1, BLACK> UHMVL90P3
T: <BLACK, R1> UHMVL90P3 / “ /

S: "9" <R1, BLACK> UHMVL90P5
T: <BLACK, R1> UHMVL90P5 / “…ƒ€ - “¥£  /
S: "9" <R1, BLACK> UHMVL90P6
T: <BLACK, R1> UHMVL90P6 / …’€ - ¥β ­¤  /
S: "9" <R1, BLACK> UHMVL91P1
T: <BLACK, R1> UHMVL91P1 / …’€ - ¥β ­¤  /

S: "9" <R1, BLACK> UHMVL91P3
T: <BLACK, R1> UHMVL91P3 / ‹€’… /
S: "9" <R1, BLACK> UHMVL91P4
T: <BLACK, R1> UHMVL91P4 / …’€ - ¥¤Ά¥¦ª  /

S: "9" <R1, BLACK> UHMVL92P1
T: <BLACK, R1> UHMVL92P1 / ‹€ - ­ο /
S: "9" <R1, BLACK> UHMVL92P2
T: <BLACK, R1> UHMVL92P2 / ’€‘ /
S: "9" <R1, BLACK> UHMVL92P3
T: <BLACK, R1> UHMVL92P3 / ƒ - ƒΰ®¬®Άαª ο /

S: "9" <R1, BLACK> UHMVL93P2
T: <BLACK, R1> UHMVL93P2 / ’ƒ /
S: "9" <R1, BLACK> UHMVL93P4
T: <BLACK, R1> UHMVL93P4 / ‘…‘€ /

S: "9" <R1, BLACK> UHMVL93P6
T: <BLACK, R1> UHMVL93P6 / “„ /


S: "9" <R1, BLACK> UHMVL93P9
T: <BLACK, R1> UHMVL93P9 / ‘…‹€„ /
S: "9" <R1, BLACK> UHMVL93P10
T: <BLACK, R1> UHMVL93P10 / ƒ„ /
S: "9" <R1, BLACK> UHMVL93P11
T: <BLACK, R1> UHMVL93P11 / ‹ /

S: "9" <R1, BLACK> UHMVL93P13
T: <BLACK, R1> UHMVL93P13 / “‘ /
S: "9" <R1, BLACK> UHMVL93P14
T: <BLACK, R1> UHMVL93P14 / €„“ /
S: "9" <R1, BLACK> UHMVL93P15
T: <BLACK, R1> UHMVL93P15 / “„€ - “¤αª®¥ /
S: "9" <R1, BLACK> UHMVL93P16
T: <BLACK, R1> UHMVL93P16 / €’€ - €­βλª ­ /
* S: "9" <R1, BLACK> UHMVL93P17 *				***Schetinkin23.05.16***
* T: <BLACK, R1> UHMVL93P17 / “‹‘ / *
S: "9" <R1, BLACK> UHMVL93P18
T: <BLACK, R1> UHMVL93P18 / €‘’“ /
S: "9" <R1, BLACK> UHMVL93P19
T: <BLACK, R1> UHMVL93P19 / “ /
S: "9" <R1, BLACK> UHMVL93P20
T: <BLACK, R1> UHMVL93P20 / “‹ /

S: "9" <R1, BLACK> UHMVL93P22
T: <BLACK, R1> UHMVL93P22 / €ƒ“‘ - οη  /
S: "9" <R1, BLACK> UHMVL93P23
T: <BLACK, R1> UHMVL93P23 / …“ /

S: "9" <R1, BLACK> UHMVL93P25
T: <BLACK, R1> UHMVL93P25 / ‘… /
S: "9" <R1, BLACK> UHMVL93P26
T: <BLACK, R1> UHMVL93P26 / ‹‘ /
S: "9" <R1, BLACK> UHMVL93P27
T: <BLACK, R1> UHMVL93P27 / “‹“€ - “«μο /
S: "9" <R1, BLACK> UHMVL93P28
T: <BLACK, R1> UHMVL93P28 / €’ /
S: "9" <R1, BLACK> UHMVL93P29
T: <BLACK, R1> UHMVL93P29 / “€‘ - “ΰ ª /

S: "9" <R1, BLACK> UHMVL93P31
T: <BLACK, R1> UHMVL93P31 / ‘€ /
S: "9" <R1, BLACK> UHMVL93P32
T: <BLACK, R1> UHMVL93P32 / ’“‹’ /
S: "9" <R1, BLACK> UHMVL93P33
T: <BLACK, R1> UHMVL93P33 / ‹€ - ­ο /
S: "9" <R1, BLACK> UHMVL93P34
T: <BLACK, R1> UHMVL93P34 / ‘ /
S: "9" <R1, BLACK> UHMVL93P35
T: <BLACK, R1> UHMVL93P35 / €€ /


S: "9" <R1, BLACK> UHMVL94P2
T: <BLACK, R1> UHMVL94P2 / ‹‘ /
S: "9" <R1, BLACK> UHMVL94P3
T: <BLACK, R1> UHMVL94P3 / ’€“ /
S: "9" <R1, BLACK> UHMVL94P4
T: <BLACK, R1> UHMVL94P4 / „€“ /
S: "9" <R1, BLACK> UHMVL94P5
T: <BLACK, R1> UHMVL94P5 / ‘ /
S: "9" <R1, BLACK> UHMVL94P6
T: <BLACK, R1> UHMVL94P6 / ‹“€„ /
S: "9" <R1, BLACK> UHMVL94P7
T: <BLACK, R1> UHMVL94P7 / ‘…“ /
S: "9" <R1, BLACK> UHMVL94P8
T: <BLACK, R1> UHMVL94P8 / …‹ /
S: "9" <R1, BLACK> UHMVL94P9
T: <BLACK, R1> UHMVL94P9 / ‹… /
S: "9" <R1, BLACK> UHMVL94P10
T: <BLACK, R1> UHMVL94P10 / ‘…ƒ /
S: "9" <R1, BLACK> UHMVL94P11
T: <BLACK, R1> UHMVL94P11 / …‹ /

S: "9" <R1, BLACK> UHMVL94P13
T: <BLACK, R1> UHMVL94P13 / € /
S: "9" <R1, BLACK> UHMVL94P14
T: <BLACK, R1> UHMVL94P14 / ‘“…’€ /
S: "9" <R1, BLACK> UHMVL94P15
T: <BLACK, R1> UHMVL94P15 / …“ /
S: "9" <R1, BLACK> UHMVL94P16
T: <BLACK, R1> UHMVL94P16 / € /
S: "9" <R1, BLACK> UHMVL94P17
T: <BLACK, R1> UHMVL94P17 / ƒ…… /
S: "9" <R1, BLACK> UHMVL94P18
T: <BLACK, R1> UHMVL94P18 / ‹€“ /
S: "9" <R1, BLACK> UHMVL94P19
T: <BLACK, R1> UHMVL94P19 / ‘’…… /

S: "9" <R1, BLACK> UHMVL94P21
T: <BLACK, R1> UHMVL94P21 / “€ /


S: "9" <R1, BLACK> UHMVL95P2
T: <BLACK, R1> UHMVL95P2 / €€ /
S: "9" <R1, BLACK> UHMVL95P3
T: <BLACK, R1> UHMVL95P3 / ‹…€ /
S: "9" <R1, BLACK> UHMVL95P4
T: <BLACK, R1> UHMVL95P4 / ‹€‹ /
S: "9" <R1, BLACK> UHMVL95P5
T: <BLACK, R1> UHMVL95P5 / “ƒ€ /
S: "9" <R1, BLACK> UHMVL95P6
T: <BLACK, R1> UHMVL95P6 / „€ /
S: "9" <R1, BLACK> UHMVL95P7
T: <BLACK, R1> UHMVL95P7 / ‹€ /
S: "9" <R1, BLACK> UHMVL95P8
T: <BLACK, R1> UHMVL95P8 / €’… /

S: "9" <R1, BLACK> UHMVL95P10
T: <BLACK, R1> UHMVL95P10 / “…’ /
S: "9" <R1, BLACK> UHMVL95P11
T: <BLACK, R1> UHMVL95P11 / €‹‘ /
S: "9" <R1, BLACK> UHMVL95P12
T: <BLACK, R1> UHMVL95P12 / €“ƒ€ /
S: "9" <R1, BLACK> UHMVL95P13
T: <BLACK, R1> UHMVL95P13 / ’…’“ /
S: "9" <R1, BLACK> UHMVL95P14
T: <BLACK, R1> UHMVL95P14 / ‹… /

S: "9" <R1, BLACK> UHMVL96P2
T: <BLACK, R1> UHMVL96P2 / €“€ /
S: "9" <R1, BLACK> UHMVL96P3
T: <BLACK, R1> UHMVL96P3 / ‘€’ /
S: "9" <R1, BLACK> UHMVL96P4
T: <BLACK, R1> UHMVL96P4 / €€ /
S: "9" <R1, BLACK> UHMVL96P5
T: <BLACK, R1> UHMVL96P5 / €€ /
S: "9" <R1, BLACK> UHMVL96P6
T: <BLACK, R1> UHMVL96P6 / …‘ /
S: "9" <R1, BLACK> UHMVL96P7
T: <BLACK, R1> UHMVL96P7 / “ƒ“ /
S: "9" <R1, BLACK> UHMVL96P8
T: <BLACK, R1> UHMVL96P8 / “ /
S: "9" <R1, BLACK> UHMVL96P9
T: <BLACK, R1> UHMVL96P9 /  /
S: "9" <R1, BLACK> UHMVL96P10
T: <BLACK, R1> UHMVL96P10 / ‘€‹‹ /
S: "9" <R1, BLACK> UHMVL96P11
T: <BLACK, R1> UHMVL96P11 / …‘ /
S: "9" <R1, BLACK> UHMVL96P12
T: <BLACK, R1> UHMVL96P12 / ’’ /
S: "9" <R1, BLACK> UHMVL96P13
T: <BLACK, R1> UHMVL96P13 / “…‘“ /
S: "9" <R1, BLACK> UHMVL96P14
T: <BLACK, R1> UHMVL96P14 / ‹‘ /
S: "9" <R1, BLACK> UHMVL96P15
T: <BLACK, R1> UHMVL96P15 / “ /
S: "9" <R1, BLACK> UHMVL96P16
T: <BLACK, R1> UHMVL96P16 / €„€ /
S: "9" <R1, BLACK> UHMVL96P17
T: <BLACK, R1> UHMVL96P17 / “‹€‘ /
S: "9" <R1, BLACK> UHMVL96P18
T: <BLACK, R1> UHMVL96P18 / …‘’ /
S: "9" <R1, BLACK> UHMVL96P19
T: <BLACK, R1> UHMVL96P19 / ““’ /

S: "9" <R1, BLACK> UHMVL97P1
T: <BLACK, R1> UHMVL97P1 / €“‘ /
S: "9" <R1, BLACK> UHMVL97P2
T: <BLACK, R1> UHMVL97P2 / €’ /
S: "9" <R1, BLACK> UHMVL97P3
T: <BLACK, R1> UHMVL97P3 / ƒ€ /
S: "9" <R1, BLACK> UHMVL97P4
T: <BLACK, R1> UHMVL97P4 / „ /
S: "9" <R1, BLACK> UHMVL97P5
T: <BLACK, R1> UHMVL97P5 / ‘’ /
S: "9" <R1, BLACK> UHMVL97P6
T: <BLACK, R1> UHMVL97P6 / ’€€ /

S: "9" <R1, BLACK> UHMVL97P8
T: <BLACK, R1> UHMVL97P8 / ‘‹ /
S: "9" <R1, BLACK> UHMVL97P9
T: <BLACK, R1> UHMVL97P9 / €‘’ /
S: "9" <R1, BLACK> UHMVL97P10
T: <BLACK, R1> UHMVL97P10 / … /
S: "9" <R1, BLACK> UHMVL97P11
T: <BLACK, R1> UHMVL97P11 / ’€€ /

S: "9" <R1, BLACK> UHMVL97P13
T: <BLACK, R1> UHMVL97P13 / €ƒ /

S: "9" <R1, BLACK> UHMVL97P15
T: <BLACK, R1> UHMVL97P15 / “…… /
S: "9" <R1, BLACK> UHMVL97P16
T: <BLACK, R1> UHMVL97P16 / ‹ /
S: "9" <R1, BLACK> UHMVL97P17
T: <BLACK, R1> UHMVL97P17 / €“’ /
S: "9" <R1, BLACK> UHMVL97P18
T: <BLACK, R1> UHMVL97P18 / …‹… /
S: "9" <R1, BLACK> UHMVL97P19
T: <BLACK, R1> UHMVL97P19 / ‹ /
S: "9" <R1, BLACK> UHMVL97P20
T: <BLACK, R1> UHMVL97P20 / …„ /
S: "9" <R1, BLACK> UHMVL97P21
T: <BLACK, R1> UHMVL97P21 / ’ /
S: "9" <R1, BLACK> UHMVL97P22
T: <BLACK, R1> UHMVL97P22 / €ƒ€ /

S: "9" <R1, BLACK> UHMVL97P24
T: <BLACK, R1> UHMVL97P24 / € /
S: "9" <R1, BLACK> UHMVL97P25
T: <BLACK, R1> UHMVL97P25 / ƒ„ /
S: "9" <R1, BLACK> UHMVL97P26
T: <BLACK, R1> UHMVL97P26 / €‘ /
S: "9" <R1, BLACK> UHMVL97P27
T: <BLACK, R1> UHMVL97P27 / …‹ƒ /
S: "9" <R1, BLACK> UHMVL97P28
T: <BLACK, R1> UHMVL97P28 / €‘€“ /
S: "9" <R1, BLACK> UHMVL97P29
T: <BLACK, R1> UHMVL97P29 / ‘’ /

S: "9" <R1, BLACK> UHMVL97P31
T: <BLACK, R1> UHMVL97P31 / “‹ /
*S: "9" <R1, BLACK> UHMVL97P32*
*T: <BLACK, R1> UHMVL97P32 / €ƒ’ /*
*S: "9" <R1, BLACK> UHMVL97P33*
*T: <BLACK, R1> UHMVL97P33 / ƒ€ /*
*S: "9" <R1, BLACK> UHMVL97P34*
*T: <BLACK, R1> UHMVL97P34 / …‹“ /*
S: "9" <R1, BLACK> UHMVL97P35
T: <BLACK, R1> UHMVL97P35 / ‹€“ /
S: "9" <R1, BLACK> UHMVL97P36
T: <BLACK, R1> UHMVL97P36 / ‘’…… /

S: "9" <R1, BLACK> UHMVL98P1
T: <BLACK, R1> UHMVL98P1 / € /

S: "9" <R1, BLACK> UHMVL98P3
T: <BLACK, R1> UHMVL98P3 / ‘…“ /
S: "9" <R1, BLACK> UHMVL98P4*
T: <BLACK, R1> UHMVL98P4 / …ƒ“ /
S: "9" <R1, BLACK> UHMVL98P5*
T: <BLACK, R1> UHMVL98P5 /  /
S: "9" <R1, BLACK> UHMVL98P6*
T: <BLACK, R1> UHMVL98P6 / “…… /
S: "9" <R1, BLACK> UHMVL98P7*
T: <BLACK, R1> UHMVL98P7 / ƒ‘ /
S: "9" <R1, BLACK> UHMVL98P8*
T: <BLACK, R1> UHMVL98P8 / ‹€€’ /
S: "9" <R1, BLACK> UHMVL98P9*
T: <BLACK, R1> UHMVL98P9 / … /
S: "9" <R1, BLACK> UHMVL98P10*
T: <BLACK, R1> UHMVL98P10 / €‘ /
S: "9" <R1, BLACK> UHMVL98P11*
T: <BLACK, R1> UHMVL98P11 /  /
S: "9" <R1, BLACK> UHMVL98P12*
T: <BLACK, R1> UHMVL98P12 / “…“ /
S: "9" <R1, BLACK> UHMVL98P13
T: <BLACK, R1> UHMVL98P13 / …„ /
S: "9" <R1, BLACK> UHMVL99P1
T: <BLACK, R1> UHMVL99P1 / ‘€€ /
S: "9" <R1, BLACK> UHMVL99P2
T: <BLACK, R1> UHMVL99P2 / “ /
S: "9" <R1, BLACK> UHMVL99P3
T: <BLACK, R1> UHMVL99P3 / €‹ /
S: "9" <R1, BLACK> UHMVL99P4
T: <BLACK, R1> UHMVL99P4 / ‹€“’ /
S: "9" <R1, BLACK> UHMVL99P5
T: <BLACK, R1> UHMVL99P5 / ‹…€ /

S: "9" <R1, BLACK> UHMVL99P7
T: <BLACK, R1> UHMVL99P7 / €ƒ€’ /
S: "9" <R1, BLACK> UHMVL99P8
T: <BLACK, R1> UHMVL99P8 / ‘…‘“ /
S: "9" <R1, BLACK> UHMVL99P9
T: <BLACK, R1> UHMVL99P9 / “’…‹€ /
S: "9" <R1, BLACK> UHMVL100P1
T: <BLACK, R1> UHMVL100P1 / ‘€€ /
S: "9" <R1, BLACK> UHMVL100P2
T: <BLACK, R1> UHMVL100P2 / €„€ /
S: "9" <R1, BLACK> UHMVL100P3
T: <BLACK, R1> UHMVL100P3 / …‹ /

S: "9" <R1, BLACK> UHMVL100P5
T: <BLACK, R1> UHMVL100P5 / ‹ /
S: "9" <R1, BLACK> UHMVL100P6
T: <BLACK, R1> UHMVL100P6 / €ƒ /
S: "9" <R1, BLACK> UHMVL100P7
T: <BLACK, R1> UHMVL100P7 / ‘’’ /
S: "9" <R1, BLACK> UHMVL101P1
T: <BLACK, R1> UHMVL101P1 / ’…“ /
S: "9" <R1, BLACK> UHMVL101P2
T: <BLACK, R1> UHMVL101P2 / € /
S: "9" <R1, BLACK> UHMVL101P3
T: <BLACK, R1> UHMVL101P3 / €€ /
S: "9" <R1, BLACK> UHMVL101P4
T: <BLACK, R1> UHMVL101P4 / €„€ /
S: "9" <R1, BLACK> UHMVL101P5
T: <BLACK, R1> UHMVL101P5 / ‘…ƒ… /
S: "9" <R1, BLACK> UHMVL101P6
T: <BLACK, R1> UHMVL101P6 / €…ƒ€ /
S: "9" <R1, BLACK> UHMVL101P7
T: <BLACK, R1> UHMVL101P7 / …‹ /
S: "9" <R1, BLACK> UHMVL101P8
T: <BLACK, R1> UHMVL101P8 / ƒ…… /
S: "9" <R1, BLACK> UHMVL101P9
T: <BLACK, R1> UHMVL101P9 / ‘’ƒ /

S: "9" <R1, BLACK> UHMVL101P11
T: <BLACK, R1> UHMVL101P11 / …ƒ /
S: "9" <R1, BLACK> UHMVL101P12
T: <BLACK, R1> UHMVL101P12 / „‹ /
S: "9" <R1, BLACK> UHMVL101P13
T: <BLACK, R1> UHMVL101P13 / ’€“ /
S: "9" <R1, BLACK> UHMVL102P1
T: <BLACK, R1> UHMVL102P1 / € /
S: "9" <R1, BLACK> UHMVL102P2
T: <BLACK, R1> UHMVL102P2 / …“ /
S: "9" <R1, BLACK> UHMVL102P3
T: <BLACK, R1> UHMVL102P3 / ƒ‘ /
S: "9" <R1, BLACK> UHMVL102P4
T: <BLACK, R1> UHMVL102P4 / €ƒ /
S: "9" <R1, BLACK> UHMVL102P5
T: <BLACK, R1> UHMVL102P5 / ’…“ /
S: "9" <R1, BLACK> UHMVL102P6
T: <BLACK, R1> UHMVL102P6 / …€ /
S: "9" <R1, BLACK> UHMVL102P7
T: <BLACK, R1> UHMVL102P7 / ’“ /
S: "9" <R1, BLACK> UHMVL102P8
T: <BLACK, R1> UHMVL102P8 / … /

S: "9" <R1, BLACK> UHMVL103P1
T: <BLACK, R1> UHMVL103P1 / ‹“€„ /
S: "9" <R1, BLACK> UHMVL103P2
T: <BLACK, R1> UHMVL103P2 / €ƒ€ /
S: "9" <R1, BLACK> UHMVL103P3
T: <BLACK, R1> UHMVL103P3 / €“ /
S: "9" <R1, BLACK> UHMVL103P4
T: <BLACK, R1> UHMVL103P4 / ƒ€ /
S: "9" <R1, BLACK> UHMVL103P5
T: <BLACK, R1> UHMVL103P5 / ‘ /
S: "9" <R1, BLACK> UHMVL103P6
T: <BLACK, R1> UHMVL103P6 / ƒ /
S: "9" <R1, BLACK> UHMVL103P7
T: <BLACK, R1> UHMVL103P7 / ‘“€ /
S: "9" <R1, BLACK> UHMVL104P1
T: <BLACK, R1> UHMVL104P1 / …“ /
S: "9" <R1, BLACK> UHMVL104P2
T: <BLACK, R1> UHMVL104P2 / €€ƒ /
S: "9" <R1, BLACK> UHMVL104P3
T: <BLACK, R1> UHMVL104P3 / ““ /
S: "9" <R1, BLACK> UHMVL104P4
T: <BLACK, R1> UHMVL104P4 / “‹“ /
S: "9" <R1, BLACK> UHMVL104P5
T: <BLACK, R1> UHMVL104P5 / … /
S: "9" <R1, BLACK> UHMVL104P6
T: <BLACK, R1> UHMVL104P6 / €ƒ€ /
S: "9" <R1, BLACK> UHMVL104P7
T: <BLACK, R1> UHMVL104P7 / “ /
S: "9" <R1, BLACK> UHMVL105P1
T: <BLACK, R1> UHMVL105P1 / ‹“€„ /
S: "9" <R1, BLACK> UHMVL105P2
T: <BLACK, R1> UHMVL105P2 / ‘ /
S: "9" <R1, BLACK> UHMVL105P3
T: <BLACK, R1> UHMVL105P3 / €‘ /
S: "9" <R1, BLACK> UHMVL105P4
T: <BLACK, R1> UHMVL105P4 / ƒ… /
S: "9" <R1, BLACK> UHMVL105P5
T: <BLACK, R1> UHMVL105P5 / „€“ /
S: "9" <R1, BLACK> UHMVL105P6
T: <BLACK, R1> UHMVL105P6 / ‹‘€ /
S: "9" <R1, BLACK> UHMVL105P7
T: <BLACK, R1> UHMVL105P7 / “ /
S: "9" <R1, BLACK> UHMVL105P8
T: <BLACK, R1> UHMVL105P8 / ’€“ /
S: "9" <R1, BLACK> UHMVL105P9
T: <BLACK, R1> UHMVL105P9 / ‘ /
S: "9" <R1, BLACK> UHMVL105P10
T: <BLACK, R1> UHMVL105P10 / “’…‹€ /
S: "9" <R1, BLACK> UHMVL106P1
T: <BLACK, R1> UHMVL106P1 / “’…‹€ /
S: "9" <R1, BLACK> UHMVL106P2
T: <BLACK, R1> UHMVL106P2 / ’€“‹ /
S: "9" <R1, BLACK> UHMVL106P3
T: <BLACK, R1> UHMVL106P3 / ƒ… /
S: "9" <R1, BLACK> UHMVL106P4
T: <BLACK, R1> UHMVL106P4 / ‘ /
S: "9" <R1, BLACK> UHMVL106P5
T: <BLACK, R1> UHMVL106P5 / ‹“€„ /
S: "9" <R1, BLACK> UHMVL107P1
T: <BLACK, R1> UHMVL107P1 / €ƒ€ /
S: "9" <R1, BLACK> UHMVL107P2
T: <BLACK, R1> UHMVL107P2 / ’“’ /
S: "9" <R1, BLACK> UHMVL107P3
T: <BLACK, R1> UHMVL107P3 / ’€ /
S: "9" <R1, BLACK> UHMVL107P4
T: <BLACK, R1> UHMVL107P4 / €‹“ /
S: "9" <R1, BLACK> UHMVL108P1
T: <BLACK, R1> UHMVL108P1 / ‹“€„ /
S: "9" <R1, BLACK> UHMVL108P2
T: <BLACK, R1> UHMVL108P2 /  /
S: "9" <R1, BLACK> UHMVL108P3
T: <BLACK, R1> UHMVL108P3 / ƒ€ /
S: "9" <R1, BLACK> UHMVL108P5
T: <BLACK, R1> UHMVL108P5 / €‹“ /
S: "9" <R1, BLACK> UHMVL108P6
T: <BLACK, R1> UHMVL108P6 / …‘€“ /

S: "9" <R1, BLACK> UHMVL109P1
T: <BLACK, R1> UHMVL109P1 / € /
S: "9" <R1, BLACK> UHMVL109P2
T: <BLACK, R1> UHMVL109P2 / …‹ /
S: "9" <R1, BLACK> UHMVL109P3
T: <BLACK, R1> UHMVL109P3 / … /
S: "9" <R1, BLACK> UHMVL109P4
T: <BLACK, R1> UHMVL109P4 /  /
S: "9" <R1, BLACK> UHMVL110P1
T: <BLACK, R1> UHMVL110P1 / “ /
S: "9" <R1, BLACK> UHMVL110P2
T: <BLACK, R1> UHMVL110P2 / …‹ /
S: "9" <R1, BLACK> UHMVL110P3
T: <BLACK, R1> UHMVL110P3 / €ƒ„€ /
S: "9" <R1, BLACK> UHMVL110P4
T: <BLACK, R1> UHMVL110P4 / ƒ‘€ /
S: "9" <R1, BLACK> UHMVL110P5
T: <BLACK, R1> UHMVL110P5 / € /
S: "9" <R1, BLACK> UHMVL110P6
T: <BLACK, R1> UHMVL110P6 / … /
S: "9" <R1, BLACK> UHMVL111P1
T: <BLACK, R1> UHMVL111P1 / ……‹ /
S: "9" <R1, BLACK> UHMVL111P2
T: <BLACK, R1> UHMVL111P2 / “‹ /
S: "9" <R1, BLACK> UHMVL111P3
T: <BLACK, R1> UHMVL111P3 / €‘€ /
S: "9" <R1, BLACK> UHMVL111P4
T: <BLACK, R1> UHMVL111P4 / ‘’… /
S: "9" <R1, BLACK> UHMVL111P5
T: <BLACK, R1> UHMVL111P5 / ‘… /
S: "9" <R1, BLACK> UHMVL111P6
T: <BLACK, R1> UHMVL111P6 / ‘’ /
S: "9" <R1, BLACK> UHMVL111P7
T: <BLACK, R1> UHMVL111P7 / “•„ /
S: "9" <R1, BLACK> UHMVL111P8
T: <BLACK, R1> UHMVL111P8 / “‹ /
S: "9" <R1, BLACK> UHMVL111P9
T: <BLACK, R1> UHMVL111P9 / ‹ /
S: "9" <R1, BLACK> UHMVL111P10
T: <BLACK, R1> UHMVL111P10 / €ƒ’ /
S: "9" <R1, BLACK> UHMVL112P1
T: <BLACK, R1> UHMVL112P1 / “’… /
S: "9" <R1, BLACK> UHMVL112P2
T: <BLACK, R1> UHMVL112P2 / …‹ /
S: "9" <R1, BLACK> UHMVL113P1
T: <BLACK, R1> UHMVL113P1 / …€ /
S: "9" <R1, BLACK> UHMVL113P2
T: <BLACK, R1> UHMVL113P2 / … /
S: "9" <R1, BLACK> UHMVL113P3
T: <BLACK, R1> UHMVL113P3 / ……€ /
S: "9" <R1, BLACK> UHMVL113P4
T: <BLACK, R1> UHMVL113P4 / ‘…ƒ… /

S: "9" <R1, BLACK> UHMVL114P2
T: <BLACK, R1> UHMVL114P2 / ‹ /
S: "9" <R1, BLACK> UHMVL114P3
T: <BLACK, R1> UHMVL114P3 / …‹€„ /
S: "9" <R1, BLACK> UHMVL114P4
T: <BLACK, R1> UHMVL114P4 / “‘’ /
S: "9" <R1, BLACK> UHMVL114P5
T: <BLACK, R1> UHMVL114P5 / ‘€’ /
S: "9" <R1, BLACK> UHMVL114P6
T: <BLACK, R1> UHMVL114P6 / €“€ /


S: "9" <R1, BLACK> UHMVL115P2
T: <BLACK, R1> UHMVL115P2 / ““’ /
S: "9" <R1, BLACK> UHMVL115P3
T: <BLACK, R1> UHMVL115P3 / „€€ /
S: "9" <R1, BLACK> UHMVL115P4
T: <BLACK, R1> UHMVL115P4 / …‹€„ /
S: "9" <R1, BLACK> UHMVL115P5
T: <BLACK, R1> UHMVL115P5 / ’‹ /
S: "9" <R1, BLACK> UHMVL115P6
T: <BLACK, R1> UHMVL115P6 / €€ /
S: "9" <R1, BLACK> UHMVL116P1
T: <BLACK, R1> UHMVL116P1 / …‹ /
S: "9" <R1, BLACK> UHMVL116P2
T: <BLACK, R1> UHMVL116P2 / “ƒ€€ /
S: "9" <R1, BLACK> UHMVL116P3
T: <BLACK, R1> UHMVL116P3 / …„… /
S: "9" <R1, BLACK> UHMVL116P4
T: <BLACK, R1> UHMVL116P4 / ‘€’€ /
S: "9" <R1, BLACK> UHMVL116P5
T: <BLACK, R1> UHMVL116P5 / €‘ /
S: "9" <R1, BLACK> UHMVL116P6
T: <BLACK, R1> UHMVL116P6 / ’€€ /
S: "9" <R1, BLACK> UHMVL116P7
T: <BLACK, R1> UHMVL116P7 / ’€€ /
S: "9" <R1, BLACK> UHMVL116P8
T: <BLACK, R1> UHMVL116P8 / …’„€ /
S: "9" <R1, BLACK> UHMVL116P9
T: <BLACK, R1> UHMVL116P9 / ’€€‹ /
S: "9" <R1, BLACK> UHMVL116P10
T: <BLACK, R1> UHMVL116P10 / €‹ /
S: "9" <R1, BLACK> UHMVL116P11
T: <BLACK, R1> UHMVL116P11 / …„ /
S: "9" <R1, BLACK> UHMVL117P1
T: <BLACK, R1> UHMVL117P1 / ‘…“ /
S: "9" <R1, BLACK> UHMVL117P2
T: <BLACK, R1> UHMVL117P2 / ‹€ /
S: "9" <R1, BLACK> UHMVL117P3
T: <BLACK, R1> UHMVL117P3 / “’€“„ /
S: "9" <R1, BLACK> UHMVL117P4
T: <BLACK, R1> UHMVL117P4 /  /
S: "9" <R1, BLACK> UHMVL117P5
T: <BLACK, R1> UHMVL117P5 /  /
S: "9" <R1, BLACK> UHMVL117P6
T: <BLACK, R1> UHMVL117P6 / €‘’ /
S: "9" <R1, BLACK> UHMVL117P7
T: <BLACK, R1> UHMVL117P7 / ‘€“€ /
S: "9" <R1, BLACK> UHMVL117P8
T: <BLACK, R1> UHMVL117P8 / ‘’ /
S: "9" <R1, BLACK> UHMVL117P9
T: <BLACK, R1> UHMVL117P9 / € /
S: "9" <R1, BLACK> UHMVL117P10
T: <BLACK, R1> UHMVL117P10 / ‘‚€ /
S: "9" <R1, BLACK> UHMVL117P11
T: <BLACK, R1> UHMVL117P11 / €ƒ‹ /
S: "9" <R1, BLACK> UHMVL117P12
T: <BLACK, R1> UHMVL117P12 / €€ /
S: "9" <R1, BLACK> UHMVL117P13
T: <BLACK, R1> UHMVL117P13 / ‘“ /
S: "9" <R1, BLACK> UHMVL117P14
T: <BLACK, R1> UHMVL117P14 / ‘“ /
S: "9" <R1, BLACK> UHMVL117P15
T: <BLACK, R1> UHMVL117P15 / ƒ /
S: "9" <R1, BLACK> UHMVL117P16
T: <BLACK, R1> UHMVL117P16 /  /
S: "9" <R1, BLACK> UHMVL117P17
T: <BLACK, R1> UHMVL117P17 / ‹ /
S: "9" <R1, BLACK> UHMVL117P18
T: <BLACK, R1> UHMVL117P18 / …ƒ /
S: "9" <R1, BLACK> UHMVL117P19
T: <BLACK, R1> UHMVL117P19 / €‹ /
S: "9" <R1, BLACK> UHMVL117P20
T: <BLACK, R1> UHMVL117P20 / ‘’… /
S: "9" <R1, BLACK> UHMVL117P21
T: <BLACK, R1> UHMVL117P21 / ‹ /
S: "9" <R1, BLACK> UHMVL117P22
T: <BLACK, R1> UHMVL117P22 / ‘’… /
S: "9" <R1, BLACK> UHMVL117P23
T: <BLACK, R1> UHMVL117P23 / €€’ /
S: "9" <R1, BLACK> UHMVL117P24
T: <BLACK, R1> UHMVL117P24 / ‘’“ /
S: "9" <R1, BLACK> UHMVL117P25
T: <BLACK, R1> UHMVL117P25 / ’“ /
S: "9" <R1, BLACK> UHMVL117P26
T: <BLACK, R1> UHMVL117P26 / €‹ /
S: "9" <R1, BLACK> UHMVL117P27
T: <BLACK, R1> UHMVL117P27 / ‘ /
S: "9" <R1, BLACK> UHMVL117P28
T: <BLACK, R1> UHMVL117P28 / ƒ /
S: "9" <R1, BLACK> UHMVL117P29
T: <BLACK, R1> UHMVL117P29 / …’‘ /
S: "9" <R1, BLACK> UHMVL117P30
T: <BLACK, R1> UHMVL117P30 / ‘€‹€ /
S: "9" <R1, BLACK> UHMVL117P31
T: <BLACK, R1> UHMVL117P31 / „€‹ /
S: "9" <R1, BLACK> UHMVL117P32
T: <BLACK, R1> UHMVL117P32 / €‘ /
S: "9" <R1, BLACK> UHMVL117P33
T: <BLACK, R1> UHMVL117P33 / €‘ /
S: "9" <R1, BLACK> UHMVL117P34
T: <BLACK, R1> UHMVL117P34 / € /
S: "9" <R1, BLACK> UHMVL117P35
T: <BLACK, R1> UHMVL117P35 / ‘“ /
S: "9" <R1, BLACK> UHMVL117P36
T: <BLACK, R1> UHMVL117P36 / ƒ„ /
S: "9" <R1, BLACK> UHMVL117P37
T: <BLACK, R1> UHMVL117P37 / €€€ /
S: "9" <R1, BLACK> UHMVL117P38
T: <BLACK, R1> UHMVL117P38 / ’‹€ /
S: "9" <R1, BLACK> UHMVL117P39
T: <BLACK, R1> UHMVL117P39 / €‹’ /
S: "9" <R1, BLACK> UHMVL117P40
T: <BLACK, R1> UHMVL117P40 / …‹€“ /
S: "9" <R1, BLACK> UHMVL117P41
T: <BLACK, R1> UHMVL117P41 / ‘“ /
S: "9" <R1, BLACK> UHMVL117P42
T: <BLACK, R1> UHMVL117P42 / €€ /
S: "9" <R1, BLACK> UHMVL117P43
T: <BLACK, R1> UHMVL117P43 / €‹‘… /
S: "9" <R1, BLACK> UHMVL117P44
T: <BLACK, R1> UHMVL117P44 / ƒ…€ /
S: "9" <R1, BLACK> UHMVL117P45
T: <BLACK, R1> UHMVL117P45 / “€ /
S: "9" <R1, BLACK> UHMVL117P46
T: <BLACK, R1> UHMVL117P46 / …€ /
S: "9" <R1, BLACK> UHMVL117P47
T: <BLACK, R1> UHMVL117P47 / …„… /

S: "9" <R1, BLACK> UHMVL117P49
T: <BLACK, R1> UHMVL117P49 / ’‹“€ /
S: "9" <R1, BLACK> UHMVL117P50
T: <BLACK, R1> UHMVL117P50 / €… /
S: "9" <R1, BLACK> UHMVL117P51
T: <BLACK, R1> UHMVL117P51 / „““’ /

S: "9" <R1, BLACK> UHMVL117P53
T: <BLACK, R1> UHMVL117P53 / €‹„€ /
S: "9" <R1, BLACK> UHMVL117P54
T: <BLACK, R1> UHMVL117P54 / …… /
S: "9" <R1, BLACK> UHMVL117P55
T: <BLACK, R1> UHMVL117P55 / …€€ /
S: "9" <R1, BLACK> UHMVL117P56
T: <BLACK, R1> UHMVL117P56 / €ƒ /
S: "9" <R1, BLACK> UHMVL117P57
T: <BLACK, R1> UHMVL117P57 / €€ /
S: "9" <R1, BLACK> UHMVL117P58
T: <BLACK, R1> UHMVL117P58 / ‹€ /
S: "9" <R1, BLACK> UHMVL117P59
T: <BLACK, R1> UHMVL117P59 / ‘‹“’ /
S: "9" <R1, BLACK> UHMVL117P60
T: <BLACK, R1> UHMVL117P60 / €€ /

S: "9" <R1, BLACK> UHMVL118P2
T: <BLACK, R1> UHMVL118P2 / “‘€ /

S: "9" <R1, BLACK> UHMVL118P4
T: <BLACK, R1> UHMVL118P4 / €‘’ /
S: "9" <R1, BLACK> UHMVL118P5
T: <BLACK, R1> UHMVL118P5 / ’‹€ /
S: "9" <R1, BLACK> UHMVL118P6
T: <BLACK, R1> UHMVL118P6 / €‘‹€ /

S: "9" <R1, BLACK> UHMVL119P2
T: <BLACK, R1> UHMVL119P2 / ’ /

S: "9" <R1, BLACK> UHMVL119P4
T: <BLACK, R1> UHMVL119P4 / ‘’€ /
S: "9" <R1, BLACK> UHMVL119P5
T: <BLACK, R1> UHMVL119P5 / €… /
S: "9" <R1, BLACK> UHMVL119P6
T: <BLACK, R1> UHMVL119P6 / €€ /
S: "9" <R1, BLACK> UHMVL120P1
T: <BLACK, R1> UHMVL120P1 / ‘…“ /
S: "9" <R1, BLACK> UHMVL120P2
T: <BLACK, R1> UHMVL120P2 / ‘€ /
S: "9" <R1, BLACK> UHMVL120P3
T: <BLACK, R1> UHMVL120P3 / ‘’ /

S: "9" <R1, BLACK> UHMVL120P5
T: <BLACK, R1> UHMVL120P5 / ’€ /
S: "9" <R1, BLACK> UHMVL120P6
T: <BLACK, R1> UHMVL120P6 / €‹… /
S: "9" <R1, BLACK> UHMVL120P7
T: <BLACK, R1> UHMVL120P7 / “ /
S: "9" <R1, BLACK> UHMVL120P8
T: <BLACK, R1> UHMVL120P8 / …’€ /
S: "9" <R1, BLACK> UHMVL120P9
T: <BLACK, R1> UHMVL120P9 /  /

S: "9" <R1, BLACK> UHMVL120P11
T: <BLACK, R1> UHMVL120P11 / “ /
S: "9" <R1, BLACK> UHMVL120P12
T: <BLACK, R1> UHMVL120P12 / “ƒ /
S: "9" <R1, BLACK> UHMVL120P13
T: <BLACK, R1> UHMVL120P13 / ‘€’€ /
S: "9" <R1, BLACK> UHMVL120P14
T: <BLACK, R1> UHMVL120P14 / “ /
S: "9" <R1, BLACK> UHMVL120P15
T: <BLACK, R1> UHMVL120P15 /  /
S: "9" <R1, BLACK> UHMVL120P16
T: <BLACK, R1> UHMVL120P16 / ’ /
*S: "9" <R1, BLACK> UHMVL120P17*			***Schetinkin28.12.16***
*T: <BLACK, R1> UHMVL120P17 / ƒ€ /*
S: "9" <R1, BLACK> UHMVL120P18
T: <BLACK, R1> UHMVL120P18 / “’‹ /
S: "9" <R1, BLACK> UHMVL120P19
T: <BLACK, R1> UHMVL120P19 / ‹“€ /
*S: "9" <R1, BLACK> UHMVL120P20*			***Schetinkin28.12.16***
*T: <BLACK, R1> UHMVL120P20 / “‹€ /*
S: "9" <R1, BLACK> UHMVL120P21
T: <BLACK, R1> UHMVL120P21 / “’‹ /
*S: "9" <R1, BLACK> UHMVL120P22*
*T: <BLACK, R1> UHMVL120P22 / ‹€ /*			***Schetinkin28.12.16***
S: "9" <R1, BLACK> UHMVL120P23
T: <BLACK, R1> UHMVL120P23 / “‹ /
S: "9" <R1, BLACK> UHMVL120P24
T: <BLACK, R1> UHMVL120P24 / €’ /

S: "9" <R1, BLACK> UHMVL120P26
T: <BLACK, R1> UHMVL120P26 / ‘ /
S: "9" <R1, BLACK> UHMVL120P27
T: <BLACK, R1> UHMVL120P27 / “ /
S: "9" <R1, BLACK> UHMVL120P28
T: <BLACK, R1> UHMVL120P28 / ƒ„ /
S: "9" <R1, BLACK> UHMVL120P29
T: <BLACK, R1> UHMVL120P29 / €’€ /
S: "9" <R1, BLACK> UHMVL120P30
T: <BLACK, R1> UHMVL120P30 /  /
S: "9" <R1, BLACK> UHMVL121P1
T: <BLACK, R1> UHMVL121P1 / ‘€“€ /

S: "9" <R1, BLACK> UHMVL121P3
T: <BLACK, R1> UHMVL121P3 / …’ /
S: "9" <R1, BLACK> UHMVL121P4
T: <BLACK, R1> UHMVL121P4 / …’ /
S: "9" <R1, BLACK> UHMVL121P5
T: <BLACK, R1> UHMVL121P5 / € /
S: "9" <R1, BLACK> UHMVL121P6
T: <BLACK, R1> UHMVL121P6 / ‹…ƒ /
S: "9" <R1, BLACK> UHMVL121P7
T: <BLACK, R1> UHMVL121P7 / „ƒ /
S: "9" <R1, BLACK> UHMVL121P8
T: <BLACK, R1> UHMVL121P8 / „“‹ /
S: "9" <R1, BLACK> UHMVL121P9
T: <BLACK, R1> UHMVL121P9 / ’ /
S: "9" <R1, BLACK> UHMVL121P10
T: <BLACK, R1> UHMVL121P10 / „““ /
S: "9" <R1, BLACK> UHMVL121P11
T: <BLACK, R1> UHMVL121P11 / „““ /
S: "9" <R1, BLACK> UHMVL121P12
T: <BLACK, R1> UHMVL121P12 / ‹“‘ /
*S: "9" <R1, BLACK> UHMVL121P13*
*T: <BLACK, R1> UHMVL121P13 / €€ /*
*S: "9" <R1, BLACK> UHMVL121P14*
*T: <BLACK, R1> UHMVL121P14 / €€ /*

S: "9" <R1, BLACK> UHMVL121P16
T: <BLACK, R1> UHMVL121P16 / ‹€’€ /
S: "9" <R1, BLACK> UHMVL121P17
T: <BLACK, R1> UHMVL121P17 / €’‹€ /
S: "9" <R1, BLACK> UHMVL121P18
T: <BLACK, R1> UHMVL121P18 / €‘ /
S: "9" <R1, BLACK> UHMVL121P19
T: <BLACK, R1> UHMVL121P19 / €ƒ€ /
S: "9" <R1, BLACK> UHMVL121P20
T: <BLACK, R1> UHMVL121P20 /  /

S: "9" <R1, BLACK> UHMVL122P1
T: <BLACK, R1> UHMVL122P1 / ’ /
*S: "9" <R1, BLACK> UHMVL122P2*
*T: <BLACK, R1> UHMVL122P2 / … /*
*S: "9" <R1, BLACK> UHMVL122P3*
*T: <BLACK, R1> UHMVL122P3 / ‘’“ /*
S: "9" <R1, BLACK> UHMVL122P4
T: <BLACK, R1> UHMVL122P4 / …’€ /
S: "9" <R1, BLACK> UHMVL123P1
T: <BLACK, R1> UHMVL123P1 / €ƒ€ /
S: "9" <R1, BLACK> UHMVL123P2
T: <BLACK, R1> UHMVL123P2 / ƒ /
S: "9" <R1, BLACK> UHMVL123P3
T: <BLACK, R1> UHMVL123P3 / “ƒ€€ /
S: "9" <R1, BLACK> UHMVL123P4
T: <BLACK, R1> UHMVL123P4 / € /
S: "9" <R1, BLACK> UHMVL123P5
T: <BLACK, R1> UHMVL123P5 / “ /
S: "9" <R1, BLACK> UHMVL123P6
T: <BLACK, R1> UHMVL123P6 / ’ƒ /
S: "9" <R1, BLACK> UHMVL124P1
T: <BLACK, R1> UHMVL124P1 / “’‹ /
S: "9" <R1, BLACK> UHMVL124P2
T: <BLACK, R1> UHMVL124P2 / ’ƒ /
S: "9" <R1, BLACK> UHMVL124P3
T: <BLACK, R1> UHMVL124P3 / ‘…“ /
S: "9" <R1, BLACK> UHMVL124P4
T: <BLACK, R1> UHMVL124P4 / ‹’“ /
S: "9" <R1, BLACK> UHMVL124P5
T: <BLACK, R1> UHMVL124P5 / “’‹ /
S: "9" <R1, BLACK> UHMVL125P1
T: <BLACK, R1> UHMVL125P1 / €‘ /
S: "9" <R1, BLACK> UHMVL125P2
T: <BLACK, R1> UHMVL125P2 / ‘ /
S: "9" <R1, BLACK> UHMVL125P3
T: <BLACK, R1> UHMVL125P3 / € /
S: "9" <R1, BLACK> UHMVL125P4
T: <BLACK, R1> UHMVL125P4 / •‹ /
S: "9" <R1, BLACK> UHMVL125P5
T: <BLACK, R1> UHMVL125P5 / €€ /
S: "9" <R1, BLACK> UHMVL125P6
T: <BLACK, R1> UHMVL125P6 / “€‘ /
S: "9" <R1, BLACK> UHMVL125P7
T: <BLACK, R1> UHMVL125P7 / €€’ /


S: "9" <R1, BLACK> UHMVL126P2
T: <BLACK, R1> UHMVL126P2 / €„‹ - ‚®«ª®Ά® /
S: "9" <R1, BLACK> UHMVL126P3
T: <BLACK, R1> UHMVL126P3 / €’ - ’ ¬΅®Άª  /

*S: "9" <R1, BLACK> UHMVL126P5*
*T: <BLACK, R1> UHMVL126P5 / ’ƒ… - ®Ά®΅γΰ¥©αª¨© /*			***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL126P6*
*T: <BLACK, R1> UHMVL126P6 / ’ « ª ­ /*							***Schetinkin31.01.17***

S: "9" <R1, BLACK> UHMVL127P2
T: <BLACK, R1> UHMVL127P2 / € - ®Ά­®¥ /

S: "9" <R1, BLACK> UHMVL128P2
T: <BLACK, R1> UHMVL128P2 / ‚‡ - ‘ΰ¥¤­¥΅¥«®¥ /
*S: "9" <R1, BLACK> UHMVL129P1*
*T: <BLACK, R1> UHMVL129P1 / ‚‡ - ‘ΰ¥¤­¥΅¥«®¥ /*
*S: "9" <R1, BLACK> UHMVL129P2*
*T: <BLACK, R1> UHMVL129P2 / …ƒ‘ - ¥«®£®ΰαª /*

*SD: -3.0, -2.0*
*S: "9" <R1, BLACK> UHMVL130P1*
*T: <BLACK, R1> UHMVL130P1 / “•’ - ª¨¬η ­ /*
S: "9" <R1, BLACK> UHMVL130P2
T: <BLACK, R1> UHMVL130P2 / “ƒ“ /
S: "9" <R1, BLACK> UHMVL130P3
T: <BLACK, R1> UHMVL130P3 / ‘’€ - ‘β®©΅  /
S: "9" <R1, BLACK> UHMVL130P4
T: <BLACK, R1> UHMVL130P4 / ‘€‹ - ‘¥«¥¬¤¦¨­αª /

S: "9" <R1, BLACK> UHMVL131P1
T: <BLACK, R1> UHMVL131P1 / “ƒ“ /
S: "9" <R1, BLACK> UHMVL131P2
T: <BLACK, R1> UHMVL131P2 / ƒ„ /
*S: "9" <R1, BLACK> UHMVL131P6*
*T: <BLACK, R1> UHMVL131P6 / “•‰ /*							***Schetinkin31.01.17***
SD: -2.0, 1.0
S: "9" <R1, BLACK> UHMVL132P1
T: <BLACK, R1> UHMVL132P1 / …ƒ - …ΰ®δ¥©  Ά«®Ά¨η /
S: "9" <R1, BLACK> UHMVL132P2
SD: -3.0, -2.0
T: <BLACK, R1> UHMVL132P2 / … /
SD: 0.0, 0.0



*T: <BLACK, R1> UHMVL149P1 / …ƒ„€ /*


*SD:-3.0,-2.0*
*T: <BLACK, R1> UHMVL149P1 / …ƒ„€ - ’ εβ ¬λ£¤  /*
*SD:0.0,0.0*



S: "9" <R1, BLACK> UHMVL132P3
T: <BLACK, R1> UHMVL132P3 / …ƒ„€ /

S: "9" <R1, BLACK> UHMVL132P5
T: <BLACK, R1> UHMVL132P5 / €‹€ /
S: "9" <R1, BLACK> UHMVL132P6
T: <BLACK, R1> UHMVL132P6 / €ƒ - ®Ά®£¥®ΰ£¨¥Άª  /

S: "9" <R1, BLACK> UHMVL132P8
T: <BLACK, R1> UHMVL132P8 / ‚‡ - ‘ΰ¥¤­¥΅¥«®¥ /


S: "9" <R1, BLACK> UHMVL132P11
T: <BLACK, R1> UHMVL132P11 / ‹“ - ΅«γημ¥ /
S: "9" <R1, BLACK> UHMVL132P12
T: <BLACK, R1> UHMVL132P12 / €‘ - ¨ΰ  /
S: "9" <R1, BLACK> UHMVL132P13
T: <BLACK, R1> UHMVL132P13 / ‹‘ /
S: "9" <R1, BLACK> UHMVL132P14
T: <BLACK, R1> UHMVL132P14 / “ - “ΰ¬¨­-ΰ¥ª  /
S: "9" <R1, BLACK> UHMVL132P15
T: <BLACK, R1> UHMVL132P15 / „€‹ - „ ­¨«®Άª  /
*S: "9" <R1, BLACK> UHMVL132P16*
*T: <BLACK, R1> UHMVL132P16 / ’‹€ - ¬.’¥«μ¬ ­  /*		***Schetinkin23.05.17***
*S: "9" <R1, BLACK> UHMVL132P17*
*T: <BLACK, R1> UHMVL132P17 / “••’ - • ΅ ΰ®Άαª-‚‹ /*
*S: "9" <R1, BLACK> UHMVL132P18*
*T: <BLACK, R1> UHMVL132P18 / ‘“… - ”¥¤®ΰ®Άª  /*			***Schetinkin23.05.17***
*S: "9" <R1, BLACK> UHMVL132P19*
*T: <BLACK, R1> UHMVL132P19 / € /*						***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL132P20*
*T: <BLACK, R1> UHMVL132P20 / …‘ - ®Ά®γααγΰ¨ /*			***Schetinkin23.05.17***

*S: "9" <R1, BLACK> UHMVL132P22*
*T: <BLACK, R1> UHMVL132P22 / „ /*						***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL132P23*
*T: <BLACK, R1> UHMVL132P23 / …’ /*						***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL132P24*
*T: <BLACK, R1> UHMVL132P24 / €„€ /*						***Schetinkin31.01.17***

S: "9" <R1, BLACK> UHMVL132P26
T: <BLACK, R1> UHMVL132P26 / “• - …€ /

S: "9" <R1, BLACK> UHMVL132P28
T: <BLACK, R1> UHMVL132P28 / ‹€„€ - ‹ § ΰ¥Ά /
S: "9" <R1, BLACK> UHMVL132P29
T: <BLACK, R1> UHMVL132P29 / “‹ - ®£¨΅¨ /
S: "9" <R1, BLACK> UHMVL132P30
T: <BLACK, R1> UHMVL132P30 / „€ - ε¤ ¬-¬λα /
S: "9" <R1, BLACK> UHMVL132P31
T: <BLACK, R1> UHMVL132P31 / ‹ - ®«μθ¥ΰ¥η¥­αª /

*S: "9" <R1, BLACK> UHMVL133P2*
*T: <BLACK, R1> UHMVL133P2 / ’€’ /*						***Schetinkin31.01.17***

*S: "9" <R1, BLACK> UHMVL133P7*
*T: <BLACK, R1> UHMVL133P7 / ƒ /*						***Schetinkin31.01.17***

*S: "9" <R1, BLACK> UHMVL134P2*
*T: <BLACK, R1> UHMVL134P2 / ‘ /*
*S: "9" <R1, BLACK> UHMVL134P3*
*T: <BLACK, R1> UHMVL134P3 / ¥«¥­μª ο /*

S: "9" <R1, BLACK> UHMVL134P4
T: <BLACK, R1> UHMVL134P4 / „…‹ /
S: "9" <R1, BLACK> UHMVL134P5
T: <BLACK, R1> UHMVL134P5 / „’ /
S: "9" <R1, BLACK> UHMVL134P6
T: <BLACK, R1> UHMVL134P6 / „’ /

S: "9" <R1, BLACK> UHMVL134P8
T: <BLACK, R1> UHMVL134P8 / €„ /
S: "9" <R1, BLACK> UHMVL134P9
T: <BLACK, R1> UHMVL134P9 / ‹ /
S: "9" <R1, BLACK> UHMVL134P10
T: <BLACK, R1> UHMVL134P10 / „€ /
S: "9" <R1, BLACK> UHMVL134P11
T: <BLACK, R1> UHMVL134P11 / “• - ¨¬ ­®Άαª /
S: "9" <R1, BLACK> UHMVL134P12
T: <BLACK, R1> UHMVL134P12 / ƒ“‹ /
S: "9" <R1, BLACK> UHMVL134P13
T: <BLACK, R1> UHMVL134P13 / €’€ /

*SD:-6.0,0.0*
*S: "9" <R1, BLACK> UHMVL135P1*
*T: <BLACK, R1> UHMVL135P1 / “•‚ /*			***Schetinkib25.05.17***			
SD:0.0,0.0

S: "9" <R1, BLACK> UHMVL135P2
T: <BLACK, R1> UHMVL135P2 / ‹€ /
S: "9" <R1, BLACK> UHMVL135P3
T: <BLACK, R1> UHMVL135P3 / “‹ /

S: "9" <R1, BLACK> UHMVL135P5
T: <BLACK, R1> UHMVL135P5 / …‘ /

S: "9" <R1, BLACK> UHMVL135P7
T: <BLACK, R1> UHMVL135P7 / ƒ“‹ /
S: "9" <R1, BLACK> UHMVL135P8
T: <BLACK, R1> UHMVL135P8 / “’€ - ®ªΰ ο ¤μ /


S: "9" <R1, BLACK> UHMVL136P2
T: <BLACK, R1> UHMVL136P2 / ƒ - £®ΰ®­-®§¥ΰ® /
S: "9" <R1, BLACK> UHMVL136P3
T: <BLACK, R1> UHMVL136P3 /  - ¨­­¨-γ,ΰ, /

S: "9" <R1, BLACK> UHMVL136P5
T: <BLACK, R1> UHMVL136P5 / €‘’ - γεβ¥ΰ¨­‹γ£ /
S: "9" <R1, BLACK> UHMVL136P6
T: <BLACK, R1> UHMVL136P6 / “• - ¨¬ ­®Άαª /
S: "9" <R1, BLACK> UHMVL137P1
T: <BLACK, R1> UHMVL137P1 / ƒ - £®ΰ®­-®§¥ΰ® /
*S: "9" <R1, BLACK> UHMVL137P2*
*T: <BLACK, R1> UHMVL137P2 / €€ /*						***Schetinkin31.01.17***
S: "9" <R1, BLACK> UHMVL137P3
T: <BLACK, R1> UHMVL137P3 / ΰ¥ε®Ά ο-βΰ /
*S: "9" <R1, BLACK> UHMVL138P1*
*T: <BLACK, R1> UHMVL138P1 / „’‹“ - ®ΰN„-‡¥ο /*			***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL138P2*
*T: <BLACK, R1> UHMVL138P2 / ‘€ - λη®Ά® /*				***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL138P3*
*T: <BLACK, R1> UHMVL138P3 /  - ¨­­¨-γ,ΰ, /*			***Schetinkin31.01.17***

S: "9" <R1, BLACK> UHMVL139P2
T: <BLACK, R1> UHMVL139P2 / „’‹“ - ®ΰN„-‡¥ο /

S: "9" <R1, BLACK> UHMVL139P4
T: <BLACK, R1> UHMVL139P4 / ΰ¥ε®Ά ο-βΰ /


S: "9" <R1, BLACK> UHMVL140P2
T: <BLACK, R1> UHMVL140P2 / „ - ®ΰN€-‡¥ο /
S: "9" <R1, BLACK> UHMVL140P3
T: <BLACK, R1> UHMVL140P3 / … - ¥ΰ¥£®Ά®© /
S: "9" <R1, BLACK> UHMVL140P4
T: <BLACK, R1> UHMVL140P4 / ’€ - β¬¥βª 401 /
S: "9" <R1, BLACK> UHMVL140P5
T: <BLACK, R1> UHMVL140P5 / ‘“ - •Ά®©­λ© /

S: "9" <R1, BLACK> UHMVL140P8
T: <BLACK, R1> UHMVL140P8 / ‘…ƒ - ‘­¥¦­®£®ΰαª¨© /
S: "9" <R1, BLACK> UHMVL140P9
T: <BLACK, R1> UHMVL140P9 / ƒ‹€‘ - ƒ¨«ξ©-γ.ΰ. /
*S: "9" <R1, BLACK> UHMVL141P1*
*T: <BLACK, R1> UHMVL141P1 / „“ - „¨―ªγ­ /*				***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL141P2*
*T: <BLACK, R1> UHMVL141P2 / € /*						***Schetinkin31.01.17***
S: "9" <R1, BLACK> UHMVL141P3
T: <BLACK, R1> UHMVL141P3 / ’€ - β¬¥βª 401 /

*S: "9" <R1, BLACK> UHMVL142P2*
*T: <BLACK, R1> UHMVL142P2 / €€ - ,— ― -γ,ΰ, /*			***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL142P3*
*T: <BLACK, R1> UHMVL142P3 / ƒ€ - ƒ®ΰγ­η -γ,ΰ /*			***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL142P4*
*T: <BLACK, R1> UHMVL142P4 / „…ƒ… - „¥α¨ƒ¥ΰβ ­¤  /*		***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL142P5*
*T: <BLACK, R1> UHMVL142P5 / ’ - ’®ª®-¬¥β¥® /*			***Schetinkin31.01.17***

*S: "9" <R1, BLACK> UHMVL143P2*
*T: <BLACK, R1> UHMVL143P2 / €ΰ ―¥ /*						***Schetinkin31.01.17***

S: "9" <R1, BLACK> UHMVL143P4
T: <BLACK, R1> UHMVL143P4 / ƒ‹€‘ - ƒ¨«ξ©-γ.ΰ. /
S: "9" <R1, BLACK> UHMVL143P5
T: <BLACK, R1> UHMVL143P5 / … - ¥ΰ¥£®Ά®© /

*S: "9" <R1, BLACK> UHMVL144P2*
*T: <BLACK, R1> UHMVL144P2 / ’‘ /*						***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL144P3*
*T: <BLACK, R1> UHMVL144P3 / „“ - „¨―ªγ­ /*				***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL144P4*
*T: <BLACK, R1> UHMVL144P4 / ‹‘ -  ΰ «γα /*				***Schetinkin31.01.17***

*S: "9" <R1, BLACK> UHMVL145P1*
*T: <BLACK, R1> UHMVL145P1 / ’‘ /*						***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL145P2*
*T: <BLACK, R1> UHMVL145P2 / € /*						***Schetinkin31.01.17***
*S: "9" <R1, BLACK> UHMVL145P3*
*T: <BLACK, R1> UHMVL145P3 / €’€ /*						***Schetinkin31.01.17***
S: "9" <R1, BLACK> UHMVL145P4
T: <BLACK, R1> UHMVL145P4 / ’€ - β¬¥βª 401 /
*S: "9" <R1, BLACK> UHMVL146P1*
*T: <BLACK, R1> UHMVL146P1 / …ƒ‘ - ¥«®£®ΰαª /*			***Schetinkin31.01.17***



S: "9" <R1, BLACK> UHMVL149P1
T: <BLACK, R1> UHMVL149P1 / …ƒ„€ /


*SD:-3.0,-2.0*
*T: <BLACK, R1> UHMVL149P1 / …ƒ„€ - ’ εβ ¬λ£¤  /*
*SD:0.0,0.0*


S: "9" <R1, BLACK> UHMVL149P2
T: <BLACK, R1> UHMVL149P2 / “‹ /
S: "9" <R1, BLACK> UHMVL149P3
T: <BLACK, R1> UHMVL149P3 / “€ /

*S: "9" <R1, BLACK> UHMVL150P2*
*T: <BLACK, R1> UHMVL150P2 / ’ƒ… - ®Ά®΅γΰ¥©αª¨© /*		***Schetinkin31.01.17***

S: "9" <R1, BLACK> UHMVL151P2
T: <BLACK, R1> UHMVL151P2 / €„“ƒ /

S: "9" <R1, BLACK> UHMVL151P4
T: <BLACK, R1> UHMVL151P4 / €‘ - ‘λΰ ­μ-γαβμ¥ΰ¥ª¨ /
S: "9" <R1, BLACK> UHMVL151P5
T: <BLACK, R1> UHMVL151P5 / ‹ - ΰ«¨ª-®§, /

S: "9" <R1, BLACK> UHMVL151P7
T: <BLACK, R1> UHMVL151P7 / ‘€€ -  « οαª -ΰ¥ª  /
S: "9" <R1, BLACK> UHMVL151P8
T: <BLACK, R1> UHMVL151P8 / „€‘ - ‚« αμ¥Ά® /
S: "9" <R1, BLACK> UHMVL151P9
T: <BLACK, R1> UHMVL151P9 / “€ - γ¨ΰ /

S: "9" <R1, BLACK> UHMVL151P11
T: <BLACK, R1> UHMVL151P11 / €‹ -  οη­λ©-¬λα /

S: "9" <R1, BLACK> UHMVL151P13
T: <BLACK, R1> UHMVL151P13 / …’ - ¥δβ¥£®ΰαª /
S: "9" <R1, BLACK> UHMVL151P14
T: <BLACK, R1> UHMVL151P14 / “’€ - γβ ªγ /
S: "9" <R1, BLACK> UHMVL151P15
T: <BLACK, R1> UHMVL151P15 / …€ /
S: "9" <R1, BLACK> UHMVL151P16
T: <BLACK, R1> UHMVL151P16 / ‹“ - ¨¦­¨©‚ « /
S: "9" <R1, BLACK> UHMVL151P17
T: <BLACK, R1> UHMVL151P17 / …‹ - Ά ©-®§¥ΰ® /

*S: "9" <R1, BLACK> UHMVL151P19*
*T: <BLACK, R1> UHMVL151P19 / €ƒ€ -  ©£ ­ /*					***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL151P20*
*T: <BLACK, R1> UHMVL151P20 / €‹ -  ΅¨«μ-28 /*				***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL151P21*
*T: <BLACK, R1> UHMVL151P21 / € - ‚ βγ­£-®§¥ΰ® /*			***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL151P22*
*T: <BLACK, R1> UHMVL151P22 /  - ®¬ΰΆ® /*					***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL151P23*
*T: <BLACK, R1> UHMVL151P23 / €’€ -  β¬ ­®Ά -¬λα /*			***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL151P24*
*T: <BLACK, R1> UHMVL151P24 / ƒ€ - ®£ΰ ­¨η­®¥ /*			***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL151P25*
*T: <BLACK, R1> UHMVL151P25 / €‘ - ¨§ª¨©-¬λα /*				***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL151P26*
*T: <BLACK, R1> UHMVL151P26 / ‹‹ - ¥««¨­α£ γ§¥­-¬λα /*		***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL151P27*
*T: <BLACK, R1> UHMVL151P27 / ƒ„ - ƒΆ®§¤¥Ά -¬λα /*			***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL151P28*
*T: <BLACK, R1> UHMVL151P28 / „ - ®Ά®ΰ®β­λ©-¬λα /*			***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL151P29*
*T: <BLACK, R1> UHMVL151P29 / ’…€ - ’¥ΰ―¥­¨ο-¬λα /*			***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL151P30*
*T: <BLACK, R1> UHMVL151P30 / ‹€„ - ‚« ¤¨¬¨ΰ®Ά® /*			***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL151P31*
*T: <BLACK, R1> UHMVL151P31 /  - ΰ®¬λα«®Ά ο /*			***Schetinkin30.01.17***
S: "9" <R1, BLACK> UHMVL151P32
T: <BLACK, R1> UHMVL151P32 / ƒ€ - ®ΰ®­ ©αª /
S: "9" <R1, BLACK> UHMVL151P33
T: <BLACK, R1> UHMVL151P33 / ‹… - ‹¥®­¨¤®Ά® /
S: "9" <R1, BLACK> UHMVL151P34
T: <BLACK, R1> UHMVL151P34 / ƒ€ /

*S: "9" <R1, BLACK> UHMVL151P36*
*T: <BLACK, R1> UHMVL151P36 / ‹“ /*							***Schetinkin30.01.17***

S: "9" <R1, BLACK> UHMVL151P38
T: <BLACK, R1> UHMVL151P38 / €€ - €΅ΰ ¬®Άª  /
S: "9" <R1, BLACK> UHMVL152P2
T: <BLACK, R1> UHMVL152P2 / “€ - γ¨ΰ /
S: "9" <R1, BLACK> UHMVL152P3
T: <BLACK, R1> UHMVL152P3 / …‹ - ΰ¥¬¨δ-®αβΰ®Ά /

S: "9" <R1, BLACK> UHMVL153P2
T: <BLACK, R1> UHMVL153P2 / …‘€ - ®«μθ οαª -ΰ¥ª  /
S: "9" <R1, BLACK> UHMVL153P3
T: <BLACK, R1> UHMVL153P3 / €’ - ­®£®Ά¥ΰθ¨­­λ© /
S: "9" <R1, BLACK> UHMVL153P4
T: <BLACK, R1> UHMVL153P4 / “…€ - “«-ΰ¥ª  /
S: "9" <R1, BLACK> UHMVL153P5
T: <BLACK, R1> UHMVL153P5 / …‹ƒ€ - «μ£®-γαβμ¥ΰ¥ª¨ /
S: "9" <R1, BLACK> UHMVL153P6
T: <BLACK, R1> UHMVL153P6 / €ƒ€ - …¬ -ΰ¥ª  /

S: "9" <R1, BLACK> UHMVL154P1
T: <BLACK, R1> UHMVL154P1 / ‹ - ®«μθ¥ΰ¥η¥­αª /
S: "9" <R1, BLACK> UHMVL154P2
T: <BLACK, R1> UHMVL154P2 / €‹ - ®Άλ¥‹ ­£ΰλ /

S: "9" <R1, BLACK> UHMVL154P4
T: <BLACK, R1> UHMVL154P4 / €ƒ - ¥ΰ¥£®Άλ¥‹ ­£ΰλ /

S: "9" <R1, BLACK> UHMVL155P2
T: <BLACK, R1> UHMVL155P2 / “‹€ - ΰ Άλ©®΅§ ª-ΰ¥ª  /
S: "9" <R1, BLACK> UHMVL155P3
T: <BLACK, R1> UHMVL155P3 / €‹ - ®Άλ¥‹ ­£ΰλ /
S: "9" <R1, BLACK> UHMVL155P4
T: <BLACK, R1> UHMVL155P4 / €ƒ - ¥ΰ¥£®Άλ¥‹ ­£ΰλ /
S: "9" <R1, BLACK> UHMVL155P5
T: <BLACK, R1> UHMVL155P5 / „€ - ε¤ ¬-¬λα /

*S: "9" <R1, BLACK> UHMVL156P3*
*T: <BLACK, R1> UHMVL156P3 / ‘ - ®αª «μΆ® /*			***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL156P4*
*T: <BLACK, R1> UHMVL156P4 / …€ - λ΅­®¥ /*				***Schetinkin30.01.17***
S: "9" <R1, BLACK> UHMVL156P5
T: <BLACK, R1> UHMVL156P5 / „€ - λ΅­®Άαª /
*S: "9" <R1, BLACK> UHMVL157P1*
*T: <BLACK, R1> UHMVL157P1 / ‘…€ /*						***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL157P3*
*T: <BLACK, R1> UHMVL157P3 / …’€„ - ε ΅¨-§ «¨Ά /*			***Schetinkin30.01.17***
S: "9" <R1, BLACK> UHMVL158P1
T: <BLACK, R1> UHMVL158P1 / “‹ - ®£¨΅¨ /
S: "9" <R1, BLACK> UHMVL158P2
T: <BLACK, R1> UHMVL158P2 / ‹ /
S: "9" <R1, BLACK> UHMVL158P3
T: <BLACK, R1> UHMVL158P3 / ƒ€‹€ /
S: "9" <R1, BLACK> UHMVL158P4
T: <BLACK, R1> UHMVL158P4 / €’“ - ‚¨ εβγ /
S: "9" <R1, BLACK> UHMVL158P5
T: <BLACK, R1> UHMVL158P5 / ‹… - •®ν /
S: "9" <R1, BLACK> UHMVL158P6
T: <BLACK, R1> UHMVL158P6 /  - †®­ª¨¥ΰ-¬λα /
S: "9" <R1, BLACK> UHMVL158P7
T: <BLACK, R1> UHMVL158P7 / “ƒ€ - “αβμ-€£­¥Ά® /
S: "9" <R1, BLACK> UHMVL158P8
T: <BLACK, R1> UHMVL158P8 /  - ®θ­οª®Ά® /

S: "9" <R1, BLACK> UHMVL158P10
T: <BLACK, R1> UHMVL158P10 / ‹€€ - ‹ ¬ ­®­-¬λα /
S: "9" <R1, BLACK> UHMVL158P11
T: <BLACK, R1> UHMVL158P11 / ‹€‘ - «μ¨­αª¨© /
S: "9" <R1, BLACK> UHMVL158P12
T: <BLACK, R1> UHMVL158P12 / ‹ - ΅«®­¥Άλ©-¬λα /
S: "9" <R1, BLACK> UHMVL158P13
T: <BLACK, R1> UHMVL158P13 / ‘‹… - ‘«¥―¨ª®Άαª®£®-¬λα /
S: "9" <R1, BLACK> UHMVL158P14
T: <BLACK, R1> UHMVL158P14 / ‘‹ - •®«¬αª /
S: "9" <R1, BLACK> UHMVL158P15
T: <BLACK, R1> UHMVL158P15 / …‹€‘ - ¥Ά¥«μαª /
*S: "9" <R1, BLACK> UHMVL158P16*
*T: <BLACK, R1> UHMVL158P16 / ƒ - ƒ®ΰ­®§ Ά®¤αª /*			***Schetinkin27.01.17***
*S: "9" <R1, BLACK> UHMVL158P17*
*T: <BLACK, R1> UHMVL158P17 / …’€ - γ§­¥ζ®Ά -¬λα /*			***Schetinkin27.01.17***
*S: "9" <R1, BLACK> UHMVL158P18*
*T: <BLACK, R1> UHMVL158P18 / ‹ - ΰ¨«μ®­-¬λα /*			***Schetinkin27.01.17***
S: "9" <R1, BLACK> UHMVL159P1
T: <BLACK, R1> UHMVL159P1 / ‹ - ®«μθ¥ΰ¥η¥­αª /
S: "9" <R1, BLACK> UHMVL159P2
T: <BLACK, R1> UHMVL159P2 / …’ - ¥δβ¥£®ΰαª /
*S: "9" <R1, BLACK> UHMVL159P3*
*T: <BLACK, R1> UHMVL159P3 / €ƒ - €£¨Ά®-¬λα /*				***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL159P4*
*T: <BLACK, R1> UHMVL159P4 / ‹“ - ¨«μβγ­-¬ οª /*			***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL159P5*
*T: <BLACK, R1> UHMVL159P5 / …‘ - ¥αη ­®¥-®§¥ΰ® /*			***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL159P6*
*T: <BLACK, R1> UHMVL159P6 / €€ - €­­ -®β¬,6¬, /*			***Schetinkin30.01.17***
S: "9" <R1, BLACK> UHMVL160P1
T: <BLACK, R1> UHMVL160P1 / ‹“ - ¨¦­¨©‚ « /
*S: "9" <R1, BLACK> UHMVL160P2*
*T: <BLACK, R1> UHMVL160P2 / ‘€ - — ©Ά®-¬ οª /*				***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL160P3*
*T: <BLACK, R1> UHMVL160P3 / ‹€ - ΰ« ­-„ /*				***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL160P4*
*T: <BLACK, R1> UHMVL160P4 / ‹ - ®«¨ª― ª-„ /*			***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL160P5*
*T: <BLACK, R1> UHMVL160P5 / …‘ - ¥αη ­®¥-®§¥ΰ® /*			***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL161P1*
*T: <BLACK, R1> UHMVL161P1 / € - ‚ βγ­£-®§¥ΰ® /*			***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL161P2*
*T: <BLACK, R1> UHMVL161P2 / €ƒ€ /*							***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL161P3*
*T: <BLACK, R1> UHMVL161P3 / ‘€ - •ΰ¥΅β®Άλ© /*				***Schetinkin30.01.17***
S: "9" <R1, BLACK> UHMVL161P4
T: <BLACK, R1> UHMVL161P4 / ’ - ’λ¬®Άαª®¥ /
*S: "9" <R1, BLACK> UHMVL162P1*
*T: <BLACK, R1> UHMVL162P1 / €‹ /*							***Schetinkin30.01.17***

S: "9" <R1, BLACK> UHMVL162P3
T: <BLACK, R1> UHMVL162P3 / ‹ - ®«μθ¥ΰ¥η¥­αª /
S: "9" <R1, BLACK> UHMVL162P4
T: <BLACK, R1> UHMVL162P4 / €‹ - ‚¥ΰε­¨©‚ « /
S: "9" <R1, BLACK> UHMVL162P5
T: <BLACK, R1> UHMVL162P5 / „€’ - 19-©΅«®ª―®αβ /
S: "9" <R1, BLACK> UHMVL162P6
T: <BLACK, R1> UHMVL162P6 / €‘ - λθ /
S: "9" <R1, BLACK> UHMVL162P7
T: <BLACK, R1> UHMVL162P7 / „ƒ - €«μ΅  /
S: "9" <R1, BLACK> UHMVL162P8
T: <BLACK, R1> UHMVL162P8 / ‘‹€ƒ€ - ‘« Ά  /
S: "9" <R1, BLACK> UHMVL162P9
T: <BLACK, R1> UHMVL162P9 / ’ - ’λ¬®Άαª®¥ /

S: "9" <R1, BLACK> UHMVL162P11
T: <BLACK, R1> UHMVL162P11 / € - ­®ΰ /
S: "9" <R1, BLACK> UHMVL162P12
T: <BLACK, R1> UHMVL162P12 / ‘€ - ‘¬¨ΰ­λε /
S: "9" <R1, BLACK> UHMVL162P13
T: <BLACK, R1> UHMVL162P13 / ƒ€ - ®ΰ®­ ©αª /
*S: "9" <R1, BLACK> UHMVL162P14*								***Schetinkin27.12.16***
*T: <BLACK, R1> UHMVL162P14 /  - ƒ αβ¥««® /*
S: "9" <R1, BLACK> UHMVL162P15
T: <BLACK, R1> UHMVL162P15 / ’“ - ¨βγ©-¬λα /
S: "9" <R1, BLACK> UHMVL162P16
T: <BLACK, R1> UHMVL162P16 / €ƒ‹ -  ª ΰ®Ά /
S: "9" <R1, BLACK> UHMVL162P17
T: <BLACK, R1> UHMVL162P17 / ‚ - ‚§¬®ΰμ¥ /
S: "9" <R1, BLACK> UHMVL162P18
T: <BLACK, R1> UHMVL162P18 / ‘ - ‘®Ά¥βαª®¥ /
*S: "9" <R1, BLACK> UHMVL162P19*
*T: <BLACK, R1> UHMVL162P19 / ‘‹€ - ‘®ª®« /*					***Schetinkin03.02.17***

S: "9" <R1, BLACK> UHMVL162P21
T: <BLACK, R1> UHMVL162P21 / €€ - €­¨Ά  /
*S: "9" <R1, BLACK> UHMVL162P22*
*T: <BLACK, R1> UHMVL162P22 / €€‘’ - €­ αβ α¨¨-¬λα /*			***Schetinkin27.01.17***
*S: "9" <R1, BLACK> UHMVL162P23*
*T: <BLACK, R1> UHMVL162P23 / ‹ - ΰ¨«μ®­-¬λα /*			***Schetinkin27.01.17***
*S: "9" <R1, BLACK> UHMVL163P1*
*T: <BLACK, R1> UHMVL163P1 / „“ /*							***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL163P2*
*T: <BLACK, R1> UHMVL163P2 / ‘‹€ - ‘®ª®« /*					***Schetinkin03.02.17***
*S: "9" <R1, BLACK> UHMVL164P1*
*T: <BLACK, R1> UHMVL164P1 / €‘ - ¨§ª¨©-¬λα /*				***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL164P2*
*T: <BLACK, R1> UHMVL164P2 / …€ - ¥ΰΆ®¬ ©αª /*				***Schetinkin30.01.17***
S: "9" <R1, BLACK> UHMVL164P3
T: <BLACK, R1> UHMVL164P3 / €€ - €΅ΰ ¬®Άª  /
S: "9" <R1, BLACK> UHMVL164P4
T: <BLACK, R1> UHMVL164P4 / ‹ - 10-©ª¬ /
S: "9" <R1, BLACK> UHMVL164P5
T: <BLACK, R1> UHMVL164P5 / ‹ - ΰ«®Ά® /
S: "9" <R1, BLACK> UHMVL164P6
T: <BLACK, R1> UHMVL164P6 /  - ®ΰ®­ ©-¨§£¨΅ΰ¥ª¨ /
S: "9" <R1, BLACK> UHMVL164P7
T: <BLACK, R1> UHMVL164P7 / ƒ€ - ®ΰ®­ ©αª /
*S: "9" <R1, BLACK> UHMVL165P1*
*T: <BLACK, R1> UHMVL165P1 / ’““„ - ’ΰγ¤®Ά®¥ /*				***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL165P2*
*T: <BLACK, R1> UHMVL165P2 / ‹€„ - ‚« ¤¨¬¨ΰ®Ά® /*				***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL165P3*
*T: <BLACK, R1> UHMVL165P3 / ƒ„ - ƒΆ®§¤¥Ά -¬λα /*			***Schetinkin30.01.17***
S: "9" <R1, BLACK> UHMVL166P1
T: <BLACK, R1> UHMVL166P1 / …‹€‘ - ¥Ά¥«μαª /
S: "9" <R1, BLACK> UHMVL166P2
T: <BLACK, R1> UHMVL166P2 / €€ - €­¨Ά  /
*S: "9" <R1, BLACK> UHMVL167P1*
*T: <BLACK, R1> UHMVL167P1 / ‘“’ /*							***Schetinkin27.01.16***
*S: "9" <R1, BLACK> UHMVL167P2*
*T: <BLACK, R1> UHMVL167P2 / ‘€ /*							***Schetinkin27.01.16***
*S: "9" <R1, BLACK> UHMVL167P5*			
*T: <BLACK, R1> UHMVL167P5 / €… /*							***Schetinkin27.01.16***
S: "9" <R1, BLACK> UHMVL168P1
T: <BLACK, R1> UHMVL168P1 / ‘‹ - •®«¬αª /

*S: "9" <R1, BLACK> UHMVL168P3*
*T: <BLACK, R1> UHMVL168P3 / ‹‘ /*							***Schetinkin27.01.16***
S: "9" <R1, BLACK> UHMVL169P1
T: <BLACK, R1> UHMVL169P1 / ‘‹ - •®«¬αª /
S: "9" <R1, BLACK> UHMVL169P2
T: <BLACK, R1> UHMVL169P2 / €€ - €­¨Ά  /
*S: "9" <R1, BLACK> UHMVL169P3*
*T: <BLACK, R1> UHMVL169P3 / ‘€ - ®ΰα ª®Ά /*				***Schetinkin03.02.17***
*S: "9" <R1, BLACK> UHMVL169P4*
*T: <BLACK, R1> UHMVL169P4 / ‹‘ /*							***Schetinkin27.01.16***
S: "9" <R1, BLACK> UHMVL170P1
T: <BLACK, R1> UHMVL170P1 / ‘ - ‘®Ά¥βαª®¥ /
*S: "9" <R1, BLACK> UHMVL170P6*
*T: <BLACK, R1> UHMVL170P6 / ‹‘ /*							***Schetinkin27.01.16***
*S: "9" <R1, BLACK> UHMVL170P8*
*T: <BLACK, R1> UHMVL170P8 / “’…‘ /*							***Schetinkin27.01.16***
S: "9" <R1, BLACK> UHMVL171P1
T: <BLACK, R1> UHMVL171P1 / „€ - ε¤ ¬-¬λα /
S: "9" <R1, BLACK> UHMVL171P2
T: <BLACK, R1> UHMVL171P2 / €‹ - ‚¥ΰε­¨©‚ « /
S: "9" <R1, BLACK> UHMVL171P3
T: <BLACK, R1> UHMVL171P3 / ‹“ - ¨¦­¨©‚ « /
*S: "9" <R1, BLACK> UHMVL171P4*
*T: <BLACK, R1> UHMVL171P4 / ƒ€… /*							***Schetinkin27.01.16***
*S: "9" <R1, BLACK> UHMVL171P5	*
*T: <BLACK, R1> UHMVL171P5 / …‘ - ¥αη ­®¥-®§¥ΰ® /*			***Schetinkin30.01.17***
S: "9" <R1, BLACK> UHMVL171P6
T: <BLACK, R1> UHMVL171P6 / “’€ - γβ ªγ /
*S: "9" <R1, BLACK> UHMVL171P7*
*T: <BLACK, R1> UHMVL171P7 / €ƒ - €£¨Ά®-¬λα /*				***Schetinkin30.01.17***

*S: "9" <R1, BLACK> UHMVL171P10*
*T: <BLACK, R1> UHMVL171P10 / €‹ /*							***Schetinkin30.01.17***
S: "9" <R1, BLACK> UHMVL172P1
T: <BLACK, R1> UHMVL172P1 / “‹ - ®£¨΅¨ /
S: "9" <R1, BLACK> UHMVL172P2
T: <BLACK, R1> UHMVL172P2 / €„€€ /
S: "9" <R1, BLACK> UHMVL172P3
T: <BLACK, R1> UHMVL172P3 / „€’ - 19-©΅«®ª―®αβ /

*S: "9" <R1, BLACK> UHMVL172P5*
*T: <BLACK, R1> UHMVL172P5 / …‘… - ‚ §¨ /*					***Schetinkin30.01.17***
S: "9" <R1, BLACK> UHMVL173P1
T: <BLACK, R1> UHMVL173P1 / €’“ - ‚¨ εβγ /
S: "9" <R1, BLACK> UHMVL173P2
T: <BLACK, R1> UHMVL173P2 / €‘ - λθ /
*S: "9" <R1, BLACK> UHMVL173P3*
*T: <BLACK, R1> UHMVL173P3 / …‘… - ‚ §¨ /*					***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL173P4*
*T: <BLACK, R1> UHMVL173P4 / € - ‚ βγ­£-®§¥ΰ® /*			***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL173P5*
*T: <BLACK, R1> UHMVL173P5 / ‹“€ - ‹γ­-€-„ /*
*S: "9" <R1, BLACK> UHMVL174P1*
*T: <BLACK, R1> UHMVL174P1 / ‘… - λ©αª¨©-§ «¨Ά /*			***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL174P2*
*T: <BLACK, R1> UHMVL174P2 / €ƒ€ -  ©£ ­ /*					***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL174P3*
*T: <BLACK, R1> UHMVL174P3 / ‹“€ - ‹γ­-€-„ /*
*S: "9" <R1, BLACK> UHMVL175P1*
*T: <BLACK, R1> UHMVL175P1 / €‹ -  ΅¨«μ-28 /*				***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL175P2*
*T: <BLACK, R1> UHMVL175P2 / ‹“€ - ‹γ­-€-„ /*
*S: "9" <R1, BLACK> UHMVL176P1*
*T: <BLACK, R1> UHMVL176P1 / €„ -  --„ /*				***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL176P2*
*T: <BLACK, R1> UHMVL176P2 / ‹“ - ¨«μβγ­-¬ οª /*			***Schetinkin30.01.17***
S: "9" <R1, BLACK> UHMVL176P3
T: <BLACK, R1> UHMVL176P3 / “’€ - γβ ªγ /
S: "9" <R1, BLACK> UHMVL176P4
T: <BLACK, R1> UHMVL176P4 / €‹ - ‚¥ΰε­¨©‚ « /
S: "9" <R1, BLACK> UHMVL176P5
T: <BLACK, R1> UHMVL176P5 / …‹ - Ά ©-®§¥ΰ® /

*S: "9" <R1, BLACK> UHMVL177P6*
*T: <BLACK, R1> UHMVL177P6 / …’€„ - ε ΅¨-§ «¨Ά /*			***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL177P7*
*T: <BLACK, R1> UHMVL177P7 / €ƒ - €£¨Ά®-¬λα /*			***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL177P8*
*T: <BLACK, R1> UHMVL177P8 / €„ -  --„ /*			***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL177P9*
*T: <BLACK, R1> UHMVL177P9 / ‹ - ®«¨ª― ª-„ /*		***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL177P10*
*T: <BLACK, R1> UHMVL177P10 / €€ - €­­ -®β¬,6¬, /*		***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL177P11*
*T: <BLACK, R1> UHMVL177P11 / “‹ /*						***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL177P12*
*T: <BLACK, R1> UHMVL177P12 / ‘€ - — ©Ά®-¬ οª /*			***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL177P13*
*T: <BLACK, R1> UHMVL177P13 / €‹‘ - €ΰΆ «λθ-¬λα /*		***Schetinkin30.01.17***
*S: "9" <R1, BLACK> UHMVL177P14*
*T: <BLACK, R1> UHMVL177P14 / ‘… - λ©αª¨©-§ «¨Ά /*		***Schetinkin30.01.17***	

S: "9" <R1, BLACK> UHMVL177P16
T: <BLACK, R1> UHMVL177P16 / €‘ - λθ /
S: "9" <R1, BLACK> UHMVL177P17
T: <BLACK, R1> UHMVL177P17 / ‹… /
S: "9" <R1, BLACK> UHMVL177P18
T: <BLACK, R1> UHMVL177P18 / ‹… - •®ν /














S: "9" <R1, BLACK> P1010
T: <BLACK, R1> P1010 / ‹ /
S: "9" <R1, BLACK> UHMVL178P2
T: <BLACK, R1> UHMVL178P2 / €‹€ /
S: "9" <R1, BLACK> UHMVL178P3
T: <BLACK, R1> UHMVL178P3 / €’‘ /
S: "9" <R1, BLACK> P1011
T: <BLACK, R1> P1011 / €’€ /

S: "9" <R1, BLACK> P1012
T: <BLACK, R1> P1012 / …’’ /
S: "9" <R1, BLACK> UHMVL178P5
T: <BLACK, R1> UHMVL178P5 / “€ /
S: "9" <R1, BLACK> UHMVL178P6
T: <BLACK, R1> UHMVL178P6 / …’… /

S: "9" <R1, BLACK> UHMVL178P8
T: <BLACK, R1> UHMVL178P8 / “€ /

S: "9" <R1, BLACK> UHMVL178P10
T: <BLACK, R1> UHMVL178P10 / €‘‹ /
S: "9" <R1, BLACK> UHMVL178P11
T: <BLACK, R1> UHMVL178P11 / €ƒ“ /

S: "9" <R1, BLACK> UHMVL178P13
T: <BLACK, R1> UHMVL178P13 / …€ /

S: "9" <R1, BLACK> UHMVL178P15
T: <BLACK, R1> UHMVL178P15 / ’…’“ /
S: "9" <R1, BLACK> UHMVL178P16
T: <BLACK, R1> UHMVL178P16 / ’“‘ /

S: "9" <R1, BLACK> P1013
T: <BLACK, R1> P1013 / „ /

S: "9" <R1, BLACK> P1014
T: <BLACK, R1> P1014 / €€ /
S: "9" <R1, BLACK> UHMVL178P19
T: <BLACK, R1> UHMVL178P19 / ’€ /
S: "9" <R1, BLACK> UHMVL178P20
T: <BLACK, R1> UHMVL178P20 / € /
*S: "9" <R1, BLACK> UHMVL178P21*
*T: <BLACK, R1> UHMVL178P21 / €’€ /*
S: "9" <R1, BLACK> UHMVL178P22
T: <BLACK, R1> UHMVL178P22 / €“ /
S: "9" <R1, BLACK> P1015
T: <BLACK, R1> P1015 / ‘€‹€ /
S: "9" <R1, BLACK> UHMVL178P23
T: <BLACK, R1> UHMVL178P23 / …„€ /

S: "9" <R1, BLACK> P1016
T: <BLACK, R1> P1016 / ƒ„ /
S: "9" <R1, BLACK> UHMVL178P25
T: <BLACK, R1> UHMVL178P25 / „…‹€ /
S: "9" <R1, BLACK> UHMVL178P26
T: <BLACK, R1> UHMVL178P26 / “’€ /
S: "9" <R1, BLACK> P1017
T: <BLACK, R1> P1017 / €ƒ‘ /

S: "9" <R1, BLACK> P1018
T: <BLACK, R1> P1018 / € /
S: "9" <R1, BLACK> UHMVL178P28
T: <BLACK, R1> UHMVL178P28 /  /
S: "9" <R1, BLACK> P1019
T: <BLACK, R1> P1019 / ‘€€‹ /



S: "9" <R1, BLACK> P1020
T: <BLACK, R1> P1020 / “…’ /
S: "9" <R1, BLACK> P1021
T: <BLACK, R1> P1021 / €‘ /
S: "9" <R1, BLACK> P1022
T: <BLACK, R1> P1022 / …… /
*S: "9" <R1, BLACK> UHMVL178P30*
*T: <BLACK, R1> UHMVL178P30 / €’€ /*
*S: "9" <R1, BLACK> UHMVL178P31*
*T: <BLACK, R1> UHMVL178P31 /  /*
S: "9" <R1, BLACK> UHMVL178P32
T: <BLACK, R1> UHMVL178P32 / “…‘‘ /


*S: "9" <R1, BLACK> UHMVL179P1*
*T: <BLACK, R1> UHMVL179P1 / “•‚ /*				***Schetinkib25.05.17***
S: "9" <R1, BLACK> UHMVL179P2
T: <BLACK, R1> UHMVL179P2 / …’… /
S: "9" <R1, BLACK> UHMVL179P3
T: <BLACK, R1> UHMVL179P3 / …„ /
S: "9" <R1, BLACK> UHMVL179P4
T: <BLACK, R1> UHMVL179P4 / “…‹‹ /
S: "9" <R1, BLACK> UHMVL179P5
T: <BLACK, R1> UHMVL179P5 / € /
S: "9" <R1, BLACK> UHMVL179P6
T: <BLACK, R1> UHMVL179P6 / ‘€’ /
S: "9" <R1, BLACK> UHMVL179P7
T: <BLACK, R1> UHMVL179P7 / €‹ /
S: "9" <R1, BLACK> UHMVL179P8
T: <BLACK, R1> UHMVL179P8 / “……€ /
S: "9" <R1, BLACK> P1049
T: <BLACK, R1> P1049 / €“ /
S: "9" <R1, BLACK> UHMVL179P9
T: <BLACK, R1> UHMVL179P9 / ’ /
S: "9" <R1, BLACK> UHMVL179P10
T: <BLACK, R1> UHMVL179P10 / “€ /
S: "9" <R1, BLACK> P1050
T: <BLACK, R1> P1050 / €’… /
S: "9" <R1, BLACK> UHMVL179P11
T: <BLACK, R1> UHMVL179P11 / “…… /
*S: "9" <R1, BLACK> UHMVL179P12*
*T: <BLACK, R1> UHMVL179P12 / €€ /*			***Schetinkin13.02.17***
S: "9" <R1, BLACK> P1051
T: <BLACK, R1> P1051 / €€ /
S: "9" <R1, BLACK> UHMVL179P13
T: <BLACK, R1> UHMVL179P13 / „ /
S: "9" <R1, BLACK> UHMVL179P14
T: <BLACK, R1> UHMVL179P14 / “… /
S: "9" <R1, BLACK> UHMVL179P15
T: <BLACK, R1> UHMVL179P15 / €ƒ€ /
S: "9" <R1, BLACK> UHMVL179P16
T: <BLACK, R1> UHMVL179P16 / “……‘ /
S: "9" <R1, BLACK> UHMVL179P17
T: <BLACK, R1> UHMVL179P17 / ‘€ƒ /
S: "9" <R1, BLACK> UHMVL179P18
T: <BLACK, R1> UHMVL179P18 / €€… /
S: "9" <R1, BLACK> UHMVL179P19
T: <BLACK, R1> UHMVL179P19 / ’“‘ /


S: "9" <R1, BLACK> P1052
T: <BLACK, R1> P1052 / €‘ /			***Schetinkin13.02.17***
S: "9" <R1, BLACK> UHMVL180P2
T: <BLACK, R1> UHMVL180P2 / …‘’€ /
S: "9" <R1, BLACK> UHMVL180P3
T: <BLACK, R1> UHMVL180P3 / „ƒ /
S: "9" <R1, BLACK> UHMVL180P4
T: <BLACK, R1> UHMVL180P4 / ‹ /
S: "9" <R1, BLACK> UHMVL180P5
T: <BLACK, R1> UHMVL180P5 / ‘’€ /

S: "9" <R1, BLACK> UHMVL181P1
T: <BLACK, R1> UHMVL181P1 / “… /
S: "9" <R1, BLACK> P1053
T: <BLACK, R1> P1053 / €’“ /
S: "9" <R1, BLACK> P1054
T: <BLACK, R1> P1054 / „‹ /
S: "9" <R1, BLACK> P1055
T: <BLACK, R1> P1055 / … /
*S: "9" <R1, BLACK> UHMVL181P2*
*T: <BLACK, R1> UHMVL181P2 / …„“‘ /*				***Schetinkin13.02.17***

S: "9" <R1, BLACK> P1056
T: <BLACK, R1> P1056 / …„‘ /
S: "9" <R1, BLACK> UHMVL181P4
T: <BLACK, R1> UHMVL181P4 / “„ /
S: "9" <R1, BLACK> UHMVL181P5
T: <BLACK, R1> UHMVL181P5 / ‘“‹‹€ /
S: "9" <R1, BLACK> UHMVL181P6
T: <BLACK, R1> UHMVL181P6 / „ ­ª  /
S: "9" <R1, BLACK> UHMVL181P7
T: <BLACK, R1> UHMVL181P7 / ‹ ―¨α /
S: "9" <R1, BLACK> UHMVL181P8
T: <BLACK, R1> UHMVL181P8 / “… /
S: "9" <R1, BLACK> UHMVL181P9
T: <BLACK, R1> UHMVL181P9 / €„…„ /

S: "9" <R1, BLACK> UHMVL181P11
T: <BLACK, R1> UHMVL181P11 / …‹ /
S: "9" <R1, BLACK> UHMVL181P12
T: <BLACK, R1> UHMVL181P12 / “… /
S: "9" <R1, BLACK> UHMVL181P13
T: <BLACK, R1> UHMVL181P13 / ’‹ /
S: "9" <R1, BLACK> UHMVL181P14
T: <BLACK, R1> UHMVL181P14 / “… /

S: "9" <R1, BLACK> UHMVL182P1
T: <BLACK, R1> UHMVL182P1 / ƒ… /
S: "9" <R1, BLACK> UHMVL182P2
T: <BLACK, R1> UHMVL182P2 / “€ƒ€ /
S: "9" <R1, BLACK> UHMVL182P3
T: <BLACK, R1> UHMVL182P3 / “…’ /
S: "9" <R1, BLACK> UHMVL182P4
T: <BLACK, R1> UHMVL182P4 / “… /

S: "9" <R1, BLACK> UHMVL182P5
T: <BLACK, R1> UHMVL182P5 / ““ /
S: "9" <R1, BLACK> P1057
T: <BLACK, R1> P1057 / ‘“ /
S: "9" <R1, BLACK> UHMVL182P6
T: <BLACK, R1> UHMVL182P6 / “…‹ /
S: "9" <R1, BLACK> P1058
T: <BLACK, R1> P1058 / …„€ /
S: "9" <R1, BLACK> UHMVL182P7
T: <BLACK, R1> UHMVL182P7 / €„ /
S: "9" <R1, BLACK> UHMVL182P8
T: <BLACK, R1> UHMVL182P8 / …“‘’ /
S: "9" <R1, BLACK> P1059
T: <BLACK, R1> P1059 / ‹ /
S: "9" <R1, BLACK> UHMVL182P9
T: <BLACK, R1> UHMVL182P9 / “…‘ /
S: "9" <R1, BLACK> UHMVL182P10
T: <BLACK, R1> UHMVL182P10 / ƒ“‹ /
S: "9" <R1, BLACK> UHMVL182P11
T: <BLACK, R1> UHMVL182P11 / € /
S: "9" <R1, BLACK> UHMVL182P12
T: <BLACK, R1> UHMVL182P12 / “… /
S: "9" <R1, BLACK> UHMVL182P13
T: <BLACK, R1> UHMVL182P13 / €’ /

S: "9" <R1, BLACK> UHMVL182P15
T: <BLACK, R1> UHMVL182P15 / ’““ /
S: "9" <R1, BLACK> UHMVL182P16
T: <BLACK, R1> UHMVL182P16 / „ /
S: "9" <R1, BLACK> P1060
T: <BLACK, R1> P1060 / €‹€€ /


S: "9" <R1, BLACK> UHMVL183P1
T: <BLACK, R1> UHMVL183P1 / “…’ /
S: "9" <R1, BLACK> UHMVL183P2
T: <BLACK, R1> UHMVL183P2 / €‘ /
S: "9" <R1, BLACK> UHMVL183P3
T: <BLACK, R1> UHMVL183P3 / €ƒ€ /
S: "9" <R1, BLACK> P1061
T: <BLACK, R1> P1061 / ‘“’ /


S: "9" <R1, BLACK> UHMVL184P3
T: <BLACK, R1> UHMVL184P3 / …‹… /
S: "9" <R1, BLACK> UHMVL184P4
T: <BLACK, R1> UHMVL184P4 /  /
S: "9" <R1, BLACK> UHMVL184P5
T: <BLACK, R1> UHMVL184P5 / “…€ /

S: "9" <R1, BLACK> UHMVL185P1
T: <BLACK, R1> UHMVL185P1 / “… /
S: "9" <R1, BLACK> P1063
T: <BLACK, R1> P1063 / €“€ /
S: "9" <R1, BLACK> UHMVL185P2
T: <BLACK, R1> UHMVL185P2 / €‹ƒ /
S: "9" <R1, BLACK> UHMVL185P3
T: <BLACK, R1> UHMVL185P3 / €‹€ /
S: "9" <R1, BLACK> P1064
T: <BLACK, R1> P1064 / ƒ€ /

S: "9" <R1, BLACK> P1065
T: <BLACK, R1> P1065 / … /
S: "9" <R1, BLACK> UHMVL185P5
T: <BLACK, R1> UHMVL185P5 / €„“ /
S: "9" <R1, BLACK> UHMVL185P6
T: <BLACK, R1> UHMVL185P6 / ‹ /
S: "9" <R1, BLACK> UHMVL185P7
T: <BLACK, R1> UHMVL185P7 / “…‹ /
S: "9" <R1, BLACK> P1066
T: <BLACK, R1> P1066 / ‘ /
S: "9" <R1, BLACK> UHMVL185P8
T: <BLACK, R1> UHMVL185P8 / “‘ /
S: "9" <R1, BLACK> P1067
T: <BLACK, R1> P1067 /  /
S: "9" <R1, BLACK> UHMVL185P9
T: <BLACK, R1> UHMVL185P9 / “… /
S: "9" <R1, BLACK> P1068
T: <BLACK, R1> P1068 / “’…‘ /
S: "9" <R1, BLACK> UHMVL185P10
T: <BLACK, R1> UHMVL185P10 / “…“ /
S: "9" <R1, BLACK> UHMVL185P11
T: <BLACK, R1> UHMVL185P11 / “…• /
S: "9" <R1, BLACK> UHMVL185P12
T: <BLACK, R1> UHMVL185P12 / “…… /
S: "9" <R1, BLACK> UHMVL185P13
T: <BLACK, R1> UHMVL185P13 / ‘€ /
S: "9" <R1, BLACK> UHMVL185P14
T: <BLACK, R1> UHMVL185P14 / ‘€’“ /
S: "9" <R1, BLACK> UHMVL185P15
T: <BLACK, R1> UHMVL185P15 / “… /

S: "9" <R1, BLACK> UHMVL186P1
T: <BLACK, R1> UHMVL186P1 / “…… /
S: "9" <R1, BLACK> P1069
T: <BLACK, R1> P1069 / €ƒ /
S: "9" <R1, BLACK> UHMVL186P2
T: <BLACK, R1> UHMVL186P2 / “…… /

S: "9" <R1, BLACK> UHMVL187P1
T: <BLACK, R1> UHMVL187P1 / “… /
S: "9" <R1, BLACK> P1070
T: <BLACK, R1> P1070 / ‘’€ /
S: "9" <R1, BLACK> UHMVL187P2
T: <BLACK, R1> UHMVL187P2 / € /
S: "9" <R1, BLACK> P1071
T: <BLACK, R1> P1071 / €’ /

S: "9" <R1, BLACK> P1072
T: <BLACK, R1> P1072 / “€ /
S: "9" <R1, BLACK> UHMVL187P4
T: <BLACK, R1> UHMVL187P4 / …‘ /
S: "9" <R1, BLACK> UHMVL187P5
T: <BLACK, R1> UHMVL187P5 / “… /
S: "9" <R1, BLACK> UHMVL187P6
T: <BLACK, R1> UHMVL187P6 / €‘ /
S: "9" <R1, BLACK> UHMVL187P7
T: <BLACK, R1> UHMVL187P7 / ’…‹ /
S: "9" <R1, BLACK> UHMVL187P8
T: <BLACK, R1> UHMVL187P8 / …‹€ /
S: "9" <R1, BLACK> UHMVL187P9
T: <BLACK, R1> UHMVL187P9 / “… /


S: "9" <R1, BLACK> P1073
T: <BLACK, R1> P1073 / ’€ /
S: "9" <R1, BLACK> UHMVL188P2
T: <BLACK, R1> UHMVL188P2 / ’ƒ /
S: "9" <R1, BLACK> P1074
T: <BLACK, R1> P1074 / ƒ“…‹ /




S: "9" <R1, BLACK> P1023
T: <BLACK, R1> P1023 / €‘€ /

S: "9" <R1, BLACK> UHMVL189P2
T: <BLACK, R1> UHMVL189P2 / „“ /
S: "9" <R1, BLACK> UHMVL189P3
T: <BLACK, R1> UHMVL189P3 / „… /
S: "9" <R1, BLACK> UHMVL189P4
T: <BLACK, R1> UHMVL189P4 / “…‘ - ‘γ­β ΰ/
S: "9" <R1, BLACK> UHMVL189P5
T: <BLACK, R1> UHMVL189P5 / ƒ€€ /
S: "9" <R1, BLACK> UHMVL189P6
T: <BLACK, R1> UHMVL189P6 / “… /
S: "9" <R1, BLACK> UHMVL189P7
T: <BLACK, R1> UHMVL189P7 / €‹ƒ€ /
S: "9" <R1, BLACK> UHMVL189P8
T: <BLACK, R1> UHMVL189P8 / …’ /
S: "9" <R1, BLACK> UHMVL189P9
T: <BLACK, R1> UHMVL189P9 / “……• /
S: "9" <R1, BLACK> UHMVL189P10
T: <BLACK, R1> UHMVL189P10 / €’ /
S: "9" <R1, BLACK> UHMVL189P11
T: <BLACK, R1> UHMVL189P11 / “… /
S: "9" <R1, BLACK> UHMVL189P12
T: <BLACK, R1> UHMVL189P12 / ƒ€‹€‘ /
S: "9" <R1, BLACK> UHMVL189P13
T: <BLACK, R1> UHMVL189P13 / ’€ /
S: "9" <R1, BLACK> UHMVL189P14
T: <BLACK, R1> UHMVL189P14 / “…› /
S: "9" <R1, BLACK> UHMVL189P15
T: <BLACK, R1> UHMVL189P15 / ’ /
S: "9" <R1, BLACK> UHMVL189P16
T: <BLACK, R1> UHMVL189P16 / ‘€„€ƒ /
S: "9" <R1, BLACK> UHMVL189P17
T: <BLACK, R1> UHMVL189P17 / “…• /
S: "9" <R1, BLACK> UHMVL189P18
T: <BLACK, R1> UHMVL189P18 / ‘… /
S: "9" <R1, BLACK> UHMVL189P19
T: <BLACK, R1> UHMVL189P19 / “‘ /
S: "9" <R1, BLACK> UHMVL189P20
T: <BLACK, R1> UHMVL189P20 / …“ /
S: "9" <R1, BLACK> UHMVL189P21
T: <BLACK, R1> UHMVL189P21 / …“ /
S: "9" <R1, BLACK> UHMVL189P22
T: <BLACK, R1> UHMVL189P22 / €€ /
S: "9" <R1, BLACK> P1024
T: <BLACK, R1> P1024 / …„ /
S: "9" <R1, BLACK> UHMVL189P23
T: <BLACK, R1> UHMVL189P23 / €“ /
S: "9" <R1, BLACK> UHMVL189P24
T: <BLACK, R1> UHMVL189P24 / “…’ /
S: "9" <R1, BLACK> UHMVL189P25
T: <BLACK, R1> UHMVL189P25 / ‘“ /
S: "9" <R1, BLACK> UHMVL189P26
T: <BLACK, R1> UHMVL189P26 / ‘€‘ /
S: "9" <R1, BLACK> UHMVL189P27
T: <BLACK, R1> UHMVL189P27 / „€‹… /
S: "9" <R1, BLACK> UHMVL189P28
T: <BLACK, R1> UHMVL189P28 / …€ /
S: "9" <R1, BLACK> P1025
T: <BLACK, R1> P1025 / “ƒ…€ /



S: "9" <R1, BLACK> P1075
T: <BLACK, R1> P1075 / €’€ /
S: "9" <R1, BLACK> UHMVL190P2
T: <BLACK, R1> UHMVL190P2 / „‘“ /
S: "9" <R1, BLACK> UHMVL190P3
T: <BLACK, R1> UHMVL190P3 / “…‘ /
S: "9" <R1, BLACK> P1076
T: <BLACK, R1> P1076 / “ /
S: "9" <R1, BLACK> UHMVL190P4
T: <BLACK, R1> UHMVL190P4 / ‹“’ /
S: "9" <R1, BLACK> P1077
T: <BLACK, R1> P1077 / ‘…€ /
S: "9" <R1, BLACK> UHMVL190P5
T: <BLACK, R1> UHMVL190P5 / “… /
S: "9" <R1, BLACK> P1078
T: <BLACK, R1> P1078 / €ƒ /
S: "9" <R1, BLACK> UHMVL190P6
T: <BLACK, R1> UHMVL190P6 / ‘€„“ /
S: "9" <R1, BLACK> UHMVL190P7
T: <BLACK, R1> UHMVL190P7 / ’€‹“ /
S: "9" <R1, BLACK> UHMVL190P8
T: <BLACK, R1> UHMVL190P8 / € /
S: "9" <R1, BLACK> UHMVL190P9
T: <BLACK, R1> UHMVL190P9 / “…‹‹ /
S: "9" <R1, BLACK> UHMVL190P10
T: <BLACK, R1> UHMVL190P10 / ‘€ /
S: "9" <R1, BLACK> UHMVL190P11
T: <BLACK, R1> UHMVL190P11 / “…‹… /
S: "9" <R1, BLACK> UHMVL190P12
T: <BLACK, R1> UHMVL190P12 / „„€ /

S: "9" <R1, BLACK> UHMVL191P1
T: <BLACK, R1> UHMVL191P1 / …‹“ /
S: "9" <R1, BLACK> UHMVL191P2
T: <BLACK, R1> UHMVL191P2 / ‹€ /
S: "9" <R1, BLACK> UHMVL191P3
T: <BLACK, R1> UHMVL191P3 / € /
S: "9" <R1, BLACK> P1079
T: <BLACK, R1> P1079 / ‹“ƒ /
S: "9" <R1, BLACK> UHMVL191P4
T: <BLACK, R1> UHMVL191P4 / “… /
S: "9" <R1, BLACK> UHMVL192P1
T: <BLACK, R1> UHMVL192P1 / “… /
S: "9" <R1, BLACK> UHMVL192P2
T: <BLACK, R1> UHMVL192P2 / …€ /
*S: "9" <R1, BLACK> UHMVL192P3*
*T: <BLACK, R1> UHMVL192P3 / €€‘ /*				***Schetinkin17.02.17***
S: "9" <R1, BLACK> UHMVL192P4
T: <BLACK, R1> UHMVL192P4 / „…€ /
S: "9" <R1, BLACK> UHMVL192P5
T: <BLACK, R1> UHMVL192P5 / €€‘ /
S: "9" <R1, BLACK> UHMVL192P6
T: <BLACK, R1> UHMVL192P6 / €“‘ /


S: "9" <R1, BLACK> UHMVL193P2
T: <BLACK, R1> UHMVL193P2 / ‘€…’ /
S: "9" <R1, BLACK> UHMVL193P3
T: <BLACK, R1> UHMVL193P3 / “……‘ /

S: "9" <R1, BLACK> UHMVL194P2
T: <BLACK, R1> UHMVL194P2 / …’‹ /
S: "9" <R1, BLACK> UHMVL194P3
T: <BLACK, R1> UHMVL194P3 / „… /
S: "9" <R1, BLACK> P1080
T: <BLACK, R1> P1080 /  /
S: "9" <R1, BLACK> UHMVL194P4
T: <BLACK, R1> UHMVL194P4 / “… /
S: "9" <R1, BLACK> P1081
T: <BLACK, R1> P1081 / ‘‹„€ /
S: "9" <R1, BLACK> UHMVL194P5
T: <BLACK, R1> UHMVL194P5 / “… /
S: "9" <R1, BLACK> UHMVL194P6
T: <BLACK, R1> UHMVL194P6 / “… /
*S: "9" <R1, BLACK> UHMVL194P7*
*T: <BLACK, R1> UHMVL194P7 / ’€€ /*				***Schetinkin17.02.17***
S: "9" <R1, BLACK> UHMVL194P8
T: <BLACK, R1> UHMVL194P8 / ‘€ /
S: "9" <R1, BLACK> UHMVL194P9
T: <BLACK, R1> UHMVL194P9 / ƒ€ /
S: "9" <R1, BLACK> UHMVL194P10
T: <BLACK, R1> UHMVL194P10 / ‘ /
S: "9" <R1, BLACK> UHMVL194P11
T: <BLACK, R1> UHMVL194P11 / “…‹‹ /
S: "9" <R1, BLACK> UHMVL194P12
T: <BLACK, R1> UHMVL194P12 / ‘€ /
S: "9" <R1, BLACK> UHMVL194P13
T: <BLACK, R1> UHMVL194P13 / ‘…‹ /
S: "9" <R1, BLACK> UHMVL194P14
T: <BLACK, R1> UHMVL194P14 / ’ /
S: "9" <R1, BLACK> UHMVL194P15
T: <BLACK, R1> UHMVL194P15 / ‘“€ /

S: "9" <R1, BLACK> UHMVL195P1
T: <BLACK, R1> UHMVL195P1 / “… /
S: "9" <R1, BLACK> P1082
T: <BLACK, R1> P1082 / € /
S: "9" <R1, BLACK> UHMVL195P2
T: <BLACK, R1> UHMVL195P2 / “…’ /
S: "9" <R1, BLACK> UHMVL195P3
T: <BLACK, R1> UHMVL195P3 / …‘ /
S: "9" <R1, BLACK> UHMVL195P4
T: <BLACK, R1> UHMVL195P4 / “… /
*S: "9" <R1, BLACK> UHMVL195P5*
*T: <BLACK, R1> UHMVL195P5 / ‘€ /*			***Schetinkin17.02.17***
S: "9" <R1, BLACK> UHMVL195P6
T: <BLACK, R1> UHMVL195P6 / ‘…… /
S: "9" <R1, BLACK> UHMVL195P7
T: <BLACK, R1> UHMVL195P7 / “……€ /
S: "9" <R1, BLACK> UHMVL195P8
T: <BLACK, R1> UHMVL195P8 / ’€ /
S: "9" <R1, BLACK> UHMVL195P9
T: <BLACK, R1> UHMVL195P9 / „„€ /


S: "9" <R1, BLACK> UHMVL196P2
T: <BLACK, R1> UHMVL196P2 / ’ /
S: "9" <R1, BLACK> UHMVL196P3
T: <BLACK, R1> UHMVL196P3 / ““ /
S: "9" <R1, BLACK> UHMVL196P4
T: <BLACK, R1> UHMVL196P4 / ‘… /
S: "9" <R1, BLACK> UHMVL196P5
T: <BLACK, R1> UHMVL196P5 / ‹€ƒ€ /
S: "9" <R1, BLACK> UHMVL197P1
T: <BLACK, R1> UHMVL197P1 / “…‹… /
S: "9" <R1, BLACK> UHMVL197P2
T: <BLACK, R1> UHMVL197P2 / ƒ€‹ /
S: "9" <R1, BLACK> UHMVL197P3
T: <BLACK, R1> UHMVL197P3 / €“ /
S: "9" <R1, BLACK> UHMVL197P4
T: <BLACK, R1> UHMVL197P4 / „……‘ /
S: "9" <R1, BLACK> UHMVL197P5
T: <BLACK, R1> UHMVL197P5 / ‹€ƒ€ /
S: "9" <R1, BLACK> UHMVL197P6
T: <BLACK, R1> UHMVL197P6 / €‹ƒ€“ /
S: "9" <R1, BLACK> UHMVL197P7
T: <BLACK, R1> UHMVL197P7 / ’ - ’®ª®-¬¥β¥® /

S: "9" <R1, BLACK> UHMVL198P1
T: <BLACK, R1> UHMVL198P1 / “…‹‹ /
S: "9" <R1, BLACK> UHMVL198P2
T: <BLACK, R1> UHMVL198P2 / “‹€ /
S: "9" <R1, BLACK> UHMVL198P3
T: <BLACK, R1> UHMVL198P3 / €“ /
S: "9" <R1, BLACK> UHMVL198P4
T: <BLACK, R1> UHMVL198P4 / „‘… /
S: "9" <R1, BLACK> UHMVL198P5
T: <BLACK, R1> UHMVL198P5 / “‹ /
S: "9" <R1, BLACK> UHMVL198P6
T: <BLACK, R1> UHMVL198P6 / ‘“€ /
S: "9" <R1, BLACK> UHMVL198P7
T: <BLACK, R1> UHMVL198P7 / “……ƒ /
S: "9" <R1, BLACK> UHMVL198P8
T: <BLACK, R1> UHMVL198P8 / “’€ /
S: "9" <R1, BLACK> UHMVL198P9
T: <BLACK, R1> UHMVL198P9 / “…… - ¥«μª η¨-‹¥Άλ¥ /
S: "9" <R1, BLACK> UHMVL198P10
T: <BLACK, R1> UHMVL198P10 / “… /
S: "9" <R1, BLACK> P1083
T: <BLACK, R1> P1083 / ‹ /
S: "9" <R1, BLACK> UHMVL198P11
T: <BLACK, R1> UHMVL198P11 / “…“ /
S: "9" <R1, BLACK> P1084
T: <BLACK, R1> P1084 / €…€ /
S: "9" <R1, BLACK> UHMVL198P12
T: <BLACK, R1> UHMVL198P12 / “‘ /
S: "9" <R1, BLACK> UHMVL198P13
T: <BLACK, R1> UHMVL198P13 / “…„ /
S: "9" <R1, BLACK> P1085
T: <BLACK, R1> P1085 / „€€‘ /
S: "9" <R1, BLACK> UHMVL198P14
T: <BLACK, R1> UHMVL198P14 / “…• /

S: "9" <R1, BLACK> UHMVL199P1
T: <BLACK, R1> UHMVL199P1 / ’ /
S: "9" <R1, BLACK> UHMVL199P2
T: <BLACK, R1> UHMVL199P2 / “……ƒ /
S: "9" <R1, BLACK> UHMVL199P3
T: <BLACK, R1> UHMVL199P3 / “…… - ¥«μª η¨-‹¥Άλ¥ /
S: "9" <R1, BLACK> UHMVL199P4
T: <BLACK, R1> UHMVL199P4 / “……‚ /

S: "9" <R1, BLACK> UHMVL200P1
T: <BLACK, R1> UHMVL200P1 / “…€ /
S: "9" <R1, BLACK> UHMVL200P2
T: <BLACK, R1> UHMVL200P2 / „…€ /
S: "9" <R1, BLACK> UHMVL200P3
T: <BLACK, R1> UHMVL200P3 / “… /
S: "9" <R1, BLACK> P1026
T: <BLACK, R1> P1026 / €‹’ /

S: "9" <R1, BLACK> UHMVL200P5
T: <BLACK, R1> UHMVL200P5 / ‘“ /
S: "9" <R1, BLACK> P1027
T: <BLACK, R1> P1027 / ‹ /

S: "9" <R1, BLACK> UHMVL200P7
T: <BLACK, R1> UHMVL200P7 / ‘…€ /
S: "9" <R1, BLACK> UHMVL200P8
T: <BLACK, R1> UHMVL200P8 / „€ /
S: "9" <R1, BLACK> UHMVL200P9
T: <BLACK, R1> UHMVL200P9 / ƒ€‘ /
S: "9" <R1, BLACK> UHMVL200P10
T: <BLACK, R1> UHMVL200P10 / “…‘ /
S: "9" <R1, BLACK> UHMVL200P11
T: <BLACK, R1> UHMVL200P11 / …„ /
S: "9" <R1, BLACK> UHMVL200P12
T: <BLACK, R1> UHMVL200P12 / “…‚ /
S: "9" <R1, BLACK> P1028
T: <BLACK, R1> P1028 / €‘€„ /
S: "9" <R1, BLACK> UHMVL200P13

S: "9" <R1, BLACK> UHMVL201P2
T: <BLACK, R1> UHMVL201P2 / ‘€ƒ /
S: "9" <R1, BLACK> UHMVL202P1
T: <BLACK, R1> UHMVL202P1 / „ /
S: "9" <R1, BLACK> UHMVL202P2
T: <BLACK, R1> UHMVL202P2 / €’“ /
S: "9" <R1, BLACK> UHMVL202P3
T: <BLACK, R1> UHMVL202P3 / “……‚ /
S: "9" <R1, BLACK> UHMVL202P4
T: <BLACK, R1> UHMVL202P4 / “… /

S: "9" <R1, BLACK> UHMVL203P1
T: <BLACK, R1> UHMVL203P1 / “……‚ /
S: "9" <R1, BLACK> P1086
T: <BLACK, R1> P1086 / €„ /
S: "9" <R1, BLACK> UHMVL203P2
T: <BLACK, R1> UHMVL203P2 / “…“ /
S: "9" <R1, BLACK> P1087
T: <BLACK, R1> P1087 / ’ƒ“‹ /
S: "9" <R1, BLACK> UHMVL203P3
T: <BLACK, R1> UHMVL203P3 / “… /
S: "9" <R1, BLACK> UHMVL203P4
T: <BLACK, R1> UHMVL203P4 / …ƒ… /

S: "9" <R1, BLACK> UHMVL204P1
T: <BLACK, R1> UHMVL204P1 / “…“ /
S: "9" <R1, BLACK> P1088
T: <BLACK, R1> P1088 / ‹…‹‘ /
S: "9" <R1, BLACK> UHMVL204P3
T: <BLACK, R1> UHMVL204P3 / ’ƒ€ /
S: "9" <R1, BLACK> UHMVL204P4
T: <BLACK, R1> UHMVL204P4 / ‹‘ /
S: "9" <R1, BLACK> UHMVL204P5
T: <BLACK, R1> UHMVL204P5 / “…… /

S: "9" <R1, BLACK> UHMVL205P1
T: <BLACK, R1> UHMVL205P1 / “…… /
S: "9" <R1, BLACK> UHMVL205P2
T: <BLACK, R1> UHMVL205P2 / “‘“ƒ /
S: "9" <R1, BLACK> UHMVL205P3
T: <BLACK, R1> UHMVL205P3 / “„ /
S: "9" <R1, BLACK> UHMVL205P4
T: <BLACK, R1> UHMVL205P4 / “…‹ /
S: "9" <R1, BLACK> UHMVL205P5
T: <BLACK, R1> UHMVL205P5 / “‘’ /
S: "9" <R1, BLACK> UHMVL205P6
T: <BLACK, R1> UHMVL205P6 / “… /
S: "9" <R1, BLACK> UHMVL205P7
T: <BLACK, R1> UHMVL205P7 / ’€ /
S: "9" <R1, BLACK> P1089
T: <BLACK, R1> P1089 / ‹… /
S: "9" <R1, BLACK> UHMVL205P8
T: <BLACK, R1> UHMVL205P8 / “…• /
S: "9" <R1, BLACK> P1090
T: <BLACK, R1> P1090 / ’€’“ /
S: "9" <R1, BLACK> UHMVL205P9
T: <BLACK, R1> UHMVL205P9 / ’ /
S: "9" <R1, BLACK> UHMVL205P10
T: <BLACK, R1> UHMVL205P10 / ’‹ /
S: "9" <R1, BLACK> UHMVL205P11
T: <BLACK, R1> UHMVL205P11 / ‘€ƒ /
S: "9" <R1, BLACK> UHMVL205P12
T: <BLACK, R1> UHMVL205P12 / “‹ /
S: "9" <R1, BLACK> P1091
T: <BLACK, R1> P1091 / ƒ‘’ /

S: "9" <R1, BLACK> P1092
T: <BLACK, R1> P1092 / ‘€ /
S: "9" <R1, BLACK> UHMVL205P14
T: <BLACK, R1> UHMVL205P14 / “… /
S: "9" <R1, BLACK> UHMVL205P15
T: <BLACK, R1> UHMVL205P15 / “€ /
S: "9" <R1, BLACK> UHMVL205P16
T: <BLACK, R1> UHMVL205P16 / “…’/
S: "9" <R1, BLACK> P1093
T: <BLACK, R1> P1093 / €ƒ€ /
S: "9" <R1, BLACK> UHMVL205P17
T: <BLACK, R1> UHMVL205P17 / …‘‹ /
S: "9" <R1, BLACK> UHMVL205P18
T: <BLACK, R1> UHMVL205P18 / …‘ /
S: "9" <R1, BLACK> UHMVL205P19
T: <BLACK, R1> UHMVL205P19 / “… /

S: "9" <R1, BLACK> UHMVL206P1
T: <BLACK, R1> UHMVL206P1 / “…“ /
S: "9" <R1, BLACK> P1094
T: <BLACK, R1> P1094 / ƒ‹ /
S: "9" <R1, BLACK> UHMVL206P2
T: <BLACK, R1> UHMVL206P2 / ‹ƒ /
S: "9" <R1, BLACK> UHMVL206P3
T: <BLACK, R1> UHMVL206P3 / “„ /

S: "9" <R1, BLACK> P1095
T: <BLACK, R1> P1095 / € /
S: "9" <R1, BLACK> UHMVL207P2
T: <BLACK, R1> UHMVL207P2 / € /
S: "9" <R1, BLACK> UHMVL207P3
T: <BLACK, R1> UHMVL207P3 / “ /
S: "9" <R1, BLACK> UHMVL207P4
T: <BLACK, R1> UHMVL207P4 / “…‘… /

S: "9" <R1, BLACK> UHMVL208P1
T: <BLACK, R1> UHMVL208P1 / “…‘… /
S: "9" <R1, BLACK> UHMVL208P2
T: <BLACK, R1> UHMVL208P2 / €ƒ“ /
S: "9" <R1, BLACK> P1096
T: <BLACK, R1> P1096 / ’‘ /
S: "9" <R1, BLACK> UHMVL208P3
T: <BLACK, R1> UHMVL208P3 / “…’ /
*S: "9" <R1, BLACK> UHMVL208P4*
*T: <BLACK, R1> UHMVL208P4 / €„€„ /*			***Schetinkin17.02.17***
S: "9" <R1, BLACK> P1097
T: <BLACK, R1> P1097 / ‘“… /
S: "9" <R1, BLACK> P1098
T: <BLACK, R1> P1098 / …‘’ /
S: "9" <R1, BLACK> P1099
T: <BLACK, R1> P1099 / ““‹ /
S: "9" <R1, BLACK> UHMVL208P5
T: <BLACK, R1> UHMVL208P5 / €’€“ /

S: "9" <R1, BLACK> UHMVL209P1
T: <BLACK, R1> UHMVL209P1 / “… /
S: "9" <R1, BLACK> UHMVL209P2
T: <BLACK, R1> UHMVL209P2 / ‹„… /
S: "9" <R1, BLACK> UHMVL209P3
T: <BLACK, R1> UHMVL209P3 / “… /
S: "9" <R1, BLACK> P1100
T: <BLACK, R1> P1100 / ‘€‹ /
S: "9" <R1, BLACK> UHMVL209P4
T: <BLACK, R1> UHMVL209P4 / €’€“ /
S: "9" <R1, BLACK> P1101
T: <BLACK, R1> P1101 / ‘… /
S: "9" <R1, BLACK> UHMVL209P5
T: <BLACK, R1> UHMVL209P5 / “…‘ /
S: "9" <R1, BLACK> UHMVL209P6
T: <BLACK, R1> UHMVL209P6 / €€“ /
S: "9" <R1, BLACK> P1102
T: <BLACK, R1> P1102 / „ƒ /
S: "9" <R1, BLACK> UHMVL209P7
T: <BLACK, R1> UHMVL209P7 / “…‘” /

S: "9" <R1, BLACK> UHMVL210P1
T: <BLACK, R1> UHMVL210P1 / “… /
S: "9" <R1, BLACK> UHMVL210P2
T: <BLACK, R1> UHMVL210P2 / €„…€ /
S: "9" <R1, BLACK> P1103
T: <BLACK, R1> P1103 / ’ /
S: "9" <R1, BLACK> UHMVL210P3
T: <BLACK, R1> UHMVL210P3 / “…‘ /
S: "9" <R1, BLACK> UHMVL210P4
T: <BLACK, R1> UHMVL210P4 / “…… /
S: "9" <R1, BLACK> UHMVL210P5
T: <BLACK, R1> UHMVL210P5 / €€“ /
S: "9" <R1, BLACK> P1104
T: <BLACK, R1> P1104 / …‹€ /
S: "9" <R1, BLACK> UHMVL210P6
T: <BLACK, R1> UHMVL210P6 / “…‘ƒ /
S: "9" <R1, BLACK> P1105
T: <BLACK, R1> P1105 / €ƒ /
S: "9" <R1, BLACK> UHMVL210P7
T: <BLACK, R1> UHMVL210P7 /  /
S: "9" <R1, BLACK> UHMVL210P8
T: <BLACK, R1> UHMVL210P8 / ‹… /
S: "9" <R1, BLACK> UHMVL210P9
T: <BLACK, R1> UHMVL210P9 / ‹€ /
S: "9" <R1, BLACK> P1106
T: <RED, R1> P1106 / “…‘ /
*S: "9" <R1, BLACK> UHMVL210P10*
*T: <BLACK, R1> UHMVL210P10 / ‹“…’ /*
S: "9" <R1, BLACK> UHMVL210P11
T: <BLACK, R1> UHMVL210P11 / ‹“ /
S: "9" <R1, BLACK> UHMVL210P12
T: <BLACK, R1> UHMVL210P12 / “…‘ /

S: "9" <R1, BLACK> UHMVL211P1
T: <BLACK, R1> UHMVL211P1 / ‘’€ /
S: "9" <R1, BLACK> UHMVL211P2
T: <BLACK, R1> UHMVL211P2 / “…‘ /
*S: "9" <R1, BLACK> P1029
*T: <BLACK, R1> P1029 / …‹€ /

S: "9" <R1, BLACK> UHMVL211P5
T: <BLACK, R1> UHMVL211P5 /  /
S: "9" <R1, BLACK> UHMVL211P6
T: <BLACK, R1> UHMVL211P6 / “… /
S: "9" <R1, BLACK> UHMVL211P7
T: <BLACK, R1> UHMVL211P7 / ‘ƒ /
S: "9" <R1, BLACK> UHMVL211P8
T: <BLACK, R1> UHMVL211P8 / ’’ /
S: "9" <R1, BLACK> UHMVL211P9
T: <BLACK, R1> UHMVL211P9 / “…‘ /
S: "9" <R1, BLACK> UHMVL211P10
T: <BLACK, R1> UHMVL211P10 / ’€…‘ /
S: "9" <R1, BLACK> UHMVL211P11
T: <BLACK, R1> UHMVL211P11 / ‹€“„ /
S: "9" <R1, BLACK> UHMVL211P12
T: <BLACK, R1> UHMVL211P12 / € /
S: "9" <R1, BLACK> UHMVL211P13
T: <BLACK, R1> UHMVL211P13 / “…‘ /
*S: "9" <R1, BLACK> UHMVL211P14*
*T: <BLACK, R1> UHMVL211P14 / …‹€ /*
S: "9" <R1, BLACK> UHMVL211P15
T: <BLACK, R1> UHMVL211P15 / “…‘‘ /

S: "9" <R1, BLACK> UHMVL212P1
T: <BLACK, R1> UHMVL212P1 / “…’ /
S: "9" <R1, BLACK> P1107
T: <BLACK, R1> P1107 / ‹‹ /
S: "9" <R1, BLACK> UHMVL212P2
T: <BLACK, R1> UHMVL212P2 / €„ /
S: "9" <R1, BLACK> UHMVL212P3
T: <BLACK, R1> UHMVL212P3 / “…… /
S: "9" <R1, BLACK> UHMVL212P4
T: <BLACK, R1> UHMVL212P4 / €„‹ /
S: "9" <R1, BLACK> UHMVL212P5
T: <BLACK, R1> UHMVL212P5 / “…‘‰ /
S: "9" <R1, BLACK> UHMVL212P6
T: <BLACK, R1> UHMVL212P6 / ‹“ƒ… /
S: "9" <R1, BLACK> UHMVL212P7
T: <BLACK, R1> UHMVL212P7 / “…‘ /
S: "9" <R1, BLACK> UHMVL213P1
T: <BLACK, R1> UHMVL213P1 / €“ /
S: "9" <R1, BLACK> P1108
T: <BLACK, R1> P1108 / “€ /
S: "9" <R1, BLACK> UHMVL213P2
T: <BLACK, R1> UHMVL213P2 / € /
S: "9" <R1, BLACK> UHMVL213P3
T: <BLACK, R1> UHMVL213P3 / “…… /
S: "9" <R1, BLACK> UHMVL214P1
T: <BLACK, R1> UHMVL214P1 / € /
S: "9" <R1, BLACK> UHMVL214P2
T: <BLACK, R1> UHMVL214P2 / ‹“ƒ“ /
S: "9" <R1, BLACK> UHMVL214P3
T: <BLACK, R1> UHMVL214P3 / “…‘‰ /
S: "9" <R1, BLACK> UHMVL214P4
T: <BLACK, R1> UHMVL214P4 / “…‘ /
S: "9" <R1, BLACK> UHMVL214P5
T: <BLACK, R1> UHMVL214P5 / ‹… /

S: "9" <R1, BLACK> UHMVL215P1
T: <BLACK, R1> UHMVL215P1 / “…‘ /
S: "9" <R1, BLACK> UHMVL215P2
T: <BLACK, R1> UHMVL215P2 / „’“ /
S: "9" <R1, BLACK> UHMVL215P3
T: <BLACK, R1> UHMVL215P3 / “…‘ /
S: "9" <R1, BLACK> UHMVL215P4
T: <BLACK, R1> UHMVL215P4 / ‘ƒ… /
S: "9" <R1, BLACK> P1109
T: <BLACK, R1> P1109 / €“ /
S: "9" <R1, BLACK> UHMVL215P5
T: <BLACK, R1> UHMVL215P5 / “…‘ƒ /
S: "9" <R1, BLACK> P1110
T: <BLACK, R1> P1110 / € /
S: "9" <R1, BLACK> UHMVL215P6
T: <BLACK, R1> UHMVL215P6 / “…ƒ /
S: "9" <R1, BLACK> UHMVL215P7
T: <BLACK, R1> UHMVL215P7 / ‘‘ /
S: "9" <R1, BLACK> UHMVL215P8
T: <BLACK, R1> UHMVL215P8 / ‘€‹€ /
S: "9" <R1, BLACK> UHMVL215P9
T: <BLACK, R1> UHMVL215P9 / “…‚ƒ /
S: "9" <R1, BLACK> P1111
T: <BLACK, R1> P1111 / €‘€ /
S: "9" <R1, BLACK> UHMVL215P10
T: <BLACK, R1> UHMVL215P10 / …„€ /
S: "9" <R1, BLACK> UHMVL215P11
T: <BLACK, R1> UHMVL215P11 / “…ƒ’ /
S: "9" <R1, BLACK> P1112
T: <BLACK, R1> P1112 / ‘…€ /
S: "9" <R1, BLACK> UHMVL215P12
T: <BLACK, R1> UHMVL215P12 / ’ /
S: "9" <R1, BLACK> UHMVL215P13
T: <BLACK, R1> UHMVL215P13 / “…€’ /
S: "9" <R1, BLACK> UHMVL215P14
T: <BLACK, R1> UHMVL215P14 / €ƒ€‘ /
S: "9" <R1, BLACK> UHMVL215P15
T: <BLACK, R1> UHMVL215P15 / ’‹ /
S: "9" <R1, BLACK> P1114
T: <BLACK, R1> P1114 / “€ /
S: "9" <R1, BLACK> UHMVL215P16
T: <BLACK, R1> UHMVL215P16 / “…€ /
S: "9" <R1, BLACK> UHMVL215P17
T: <BLACK, R1> UHMVL215P17 / “…’ /
S: "9" <R1, BLACK> UHMVL215P18
T: <BLACK, R1> UHMVL215P18 / €“ /
S: "9" <R1, BLACK> P1113
T: <BLACK, R1> P1113 / “‘ /
S: "9" <R1, BLACK> UHMVL215P19
T: <BLACK, R1> UHMVL215P19 / ‘€‹“ /
S: "9" <R1, BLACK> UHMVL215P20
T: <BLACK, R1> UHMVL215P20 / ’ƒ /
S: "9" <R1, BLACK> UHMVL215P21
T: <BLACK, R1> UHMVL215P21 / ƒ€‹“ /
S: "9" <R1, BLACK> UHMVL215P22
T: <BLACK, R1> UHMVL215P22 / ’…“’ /
S: "9" <R1, BLACK> UHMVL215P23
T: <BLACK, R1> UHMVL215P23 / ƒ…‹€ /
S: "9" <R1, BLACK> UHMVL215P24
T: <BLACK, R1> UHMVL215P24 / € /
S: "9" <R1, BLACK> UHMVL215P25
T: <BLACK, R1> UHMVL215P25 / ’‘ /
S: "9" <R1, BLACK> UHMVL215P26
T: <BLACK, R1> UHMVL215P26 / “…‰ /

S: "9" <R1, BLACK> UHMVL216P1
T: <BLACK, R1> UHMVL216P1 / …“ /
S: "9" <R1, BLACK> UHMVL216P2
T: <BLACK, R1> UHMVL216P2 / “…‰ /
S: "9" <R1, BLACK> UHMVL216P3
T: <BLACK, R1> UHMVL216P3 / ‘€‹ /
S: "9" <R1, BLACK> UHMVL216P4
T: <BLACK, R1> UHMVL216P4 / …‹ /
S: "9" <R1, BLACK> UHMVL216P5
T: <BLACK, R1> UHMVL216P5 / ‘“€‹ /
S: "9" <R1, BLACK> UHMVL217P1
T: <BLACK, R1> UHMVL217P1 / “…’ /
S: "9" <R1, BLACK> P1115
T: <BLACK, R1> P1115 / ‹€„ /
S: "9" <R1, BLACK> UHMVL217P2
T: <BLACK, R1> UHMVL217P2 / ““‘ /
S: "9" <R1, BLACK> UHMVL217P3
T: <BLACK, R1> UHMVL217P3 / ‹… /
S: "9" <R1, BLACK> P1116
T: <BLACK, R1> P1116 / ƒ€€ /
S: "9" <R1, BLACK> UHMVL217P4
T: <BLACK, R1> UHMVL217P4 / ‘€ /
S: "9" <R1, BLACK> UHMVL217P5
T: <BLACK, R1> UHMVL217P5 / ‘“€‹ /

S: "9" <R1, BLACK> P1117
T: <BLACK, R1> P1117 / … /
S: "9" <R1, BLACK> UHMVL218P2
T: <BLACK, R1> UHMVL218P2 / €‘€€ /
S: "9" <R1, BLACK> UHMVL218P3
T: <BLACK, R1> UHMVL218P3 / ‘“€‹ /

S: "9" <R1, BLACK> UHMVL219P1
T: <BLACK, R1> UHMVL219P1 / €‹€ /
S: "9" <R1, BLACK> P1118
T: <BLACK, R1> P1118 / ’ /

S: "9" <R1, BLACK> UHMVL219P3
T: <BLACK, R1> UHMVL219P3 / …‹… /
S: "9" <R1, BLACK> UHMVL219P4
T: <BLACK, R1> UHMVL219P4 / „‘€ /
S: "9" <R1, BLACK> UHMVL219P5
T: <BLACK, R1> UHMVL219P5 / “€“ /
S: "9" <R1, BLACK> UHMVL219P6
T: <BLACK, R1> UHMVL219P6 / „““ /
S: "9" <R1, BLACK> P1119
T: <BLACK, R1> P1119 / €ƒ‹ /
S: "9" <R1, BLACK> UHMVL219P7
T: <BLACK, R1> UHMVL219P7 / ‹– /




S: "9" <R1, BLACK> P1120
T: <BLACK, R1> P1120 / …‘„€ /
S: "9" <R1, BLACK> UHMVL220P2
T: <BLACK, R1> UHMVL220P2 / “’€‘ /
S: "9" <R1, BLACK> UHMVL220P3
T: <BLACK, R1> UHMVL220P3 / ‘€‘ /

S: "9" <R1, BLACK> UHMVL221P2
T: <BLACK, R1> UHMVL221P2 / €„‘ /
S: "9" <R1, BLACK> UHMVL221P3
T: <BLACK, R1> UHMVL221P3 / „€‹“’ /
S: "9" <R1, BLACK> UHMVL221P4
T: <BLACK, R1> UHMVL221P4 / €’€ /
S: "9" <R1, BLACK> UHMVL221P5
T: <BLACK, R1> UHMVL221P5 / ‘’€“ /
S: "9" <R1, BLACK> UHMVL221P6
T: <BLACK, R1> UHMVL221P6 / “…’’ /




S: "9" <R1, BLACK> UHMVL222P1
T: <BLACK, R1> UHMVL222P1 / “… /
S: "9" <R1, BLACK> P1030
T: <BLACK, R1> P1030 / €’… /
S: "9" <R1, BLACK> UHMVL222P2
T: <BLACK, R1> UHMVL222P2 / „ /
S: "9" <R1, BLACK> P1031
T: <BLACK, R1> P1031 / €“ /
S: "9" <R1, BLACK> UHMVL222P3
T: <BLACK, R1> UHMVL222P3 / “… /
S: "9" <R1, BLACK> P1032
T: <BLACK, R1> P1032 / ’€ƒ‹ /
S: "9" <R1, BLACK> UHMVL222P4
T: <BLACK, R1> UHMVL222P4 / €ƒ€…‹ /
S: "9" <R1, BLACK> UHMVL222P5
T: <BLACK, R1> UHMVL222P5 / “… /
S: "9" <R1, BLACK> UHMVL222P6
T: <BLACK, R1> UHMVL222P6 / €€ /
S: "9" <R1, BLACK> P1033
T: <BLACK, R1> P1033 / ‘“’ /
S: "9" <R1, BLACK> UHMVL222P7
T: <BLACK, R1> UHMVL222P7 / “…‘ /
S: "9" <R1, BLACK> P1034
T: <BLACK, R1> P1034 / ƒ„€ /
S: "9" <R1, BLACK> UHMVL222P8
T: <BLACK, R1> UHMVL222P8 / ‹“ /
S: "9" <R1, BLACK> UHMVL222P9
T: <BLACK, R1> UHMVL222P9 / ’…“‘ /
S: "9" <R1, BLACK> UHMVL222P10
T: <BLACK, R1> UHMVL222P10 / “…’’ /
S: "9" <R1, BLACK> UHMVL222P11
T: <BLACK, R1> UHMVL222P11 / ’€’ /
S: "9" <R1, BLACK> P1035
T: <BLACK, R1> P1035 / “‹’ /

S: "9" <R1, BLACK> UHMVL222P13
T: <BLACK, R1> UHMVL222P13 / „€“ /
S: "9" <R1, BLACK> UHMVL222P14
T: <BLACK, R1> UHMVL222P14 / €ƒ…„ /
S: "9" <R1, BLACK> UHMVL222P15
T: <BLACK, R1> UHMVL222P15 / “…ƒ /
S: "9" <R1, BLACK> UHMVL222P16
T: <BLACK, R1> UHMVL222P16 / “… /
S: "9" <R1, BLACK> UHMVL222P17
T: <BLACK, R1> UHMVL222P17 / €ƒ…’“ /
S: "9" <R1, BLACK> P1036
T: <BLACK, R1> P1036 / „€ƒ /
S: "9" <R1, BLACK> UHMVL222P18
T: <BLACK, R1> UHMVL222P18 / €’€“ /
S: "9" <R1, BLACK> UHMVL222P19
T: <BLACK, R1> UHMVL222P19 / “…„ /
S: "9" <R1, BLACK> UHMVL222P20
T: <BLACK, R1> UHMVL222P20 / €“ /
S: "9" <R1, BLACK> P1037
T: <BLACK, R1> P1037 / … /
S: "9" <R1, BLACK> UHMVL222P21
T: <BLACK, R1> UHMVL222P21 / €“ /
S: "9" <R1, BLACK> P1038
T: <BLACK, R1> P1038 / “‘€ /
S: "9" <R1, BLACK> UHMVL222P22
T: <BLACK, R1> UHMVL222P22 / “…‘ƒ /
S: "9" <R1, BLACK> P1039
T: <BLACK, R1> P1039 / ’“‘ /
S: "9" <R1, BLACK> UHMVL222P23
T: <BLACK, R1> UHMVL222P23 / €€ /
S: "9" <R1, BLACK> UHMVL222P24
T: <BLACK, R1> UHMVL222P24 / “…‘ /
S: "9" <R1, BLACK> P1040
T: <BLACK, R1> P1040 / €€ /
S: "9" <R1, BLACK> UHMVL223P1
T: <BLACK, R1> UHMVL223P1 / “…‘ƒ /
S: "9" <R1, BLACK> P1121
T: <BLACK, R1> P1121 / …‹ /
S: "9" <R1, BLACK> UHMVL223P2
T: <BLACK, R1> UHMVL223P2 / “‹“ /
S: "9" <R1, BLACK> UHMVL223P3
T: <BLACK, R1> UHMVL223P3 / €„€ /
S: "9" <R1, BLACK> UHMVL223P4
T: <BLACK, R1> UHMVL223P4 / ƒ“‘ /
S: "9" <R1, BLACK> P1122
T: <BLACK, R1> P1122 / ‘“„€ /



S: "9" <R1, BLACK> UHMVL224P1
T: <BLACK, R1> UHMVL224P1 / €‹€ /
S: "9" <R1, BLACK> UHMVL224P2
T: <BLACK, R1> UHMVL224P2 /  /
S: "9" <R1, BLACK> UHMVL224P3
T: <BLACK, R1> UHMVL224P3 / €‹ƒ /
S: "9" <R1, BLACK> UHMVL224P4
T: <BLACK, R1> UHMVL224P4 / ƒ€€ /
S: "9" <R1, BLACK> UHMVL224P5
T: <BLACK, R1> UHMVL224P5 / …’€’ /
S: "9" <R1, BLACK> UHMVL224P6
T: <BLACK, R1> UHMVL224P6 / €’ /
S: "9" <R1, BLACK> UHMVL224P7
T: <BLACK, R1> UHMVL224P7 / “…‘ /
S: "9" <R1, BLACK> UHMVL225P1
T: <BLACK, R1> UHMVL225P1 / “…‘ƒ /
S: "9" <R1, BLACK> P1123
T: <BLACK, R1> P1123 / €ƒ€ /
S: "9" <R1, BLACK> UHMVL225P2
T: <BLACK, R1> UHMVL225P2 / ‘€ƒ€ /

S: "9" <R1, BLACK> UHMVL225P4
T: <BLACK, R1> UHMVL225P4 / “…•‘ /

S: "9" <R1, BLACK> UHMVL225P6
T: <BLACK, R1> UHMVL225P6 / ‹€ /
S: "9" <R1, BLACK> UHMVL225P7
T: <BLACK, R1> UHMVL225P7 / „€’ /
S: "9" <R1, BLACK> UHMVL225P8
T: <BLACK, R1> UHMVL225P8 / € /
S: "9" <R1, BLACK> UHMVL226P1
T: <BLACK, R1> UHMVL226P1 / “…‘ /
S: "9" <R1, BLACK> UHMVL226P2
T: <BLACK, R1> UHMVL226P2 / …“ /
S: "9" <R1, BLACK> UHMVL226P3
T: <BLACK, R1> UHMVL226P3 / ’‹’€ /
S: "9" <R1, BLACK> UHMVL226P4
T: <BLACK, R1> UHMVL226P4 / ‘“„“ /
S: "9" <R1, BLACK> UHMVL226P5
T: <BLACK, R1> UHMVL226P5 / €‹€‘… /
S: "9" <R1, BLACK> UHMVL226P6
T: <BLACK, R1> UHMVL226P6 / „…’… /
S: "9" <R1, BLACK> UHMVL226P7
T: <BLACK, R1> UHMVL226P7 / …‘€ /
S: "9" <R1, BLACK> UHMVL226P8
T: <BLACK, R1> UHMVL226P8 /  /
S: "9" <R1, BLACK> UHMVL226P9
T: <BLACK, R1> UHMVL226P9 / „ /
S: "9" <R1, BLACK> P1124
T: <BLACK, R1> P1124 / €‘’€ /

S: "9" <R1, BLACK> UHMVL227P1
T: <BLACK, R1> UHMVL227P1 / “…‘ /
S: "9" <R1, BLACK> P1041
T: <BLACK, R1> P1041 / ‹ /
S: "9" <R1, BLACK> UHMVL227P2
T: <BLACK, R1> UHMVL227P2 / “ƒ“‹€ /
S: "9" <R1, BLACK> UHMVL227P3
T: <BLACK, R1> UHMVL227P3 / “…’’ /
S: "9" <R1, BLACK> UHMVL227P4
T: <BLACK, R1> UHMVL227P4 / …‘€ /
S: "9" <R1, BLACK> UHMVL227P5
T: <BLACK, R1> UHMVL227P5 / ‘…€ /

S: "9" <R1, BLACK> UHMVL227P7
T: <BLACK, R1> UHMVL227P7 / €“‹ /
S: "9" <R1, BLACK> UHMVL227P8
T: <BLACK, R1> UHMVL227P8 / “…‘… /
S: "9" <R1, BLACK> UHMVL227P9
T: <BLACK, R1> UHMVL227P9 / €ƒ /
S: "9" <R1, BLACK> UHMVL227P10
T: <BLACK, R1> UHMVL227P10 / “…ƒ /
S: "9" <R1, BLACK> UHMVL227P11
T: <BLACK, R1> UHMVL227P11 / €ƒ€ /
S: "9" <R1, BLACK> UHMVL227P12
T: <BLACK, R1> UHMVL227P12 / “… /
S: "9" <R1, BLACK> UHMVL227P13
T: <BLACK, R1> UHMVL227P13 / “…‘” /
S: "9" <R1, BLACK> UHMVL227P14
T: <BLACK, R1> UHMVL227P14 / ‹€‘ /
S: "9" <R1, BLACK> UHMVL227P15
T: <BLACK, R1> UHMVL227P15 / “…‘ /
S: "9" <R1, BLACK> UHMVL227P16
T: <BLACK, R1> UHMVL227P16 / …‹…‘ /
S: "9" <R1, BLACK> UHMVL227P18
T: <BLACK, R1> UHMVL227P18 / “…‘ /
S: "9" <R1, BLACK> P1042
T: <BLACK, R1> P1042 / ‹“ /

S: "9" <R1, BLACK> UHMVL228P1
T: <BLACK, R1> UHMVL228P1 / “…‘ /
S: "9" <R1, BLACK> P1043
T: <BLACK, R1> P1043 / ’ /
S: "9" <R1, BLACK> UHMVL228P2
T: <BLACK, R1> UHMVL228P2 / € /
S: "9" <R1, BLACK> UHMVL228P3
T: <BLACK, R1> UHMVL228P3 / …‘€ /
S: "9" <R1, BLACK> UHMVL228P4
T: <BLACK, R1> UHMVL228P4 / “…‘ /

S: "9" <R1, BLACK> UHMVL229P1
T: <BLACK, R1> UHMVL229P1 / “… /
S: "9" <R1, BLACK> P1044
T: <BLACK, R1> P1044 / €‹’€ /
S: "9" <R1, BLACK> UHMVL229P2
T: <BLACK, R1> UHMVL229P2 / ƒ…‹ /
S: "9" <R1, BLACK> UHMVL229P3
T: <BLACK, R1> UHMVL229P3 / ‹ƒ /
S: "9" <R1, BLACK> UHMVL229P4
T: <BLACK, R1> UHMVL229P4 / ‹“’ /
S: "9" <R1, BLACK> UHMVL229P5
T: <BLACK, R1> UHMVL229P5 / ……… /

S: "9" <R1, BLACK> P1045
T: <BLACK, R1> P1045 / „‹ /
S: "9" <R1, BLACK> UHMVL229P7
T: <BLACK, R1> UHMVL229P7 / “‘ /
S: "9" <R1, BLACK> UHMVL229P8
T: <BLACK, R1> UHMVL229P8 / “… /
S: "9" <R1, BLACK> P1046
T: <BLACK, R1> P1046 / “ /
S: "9" <R1, BLACK> UHMVL229P9
T: <BLACK, R1> UHMVL229P9 / ’‹€ /
S: "9" <R1, BLACK> UHMVL229P10
T: <BLACK, R1> UHMVL229P10 / ƒ€ /
S: "9" <R1, BLACK> UHMVL229P11
T: <BLACK, R1> UHMVL229P11 / ‹ /
S: "9" <R1, BLACK> UHMVL229P12
T: <BLACK, R1> UHMVL229P12 / “……€ /
S: "9" <R1, BLACK> UHMVL229P13
T: <BLACK, R1> UHMVL229P13 / ‘…’“ /
S: "9" <R1, BLACK> UHMVL229P14
T: <BLACK, R1> UHMVL229P14 / ‘…‹ /




S: "9" <R1, BLACK> UHMVL230P2
T: <BLACK, R1> UHMVL230P2 / ’€€ /
S: "9" <R1, BLACK> UHMVL230P3
T: <BLACK, R1> UHMVL230P3 / ’€ /
S: "9" <R1, BLACK> UHMVL230P4
T: <BLACK, R1> UHMVL230P4 / …’ /
S: "9" <R1, BLACK> UHMVL230P5
T: <BLACK, R1> UHMVL230P5 / “‘’€’ /
S: "9" <R1, BLACK> UHMVL230P6
T: <BLACK, R1> UHMVL230P6 / ’‘€‹ /
S: "9" <R1, BLACK> P1047
T: <BLACK, R1> P1047 / …ƒƒ€ /
S: "9" <R1, BLACK> UHMVL189P17
T: <BLACK, R1> UHMVL189P17 / “…• /				***Schetinkin09.02.17***
*S: "9" <R1, BLACK> UHMVL230P7*
*T: <BLACK, R1> UHMVL230P7 / “…• /*
S: "9" <R1, BLACK> P1048
T: <BLACK, R1> P1048 / …… /
S: "9" <R1, BLACK> UHMVL230P8
T: <BLACK, R1> UHMVL230P8 / “‘€’ /
S: "9" <R1, BLACK> UHMVL230P9
T: <BLACK, R1> UHMVL230P9 / …ƒ… /

***VAntonov 10.08.12***
S: "9" <R1, BLACK> UHMVL132P7
T: <BLACK, R1> UHMVL132P7 / €’€ - ®αβξª®Άª  /

*S: "9" <R1, BLACK> N48482400E135321800*
*T: <BLACK, R1> N48482400E135321800 / €‹… - „ ΅ ­¤ ®§.βΰ Ά. /*			***Schetinkin23.05.17***


*S: "9" <R1, BLACK> UHMVL132P22*
*T: <BLACK, R1> UHMVL132P22 / „ /*
*S: "9" <R1, BLACK> UHMVL132P23*
*T: <BLACK, R1> UHMVL132P23 / …’ /*
*S: "9" <R1, BLACK> UHMVL132P24*
*T: <BLACK, R1> UHMVL132P24 / €„€ /*

***VAntonov 10.08.12***

***VAntonov 11.09.12***

*S: "9" <R1, BLACK> P441*
*T: <BLACK, R1> P441 / ‹…„€ /*
*S: "9" <R1, BLACK> P442		Schetinkin17.11.15*
*T: <BLACK, R1> P442 / ‘€ /*
*S: "9" <R1, BLACK> P443*
*T: <BLACK, R1> P443 /  /*

*S: "9" <R1, BLACK> P444*
*T: <BLACK, R1> P444 / ‘€„ /*
*S: "9" <R1, BLACK> P445*
*T: <BLACK, R1> P445 / “‹„“ /*
*S: "9" <R1, BLACK> P446*
*T: <BLACK, R1> P446 / ƒ€ /*
*S: "9" <R1, BLACK> P448*			*Schetinkin17.11.15*
*T: <BLACK, R1> P448 / „ƒ /*
*S: "9" <R1, BLACK> P449*			*Schetinkin17.11.15*
*T: <BLACK, R1> P449 / …€ /*
*S: "9" <R1, BLACK> P450			Schetinkin17.11.15*
*T: <BLACK, R1> P450 / ‹…“ /*
*S: "9" <R1, BLACK> P451			Schetinkin17.11.15*
*T: <BLACK, R1> P451 / €€ /*
*S: "9" <R1, BLACK> P452			Schetinkin17.11.15*
*T: <BLACK, R1> P452 / €‘€’ /*
*S: "9" <R1, BLACK> P453			Schetinkin17.11.15*
*T: <BLACK, R1> P453 / €’‘€ /*
*S: "9" <R1, BLACK> P454			Schetinkin17.11.15*
*T: <BLACK, R1> P454 / ‘ /*
*S: "9" <R1, BLACK> P455			Schetinkin17.11.15*
*T: <BLACK, R1> P455 / „“€’ /*

***VAntonov 11.09.12***


***Chemeris S Denis 20.11.12***

*S: "9" <R1, BLACK> PIKOD*
*T: <BLACK, R1> PIKOD / „ /*		***Schetinkin30.01.17***

***Chemeris S Denis 20.11.12***


***VAntonov 06.11.13***

S: "9" <R1, BLACK> PANUR
T: <BLACK, R1> PANUR / €“ /
S: "9" <R1, BLACK> AKRIS
T: <BLACK, R1> AKRIS / €‘ /
S: "9" <R1, BLACK> BEREL
T: <BLACK, R1> BEREL / ……‹ /
S: "9" <R1, BLACK> USADI
T: <BLACK, R1> USADI / “‘€„ /


***VAntonov 06.11.13***

;VAntonov10.12.13

*S: "9" <R1, BLACK> P510*
*T: <BLACK, R1> P510 / ΰ. € /*		***Schetinkin30.01.17***

;VAntonov10.12.13

*KDP UJNO-SAKHALINSK-VAntonov10.09.14*
*S: "9" <R1> GIPUS*
*T: <R1> GIPUS / GIPUS/*				***Schetinkin30.01.17***
*S: "9" <R1> BELIL*
*T: <R1> BELIL / BELIL/*				***Schetinkin30.01.17***
*S: "9" <R1> POGEM*
*T: <R1> POGEM / POGEM/*				***Schetinkin30.01.17***
*SD:0.0,-1.0*
*S: "9" <R1> P512*
*T: <R1> P512 / ‘…ƒ‘/*				***Schetinkin30.01.17***
SD:0.0,0.0
S: "9" <R1> P513
T: <R1> P513 / ‘‹/
*S: "9" <R1> P514*
*SD:0.0,-1.0*
*T: <R1> P514 / ‹•‚€’€/*			***Schetinkin30.01.17***
SD:0.0,0.0
*S: "9" <R1> P515*
*T: <R1> P515 / ‘€/*					***Schetinkin30.01.17***
*S: "9" <R1> P516*
*T: <R1> P516 / ‹—/*					***Schetinkin30.01.17***
*S: "9" <R1> P518*
*T: <R1> P518 / ’–…/*				***Schetinkin30.01.17***
*KDP UJNO-SAKHALINSK*

;Schetinkin17.11.15

S: "9" <R1, BLACK> P950
T: <BLACK, R1> P950 / … /
S: "9" <R1, BLACK> P951
T: <BLACK, R1> P951 / “…‹ /
S: "9" <R1, BLACK> P952
T: <BLACK, R1> P952 / „ /
S: "9" <R1, BLACK> P953
T: <BLACK, R1> P953 / ’“… /
S: "9" <R1, BLACK> P954
T: <BLACK, R1> P954 / … /
S: "9" <R1, BLACK> P955
T: <BLACK, R1> P955 / ƒ“„“ /
S: "9" <R1, BLACK> P956
T: <BLACK, R1> P956 / ‘’ /
S: "9" <R1, BLACK> P957
T: <BLACK, R1> P957 / ‹ /
* S: "9" <R1, BLACK> P958 *
* T: <BLACK, R1> P958 / „ / *
S: "9" <R1, BLACK> P959
T: <BLACK, R1> P959 / ‘’ /
S: "9" <R1, BLACK> P960
T: <BLACK, R1> P960 / „€ƒ /

;Schetinkin23.11.16
*S: "9" <R1, BLACK> UHMVLP1005*
*T: <BLACK, R1> UHMVLP1005 / €’ /*
*S: "9" <R1, BLACK> UHMVLP1006*
*T: <BLACK, R1> UHMVLP1006 / ‘‹‹ /*
S: "9" <R1, BLACK> UHMVLP1007
T: <BLACK, R1> UHMVLP1007 / ƒ€ /
S: "9" <R1, BLACK> UHMVLP1008
T: <BLACK, R1> UHMVLP1008 / „€ /
S: "9" <R1, BLACK> UHMVLP1009
T: <BLACK, R1> UHMVLP1009 / ’€ - ªβο΅ΰμαª®¥ /
S: "9" <R1, BLACK> UHMVLP1010
T: <BLACK, R1> UHMVLP1010 / €€ /
S: "9" <R1, BLACK> UHMVLP1011
T: <BLACK, R1> UHMVLP1011 / “ƒ… /
S: "9" <R1, BLACK> UHMVLP1012
T: <BLACK, R1> UHMVLP1012 / “‘‹ /
S: "9" <R1, BLACK> UHMVLP1013
T: <BLACK, R1> UHMVLP1013 / € /

***Schetinkin23.05.17***
S: "9" <R1, BLACK> NANOM
T: <BLACK, R1> NANOM / € /
S: "9" <R1, BLACK> RUBIN
T: <BLACK, R1> RUBIN / “ /
*S: "9" <R1, BLACK> ONIKA*
*T: <BLACK, R1> ONIKA / € /*
S: "9" <R1, BLACK> TRITA
T: <BLACK, R1> TRITA / ’’€ /
S: "9" <R1, BLACK> KROMU
T: <BLACK, R1> KROMU / “ /
S: "9" <R1, BLACK> OKLAD
T: <BLACK, R1> OKLAD / ‹€„ /
S: "9" <R1, BLACK> SPILU
T: <BLACK, R1> SPILU / ‘‹“ /


***VANTONOV_07.10.17***
S: "9" <R1, BLACK> UHMVLDRIGU
T: <BLACK, R1> UHMVLDRIGU / „ƒ“ /
S: "9" <R1, BLACK> UHMVLGOBIN
T: <BLACK, R1> UHMVLGOBIN / ƒ /
S: "9" <R1, BLACK> UHMVLSKARB
T: <BLACK, R1> UHMVLSKARB / ‘€ /
S: "9" <R1, BLACK> UHMVLORIEN
T: <BLACK, R1> UHMVLORIEN / … /
S: "9" <R1, BLACK> UHMVLBLOGI
T: <BLACK, R1> UHMVLBLOGI / ‹ƒ /
S: "9" <R1, BLACK> UHMVLKRUIS
T: <BLACK, R1> UHMVLKRUIS / “‘ /

S: "9" <R1, BLACK> UHMVLKUTKA
T: <BLACK, R1> UHMVLKUTKA / “’€ /
S: "9" <R1, BLACK> UHMVLMISKI
T: <BLACK, R1> UHMVLMISKI / ‘ /

S: "9" <R1, BLACK> UHMVLBANAI
T: <BLACK, R1> UHMVLBANAI / €€ /
S: "9" <R1, BLACK> UHMVLIRELE
T: <BLACK, R1> UHMVLIRELE / …‹… /

***Antonov01.12.17***
S: "9" <R1, BLACK> P2153
T: <BLACK, R1> P2153 / €“…’ /

S: "9" <R1, BLACK> P2191
T: <BLACK, R1> P2191 / €“‹ /
S: "9" <R1, BLACK> P2192
T: <BLACK, R1> P2192 / €“‘ /

S: "9" <R1, BLACK> P2193
T: <BLACK, R1> P2193 / ‹ /
S: "9" <R1, BLACK> P2194
T: <BLACK, R1> P2194 / €‘‹€ /
S: "9" <R1, BLACK> P2195
T: <BLACK, R1> P2195 / ‹€€‹ /
S: "9" <R1, BLACK> P2196
T: <BLACK, R1> P2196 / €“ /

SD:-7,0
S: "9" <R1, BLACK> UHMVL195P10
T: <BLACK, R1> UHMVL195P10 / “‘€‹ /


SD:-3,-1
S: "9" <R1, BLACK> UHMVL200P4
T: <BLACK, R1> UHMVL200P4 / €… /

SD:1,-1
S: "9" <R1, BLACK> UHMVL181P3
T: <BLACK, R1> UHMVL181P3 / “…††  /

SD:0,-1
S: "9" <R1, BLACK> UHMVL225P3
T: <BLACK, R1> UHMVL225P3 / ƒ…“ /
S: "9" <R1, BLACK> UHMVL225P5
T: <BLACK, R1> UHMVL225P5 / ‘ /

SD:0,1
S: "9" <R1, BLACK> UHMVL227P17
T: <BLACK, R1> UHMVL227P17 /  /
SD:-7,0
S: "9" <R1, BLACK> P1062
T: <BLACK, R1> P1062 / ’ /
S: "9" <R1, BLACK> UHMVL184P2
T: <BLACK, R1> UHMVL184P2 / ‹…’€ /

SD:0,0
S: "9" <R1, BLACK> UHMVL222P12
T: <BLACK, R1> UHMVL222P12 / “…‘’ - ’‘/



S: "9" <R1, BLACK> UHMVL93P1
T: <BLACK, R1> UHMVL93P1 / €ƒ‚… - « £®Ά¥ι¥­αª /

S: "9" <R1, BLACK> UHMVL132P9
T: <BLACK, R1> UHMVL132P9 / €‘ -  ©η¨ε¨­αª /

SD: -0.0, -2.0
S: "9" <R1, BLACK> UHMVL93P12
T: <BLACK, R1> UHMVL93P12 / … - ª¨¬η ­ /

S: "9" <R1, BLACK> UHMVL93P8
T: <BLACK, R1> UHMVL93P8 / … - ”¥Άΰ «μαª /

S: "9" <R1, BLACK> UHMVL143P1
T: <BLACK, R1> UHMVL143P1 / ƒ“ -  £¤ £ η¨ /

S: "9" <R1, BLACK> UHMVL132P10
T: <BLACK, R1> UHMVL132P10 / €€ - €ΰε ΰ  /

S: "9" <R1, BLACK> UHMVL149P4
T: <BLACK, R1> UHMVL149P4 / €‹… - ‡¥ο /

S: "9" <R1, BLACK> UHMVL135P6
T: <BLACK, R1> UHMVL135P6 /  - ¨¬ ­®Άαª /

S: "9" <R1, BLACK> UHMVL135P9
T: <BLACK, R1> UHMVL135P9 / €ƒ - ‘Ά®΅®¤­λ© /

S: "9" <R1, BLACK> UHMVL136P1
T: <BLACK, R1> UHMVL136P1 / € - ®¬­ ª /

S: "9" <R1, BLACK> UHMVL139P3
T: <BLACK, R1> UHMVL139P3 / ’… - ªβο΅ΰμαª¨©-€¬γΰαª /

S: "9" <R1, BLACK> UHMVL195P11
T: <BLACK, R1> UHMVL195P11 / ƒ€ - ƒ®ΰ­λ© /

S: "9" <R1, BLACK> UHMVL151P1
T: <BLACK, R1> UHMVL151P1 / ƒ“ - —γ¬¨ª ­ /

S: "9" <R1, BLACK> UHMVL151P3
T: <BLACK, R1> UHMVL151P3 / ’“ƒ“ - ’γ£γΰ /

S: "9" <R1, BLACK> UHMVL153P7
T: <BLACK, R1> UHMVL153P7 /  - ¨ª®« ¥Άαª-­ -€¬γΰ¥ /

S: "9" <R1, BLACK> UHMVL177P5
T: <BLACK, R1> UHMVL177P5 / „… - ε  /

S: "9" <R1, BLACK> UHMVL177P15
T: <BLACK, R1> UHMVL177P15 / ’‹ - ®£«¨ª¨ /

S: "9" <R1, BLACK> UHMVL151P35
T: <BLACK, R1> UHMVL151P35 / „’ -  εβ¥ΰαª /

S: "9" <R1, BLACK> UHMVL168P2
T: <BLACK, R1> UHMVL168P2 / •“’ - ¦­®-‘ ε «¨­αª /

S: "9" <R1, BLACK> UHMVL162P10
T: <BLACK, R1> UHMVL162P10 / ‹€ - ‡®­ «μ­®¥ /

S: "9" <R1, BLACK> UHMVL2P1
T: <BLACK, R1> UHMVL2P1 / ‘€„ - €«¥ªα ­¤ΰ®Άαª-‘ ε «¨­αª¨© /

S: "9" <R1, BLACK> UHMVL89P1
T: <BLACK, R1> UHMVL89P1 / …‹€ƒ - ¥«μª ­ /

S: "9" <R1, BLACK> UHMVL16P1
T: <BLACK, R1> UHMVL16P1 / ’“‘ - ¨¬. ®«¨­λ α¨―¥­ª® /

S: "9" <R1, BLACK> UHMVL6P38
T: <BLACK, R1> UHMVL6P38 / …‚ - ‚« ¤¨Ά®αβ®ª-­¥Ά¨η¨ /

S: "9" <R1, BLACK> UHMVL45P1
T: <BLACK, R1> UHMVL45P1 / ‹“ - ‚« ¤¨Ά®αβ®ª-§.«ξη¨ /

S: "9" <R1, BLACK> UHMVL29P5
T: <BLACK, R1> UHMVL29P5 / ‘‚ƒ€ - ‘®Ά.ƒ Ά ­μ- ©-ƒ βª  /

S: "9" <R1, BLACK> UHMVL132P21
T: <BLACK, R1> UHMVL132P21 / ’ - ’ΰ®¨ζª®¥ /

S: "9" <R1, BLACK> UHMVL132P27
T: <BLACK, R1> UHMVL132P27 / …ƒ’€ -  ΰ¨¨­αª®¥ /

S: "9" <R1, BLACK> UHMVL132P25
T: <BLACK, R1> UHMVL132P25 / ’€ - ¨¦­¥β ¬΅®Άαª®¥ /

S: "9" <R1, BLACK> UHMVL20P3
T: <BLACK, R1> UHMVL20P3 / ‘„ - ®£®ΰ®¤αª®¥ /

S: "9" <R1, BLACK> UHMVL18P5
T: <BLACK, R1> UHMVL18P5 / ‹“… - •¥ΰ―γη¨ /

S: "9" <R1, BLACK> UHMVL29P12
T: <BLACK, R1> UHMVL29P12 / €“ - ®¬α®¬®«μαª-­ -€¬γΰ¥ /

S: "9" <R1, BLACK> UHMVL133P4
T: <BLACK, R1> UHMVL133P4 / ƒ„… - —¥£¤®¬λ­ /

S: "9" <R1, BLACK> UHMVL36P3
T: <BLACK, R1> UHMVL36P3 / “…‹ - γª ­ /

S: "9" <R1, BLACK> UHMVL36P1
T: <BLACK, R1> UHMVL36P1 / ‚“ - ®Ά®ªγΰ®Άª  /

S: "9" <R1, BLACK> UHMVL36P2
T: <BLACK, R1> UHMVL36P2 / €…„ - ®΅¥¤  /

S: "9" <R1, BLACK> UHMVL67P1
T: <BLACK, R1> UHMVL67P1 / „… - „ «μ­¥ΰ¥η¥­αª /

S: "9" <R1, BLACK> UHMVL56P2
T: <BLACK, R1> UHMVL56P2 / “‘“ - “ααγΰ¨©αª- ΰ ­®Άαª¨© /

S: "9" <R1, BLACK> UHMVL42P2
T: <BLACK, R1> UHMVL42P2 / “ƒ‹‚ - –¥­βΰ «μ­ ο “£«®Ά ο /

S: "9" <R1, BLACK> UHMVL47P5
T: <BLACK, R1> UHMVL47P5 / ‹€‘“ - ‘®ª®«®Άª  /

S: "9" <R1, BLACK> UHMVL43P9
T: <BLACK, R1> UHMVL43P9 / … -  Ά «¥ΰ®Ά® /

S: "9" <R1, BLACK> UHMVL44P1
T: <BLACK, R1> UHMVL44P1 / €ƒ‘‘“ - €£§γ /

S: "9" <R1, BLACK> UHMVL44P3
T: <BLACK, R1> UHMVL44P3 / “’ - “­βλ /

S: "9" <R1, BLACK> UHMVL75P2
T: <BLACK, R1> UHMVL75P2 / ‘‚…’‹ - ‘Ά¥β« ο /
S: "9" <R1, BLACK> UHMVL76P1
T: <BLACK, R1> UHMVL76P1 / ‘€ƒ€ - ‘ ¬ ΰ£  /

S: "9" <R1, BLACK> UHMVL65P8
T: <BLACK, R1> UHMVL65P8 / …„ - …¤¨­ª  /
S: "9" <R1, BLACK> UHMVL44P7
T: <BLACK, R1> UHMVL44P7 / “‘‹ - “αβμ-‘®΅®«¥Άª  /

S: "9" <R1, BLACK> UHMVL44P8
T: <BLACK, R1> UHMVL44P8 / €‚€ -  ªα¨¬®Άª  /

S: "9" <R1, BLACK> UHMVL44P9
T: <BLACK, R1> UHMVL44P9 / €ƒ“ - €¬£γ /

S: "9" <R1, BLACK> UHMVL71P7
T: <BLACK, R1> UHMVL71P7 / ’…“ - ’¥ΰ­¥© /

S: "9" <R1, BLACK> UHMVL61P3
T: <BLACK, R1> UHMVL61P3 /  - ¨ª®« ¥Άª -ΰ¨¬®ΰαª. /

S: "9" <R1, BLACK> UHMVL46P1
T: <BLACK, R1> UHMVL46P1 / ‘‘€ - ‘®α­®Ά ο  ¤μ /

S: "9" <R1, BLACK> UHMVL46P2
T: <BLACK, R1> UHMVL46P2 / ƒ - ®£ΰ ­¨η­λ© βΰο¤ /

S: "9" <R1, BLACK> UHMVL49P3
T: <BLACK, R1> UHMVL49P3 / €‘… - €ΰα¥­μ¥Ά /

S: "9" <R1, BLACK> UHMVL70P4
T: <BLACK, R1> UHMVL70P4 / ‘ - ®ι¨­® /

S: "9" <R1, BLACK> UHMVL75P1
T: <BLACK, R1> UHMVL75P1 / •’ - ε®β­¨η¨© /


S: "9" <R1, BLACK> UHMVL73P4
T: <BLACK, R1> UHMVL73P4 / ‹€“•… - ‹ γε¥ /


S: "9" <R1, BLACK> UHMVL64P9
T: <BLACK, R1> UHMVL64P9 / €„„ - €¤  /

S: "9" <R1, BLACK> UHMVL71P4
T: <BLACK, R1> UHMVL71P4 / ’“…’ - « αβγ­ /


S: "9" <R1, BLACK> UHMVL85P11
T: <BLACK, R1> UHMVL85P11 / …‹€ƒ - ¥«μª ­ /

S: "9" <R1, BLACK> UHMVL93P21
T: <BLACK, R1> UHMVL93P21 / €€ - €ο­ /



S: "9" <R1, BLACK> UHMVL93P30
T: <BLACK, R1> UHMVL93P30 / €‘ - ε®βαª /

SD:2,-1
S: "9" <R1, BLACK> UHMVL91P2
T: <BLACK, R1> UHMVL91P2 / €€ - €ΰª  /


SD:0,0
S: "9" <R1, BLACK> UHMVL148P1
T: <BLACK, R1> UHMVL148P1 / “‹€‹ /

S: "9" <R1, BLACK> UHMVL93P24
T: <BLACK, R1> UHMVL93P24 / ’“ - ’γªη¨ /


S: "9" <R1, BLACK> UHMVL100P4
T: <BLACK, R1> UHMVL100P4 / €€ /

S: "9" <R1, BLACK> UHMVL97P23
T: <BLACK, R1> UHMVL97P23 / ‡€… /

S: "9" <R1, BLACK> UHMVL97P37
T: <BLACK, R1> UHMVL97P37 / ‹€ /
S: "9" <R1, BLACK> UHMVL94P22
T: <BLACK, R1> UHMVL94P22 / “‹… /

S: "9" <R1, BLACK> UHMVL96P20
T: <BLACK, R1> UHMVL96P20 / ‘ /

S: "9" <R1, BLACK> UHMVL114P7
T: <BLACK, R1> UHMVL114P7 / …€ /

S: "9" <R1, BLACK> UHMVL97P30
T: <BLACK, R1> UHMVL97P30 / – /

S: "9" <R1, BLACK> UHMVL96P1
T: <BLACK, R1> UHMVL96P1 / …€ /

S: "9" <R1, BLACK> UHMVL97P12
T: <BLACK, R1> UHMVL97P12 / €€ /

S: "9" <R1, BLACK> UHMVL102P9
T: <BLACK, R1> UHMVL102P9 / … /

S: "9" <R1, BLACK> UHMVL108P7
T: <BLACK, R1> UHMVL108P7 / ƒ /

S: "9" <R1, BLACK> UHMVL119P1
T: <BLACK, R1> UHMVL119P1 / ’‹ /

S: "9" <R1, BLACK> UHMVL117P52
T: <BLACK, R1> UHMVL117P52 / •€‹ /

S: "9" <R1, BLACK> UHMVL118P3
T: <BLACK, R1> UHMVL118P3 / €•€‹ /

S: "9" <R1, BLACK> UHMVL119P3
T: <BLACK, R1> UHMVL119P3 / €‹ /

S: "9" <R1, BLACK> UHMVL120P4
T: <BLACK, R1> UHMVL120P4 / ‡… /

S: "9" <R1, BLACK> UHMVL120P10
T: <BLACK, R1> UHMVL120P10 / ‘‚ /


S: "9" <R1, BLACK> UHMVL121P2
T: <BLACK, R1> UHMVL121P2 / €‹€’ /

S: "9" <R1, BLACK> UHMVL121P15
T: <BLACK, R1> UHMVL121P15 / ‹‚ /

S: "9" <R1, BLACK> UHMVL121P21
T: <BLACK, R1> UHMVL121P21 / …‘‘ /

S: "9" <R1, BLACK> UHMVL120P25
T: <BLACK, R1> UHMVL120P25 / ‹ /

S: "9" <R1, BLACK> UHMVL125P8
T: <BLACK, R1> UHMVL125P8 / “‘’€ /


S: "9" <R1, BLACK> UHMVL226P10
T: <BLACK, R1> UHMVL226P10 /  /
S: "9" <R1, BLACK> UHMVL178P29
T: <BLACK, R1> UHMVL178P29 / ‹ /
S: "9" <R1, BLACK> UHMVL223P5
T: <BLACK, R1> UHMVL223P5 / ‡ /
S: "9" <R1, BLACK> UHMVL220P1
T: <BLACK, R1> UHMVL220P1 / € /
S: "9" <R1, BLACK> UHMVL207P1
T: <BLACK, R1> UHMVL207P1 / …€’ /
S: "9" <R1, BLACK> UHMVL178P17
T: <BLACK, R1> UHMVL178P17 / ‘€’€ /
S: "9" <R1, BLACK> UHMVL201P1
T: <BLACK, R1> UHMVL201P1 / ‘…… /
S: "9" <R1, BLACK> UHMVL230P1
T: <BLACK, R1> UHMVL230P1 / ‘“‘ /
S: "9" <R1, BLACK> UHMVL178P9
T: <BLACK, R1> UHMVL178P9 / ‘‹ /
S: "9" <R1, BLACK> UHMVL194P1
T: <BLACK, R1> UHMVL194P1 / €’“ /
S: "9" <R1, BLACK> UHMVL190P1
T: <BLACK, R1> UHMVL190P1 / € - €/
S: "9" <R1, BLACK> UHMVL189P1
T: <BLACK, R1> UHMVL189P1 / „… /









