N: "GEO LPM47 "

S: "1" <R1> LPM4701 
T: <R2> LPM4701   	/ Архара /
S: "1" <R1> LPM4702 
T: <R2> LPM4702   	/ Новобурейский /
S: "1" <R1> LPM4703 
T: <R2> LPM4703   	/ Завитинск /
S: "1" <R1> LPM4704 
T: <R2> LPM4704   	/ Чеугда /
S: "1" <R1> LPM4705 
T: <R2> LPM4705   	/ г.Б.Осинда /
S: "1" <R1> LPM4706 
T: <R2> LPM4706   	/ Кундур /

L: <BLUE, full>
L: * LPM47 * LPM4701, LPM4702, LPM4703, LPM4704, LPM4705, LPM4706, LPM4707