N: "GEO LPM45 "

S: "1" <R1> LPM4501 
T: <R2> LPM4501   	/ Шимановск /
S: "1" <R1> LPM4502 
T: <R2> LPM4502   	/ Саскаль /
S: "1" <R1> LPM4503 
T: <R2> LPM4503   	/ Аносова /
S: "1" <R1> LPM4504 
T: <R2> LPM4504   	/ Переселенец /
S: "1" <R1> LPM4505 
T: <R2> LPM4505   	/ Усть Тыгда /
S: "1" <R1> LPM4506 
T: <R2> LPM4506   	/ Чагоян /


L: <BLUE, full>
L: * LPM45 * LPM4501, LPM4502, LPM4503, LPM4504, LPM4505, LPM4506, LPM4507