N: "GEO LPM55"

S: "1" <R1> LPM5501
T: <R2> LPM5501	/ Магдагачи /
S: "1" <R1> LPM5502
T: <R2> LPM5502	/ Апрельский /
S: "1" <R1> LPM5503
T: <R2> LPM5503	/ Тыгда /
S: "1" <R1> LPM5504
T: <R2> LPM5504	/ у.р.Сиваки /
S: "1" <R1> LPM5505
T: <R2> LPM5505	/ у.р.М.Онон /
S: "1" <R1> LPM5506
T: <R2> LPM5506	/ у.р.Магдагачи /


L: <BLUE, full>
L: * LPM55 * LPM5501, LPM5502, LPM5503, LPM5504, LPM5505, LPM5506, LPM5507