N: "GEO LPM56"

S: "1" <R1> LPM5601
T: <R2> LPM5601	/ Магдагачи /
S: "1" <R1> LPM5602
T: <R2> LPM5602	/ Толбузино /
S: "1" <R1> LPM5603
T: <R2> LPM5603	/ Таежный /
S: "1" <R1> LPM5604
T: <R2> LPM5604	/ Игнашино /
S: "1" <R1> LPM5605
T: <R2> LPM5605	/ Е.Павлович /
S: "1" <R1> LPM5606
T: <R2> LPM5606	/ Тахтамыгда /
S: "1" <R1> LPM5607
T: <R2> LPM5607	/ Магдагачи /

L: <BLUE, full>
L: * LPM56 * LPM5601, LPM5602, LPM5603, LPM5604, LPM5605, LPM5606, LPM5607