N: "GEO LPR08"

S: "1" <R1> LPR0801
T: <R2> LPR0801	/ Аэр. Дземги /
S: "1" <R1> LPR0802
T: <R2> LPR0802	/ Старт /
S: "1" <R1> LPR0803
T: <R2> LPR0803	/ Уст. р. Джиакунь /
S: "1" <R1> LPR0804
T: <R2> LPR0804	/ Горин /
S: "1" <R1> LPR0805
T: <R2> LPR0805	/ Галичный /
S: "1" <R1> LPR0806
T: <R2> LPR0806	/ Аэр. Дземги /

L: <BLUE, full>
L: * LPR08 * LPR0801, LPR0802, LPR0803, LPR0804, LPR0805, LPR0806