N: "GEO LPR29"

S: "1" <R1> LPR2901
T: <R2> LPR2901	/ Аэр. Чумикан /
S: "1" <R1> LPR2902
T: <R2> LPR2902	/ Удское /
S: "1" <R1> LPR2903
T: <R2> LPR2903	/ Уст. р. Наму /
S: "1" <R1> LPR2904
T: <R2> LPR2904	/ Баладек /
S: "1" <R1> LPR2905
T: <R2> LPR2905	/ Уст. р. Миня /
S: "1" <R1> LPR2906
T: <R2> LPR2906	/ Удское /
S: "1" <R1> LPR2907
T: <R2> LPR2907	/ Аэр. Чумикан /

L: <BLUE, full>
L: * LPR29 * LPR2901, LPR2902, LPR2903, LPR2904, LPR2905, LPR2906, LPR2907